### ISSUE TITLE
Can not update org.kde.Platform

### ISSUE THREAD

**Issue by zmekinski** [elementary/appcenter#1178] opened 2020-01-15 06:47 UTC

**Comment by davidmhewitt** [comment] 2020-04-07 08:01
Are you still experiencing this issue? Does it update using `flatpak update` in the terminal?

**Comment by davidmhewitt** [comment] 2020-04-14 16:05
I'll close this issue due to a lack of details to help us be able to diagnose the issue.

OP, if you're still experiencing this, please use the following commands in the terminal to get debug output from AppCenter, reproduce the problem, and paste the output into this issue:

```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary,appcenter
```

**Closed by davidmhewitt** 2020-04-14 16:05 UTC
Labels: Status: Incomplete
