### ISSUE TITLE
[Feature] List Flatpak Applications by Default

### ISSUE THREAD

**Issue by Nic-Wow1** [elementary/appcenter#858] opened 2018-10-14 17:45 UTC
**Why?** ElementaryOS is on the frontier of Linux OSes and Flatpak's goals are very similar to Elemenary's with Secure Sandboxing and OpenSource.

**Comment by btkostner** [comment] 2018-10-14 17:50
Closing this as a duplicate of #712

**Closed by btkostner** 2018-10-14 17:50 UTC
