### ISSUE TITLE
Multiple prompts saying "authentication is required to refresh the system sources"

### ISSUE THREAD

**Issue by gka** [elementary/appcenter#546] opened 2017-11-24 07:31 UTC
Every time my system wakes up I see multiple prompts saying "authentication is required to refresh the system sources". Then I have to close them all one by one.

Same bug as this one https://bugs.launchpad.net/appcenter/+bug/1617687 except it isn't fixed at all.

**Comment by mdh34** [comment] 2017-11-25 19:30
Could you test running `sudo apt update` and see if it throws any errors? I had the same problem when one of my ppa's wasn't set up correctly

**Comment by josjoslyn** [comment] 2017-12-03 08:53
I am seeing this same issue after the OS (Elementary OS 0.4.1 Loki (64bit).  Cancel removes the popup, but everytime the OS is locked for a period of time - typically overnight the issue will once again present itself.  Short periods of 'lockup' (an hour or so) the issue is not seen.

Is this an issue created by a 'periodic check/refresh' of the 'AppCentre' looking for updates which is somehow unresolved by the system state/condition during lockup?

**Comment by gka** [comment] 2017-12-05 17:05
`sudo apt update` indeed shows some errors because some repositories don't have correct public keys, which happens sometimes. I guess the correct behaviour is to just skip those repositories on system updates, which is what `apt` is doing be default, I think. 

```
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E074D16EB6FF4DE3
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/chrysn/openscad/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by armaccloud** [comment] 2017-12-15 22:52
I am also having this issue and it doesn't accept my password.
There are no errors when performing `sudo apt update` however.

**Comment by gka** [comment] 2017-12-17 12:50
I fixed this by uninstalling appcenter. Thanks.

**Comment by fabianthoma** [comment] 2018-01-02 17:48
@gka: Your Software Sources are not configured right, that's why updating fails. We've added an additional Error dialog for this in #503. The correct behavior is fixing your software sources and installing the gpg keys needed to your system. Everything else is insecure and unsupported by appcenter.

@josjoslyn: Thank you for providing additional details, I'll see if I can reproduce this issue.

**Comment by fabianthoma** [comment] 2018-01-02 17:52
This seems to be a duplicate of #499.

**Closed by fabianthoma** 2018-01-02 17:52 UTC

**Comment by toshe** [comment] 2018-09-05 09:41
:+1:
