### ISSUE TITLE
org.gnome.Platform Flatpak runtime won't update Eos 5.1

### ISSUE THREAD

**Issue by jordanKlinux** [elementary/appcenter#1222] opened 2020-02-25 19:03 UTC
![Screenshot from 2020-02-25 20-01-29](https://user-images.githubusercontent.com/61474117/75278237-691de580-5801-11ea-8492-8b04a4fb5e9d.png)        Even if i click update it never goes away.

**Comment by aadilayub** [comment] 2020-02-27 06:17
Experiencing the same issue. Another flatpak runtime, `org.freedesktop.Sdk` also won't update through AppCenter.

![Screenshot from 2020-02-27 11-15-39](https://user-images.githubusercontent.com/31581044/75417326-8a421b80-5952-11ea-9232-b54f5f7aa0e2.png)

**Comment by EGY-SuperOne** [comment] 2020-02-27 22:54
Same issue here, after clicking on update it says updating for a second then it remains the same.
sudo apt update & sudo apt upgrade doesn't show any upgradable component.

![Screenshot from 2020-02-28 00-45-23](https://user-images.githubusercontent.com/10738474/75494403-d6c63f00-59c4-11ea-9e12-66160992f66f.png)

**Comment by aadilayub** [comment] 2020-02-28 04:01
@EGY-SuperOne the command for updating flatpak packages is `flatpak update`. However, even running that results in an unsuccessful update on eOS at the moment.

![image](https://user-images.githubusercontent.com/31581044/75509249-c33cc780-5a08-11ea-9b42-e15adb1eaa22.png)

**Comment by ryonakano** [comment] 2020-02-28 04:34
This seems like a duplicate of #1204.

**Closed by ryonakano** 2020-02-28 04:34 UTC
