### ISSUE TITLE
Text overflows update button 

### ISSUE THREAD

**Issue by alchehabii** [elementary/appcenter#555] opened 2017-12-27 10:43 UTC
![screenshot from 2017-12-26 18 09 46](https://user-images.githubusercontent.com/10380737/34379274-bb4884ee-eafa-11e7-8b3a-014fb3e403d9.png)

**Comment by febrezo** [comment] 2017-12-27 11:09
Confirmed in Spanish version.

**Comment by peteruithoven** [comment] 2017-12-27 14:56
Duplicate: https://github.com/elementary/appcenter/issues/535 ?
Looks fixed, but not released?

**Comment by danrabbit** [comment] 2017-12-27 17:53
Closing as a duplicate of #535. This was fixed in PR #536

**Closed by danrabbit** 2017-12-27 17:53 UTC
