### ISSUE TITLE
Apos instalação de packages

### ISSUE THREAD

**Issue by rodrigoaraujolima92** [elementary/appcenter#1166] opened 2019-12-31 23:32 UTC
parou de atualizar

**Comment by cassidyjames** [comment] 2020-01-07 23:11
Gonna need more details on what is happening and how to reproduce it.

**Comment by davidmhewitt** [comment] 2020-02-13 18:15
Closing due to activity, please re-open with additional details if you're still experiencing this issue.

**Closed by davidmhewitt** 2020-02-13 18:15 UTC
Labels: Status: Incomplete
