### ISSUE TITLE
Integrate Nitrokey support to easily install new software with AppCenter

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/appcenter#936] opened 2019-01-20 13:04 UTC
What it says on the tin!
This issue is thematically well suited to the following discussions:
elementary/pantheon-agent-polkit#33
elementary/pantheon-agent-polkit#40
elementary/greeter#230
elementary/mail#345
elementary/files#862
elementary/switchboard-plug-onlineaccounts#89
https://github.com/elementary/installer/issues/368

Unlike a Yubikey, it is Free Hardware and Free Software, which is mostly manufactured locally (in Berlin, Germany).

Here you can find more general information: https://www.nitrokey.com/ & https://github.com/nitrokey

This integration can also be used to decrypt your hard disks - see LUKS/LUKS2 - or as a solution for Two-factor authentication in Installer and Switchboard Online Accounts Plug. Integration with Files (to sign, encrypt and decrypt files) or Mail (to sign, encrypt and decrypt emails) it's also very useful.

**Comment by cassidyjames** [comment] 2019-01-20 17:34
AppCenter uses PolKit to authenticate. Consequently, this is a duplicate of https://github.com/elementary/pantheon-agent-polkit/issues/40

**Closed by cassidyjames** 2019-01-20 17:34 UTC

**Comment by 4jNsY6fCVqZv** [comment] 2019-02-04 16:38
Oh, I suspected that, but I wasn't sure.
Is AppCenter the only application that uses PolKit for authentication?

**Comment by cassidyjames** [comment] 2019-02-04 18:03
@4jNsY6fCVqZv any app that needs authentication uses PolKit. That's the entire point and purpose of PolKit. :stuck_out_tongue: It's an OS-wide service that provides authentication when requested.

**Comment by 4jNsY6fCVqZv** [comment] 2019-08-06 10:47
@cassidyjames What does it look like if I had to install OpenConnect VPN client via the AppCenter for my VPN access? When I connect to my VPN, I am asked for my authentication every time. Does this also work technically via PolKit?

**Comment by 4jNsY6fCVqZv** [comment] 2019-08-06 10:51
And can you basically already say something about the idea of whether you can and want to integrate other possibilities for other authentications - such as Nitrokeys - system-wide in the future? Especially Nitrokeys are suitable for more than just a login in Greeter.

**Comment by 4jNsY6fCVqZv** [comment] 2019-08-07 18:35
Maybe it makes sense to add/track these encryption-related issues here https://github.com/orgs/elementary/projects/9?
