### ISSUE TITLE
[Loki Bug] Appdata no longer being updated for new apps

### ISSUE THREAD

**Issue by arshubham** [elementary/appcenter#591] opened 2018-01-31 16:04 UTC
I experienced this with my daily repo enabled installation. So I **reinstalled elementary** to see if it was just daily bug, **but the bug is still there**.

The appdata in the top banner is no longer being updated. The first app being shown here is Cipher. I already pushed a new update **few days ago** with new icon and updated description, but appcenter is still showing the old description and icon. **Version number is correctly updating** 
Example for cipher : The version showed and installed is **0.1.5** but description and icon is shown from **0.1.3**
![image](https://user-images.githubusercontent.com/14235191/35632768-8ba53ea0-06cd-11e8-860a-c5c14692228e.png)
![image](https://user-images.githubusercontent.com/14235191/35632787-9570f262-06cd-11e8-94d3-4884d0d79971.png)

I also noticed that three new apps have been added to the appcenter by visiting https://developer.elementary.io/api/newest/project

But they are **not searchable** in appcenter. However they are available to be installed from apt 
![image](https://user-images.githubusercontent.com/14235191/35632935-10d0d792-06ce-11e8-8975-ea52b73d5db9.png)

**Output for io.elementary.appcenter -d**
[appcenter.txt](https://github.com/elementary/appcenter/files/1682355/appcenter.txt)

I have already tried manually updating appstream cache.

**Comment by btkostner** [comment] 2018-01-31 16:11
Trying running `sudo appstreamcli refresh-cache --force` and `sudo appstreamcli search <package-name>` and see if anything shows up.

**Comment by arshubham** [comment] 2018-01-31 16:15
For my app I am seeing this output : 
```
shubhamarora@HP-Notebook:~$ sudo appstreamcli search com.github.arshubham.cipher
Identifier: com.github.arshubham.cipher.desktop [desktop-application]
Name: Cipher
Summary: Encode and decode text
Package: com.github.arshubham.cipher
Homepage: https://github.com/arshubham/cipher
Icon: com.github.arshubham.cipher_com.github.arshubham.cipher.png
```
The app was already there so I think it is showing for the same.

But for say  **sudo appstreamcli search com.github.cjfloss.envelope**
```
Unable to find component matching com.github.cjfloss.envelope!
```

**Comment by memnoth** [comment] 2018-01-31 16:43
This is not a bug.
Your metadata is not up to date yet.
Try ``appstreamcli refresh-cache --force`` and ``sudo apt update``.

**Comment by btkostner** [comment] 2018-01-31 16:45
Give it like 15 minutes and do a `sudo apt update` and `sudo appstreamcli refresh-cache --force`

**Comment by arshubham** [comment] 2018-01-31 16:47
It works, but this was a fresh install and everyone can't be expected to run  ```appstreamcli refresh-cache --force``` to see all the apps.  The appcenter should force refresh every few days

**Comment by stsdc** [comment] 2018-02-01 20:35
I can also confirm, that AppCenter on my laptop is not updating more than week. After publishing new version of Monitor, only version has changed. 😢

**Comment by cassidyjames** [comment] 2018-03-01 17:42
So is an acceptable solution to this to have AppCenter force refresh the AppStream cache now and then? Is there a bug in some underlying component that's preventing it from updating normally?

**Comment by kaxing** [comment] 2018-11-22 08:14
Also encountered appstream not getting app-info on Juno.

After dig around, and found [an article](https://medium.com/@alex285/how-to-try-elementary-os-5-0-juno-on-ubuntu-18-04-4539eb346f6f) point out that I need to add the xenial repository for appcenter, `/etc/apt/sources.list.d/appCenter.list`:
```
deb http://packages.elementary.io/appcenter xenial main
# deb-src http://packages.elementary.io/appcenter xenial main
```

There might be the case that third-party repos, PPAs, got turn off due to system upgrade.

// Versions: 18.04 + Juno Daily PPA

**Comment by btkostner** [comment] 2018-11-22 15:35
@kaxing the repo should be the `bionic` version for Juno

**Comment by kaxing** [comment] 2018-11-27 02:03
@btkostner thanks for the hint!

@cassidyjames Sorry for the misinformation didn't realize appcenter repo already support bionic.
There must be something wrong when I upgrading from stock 18.04 to Juno, as the appcenter repo is missing in apt/source.list.d on my system.

**Comment by cassidyjames** [comment] 2018-11-27 16:20
@kaxing that's because "upgrading from Ubuntu to Juno" is not a thing that is technically possible and will lead to these sorts of issues. You're not running elementary OS, you're running Ubuntu with a some unstable elementary OS stuff on top.

Please install elementary OS from [elementary.io](https://elementary.io) for it to work correctly.

**Comment by jtrees** [comment] 2018-12-03 11:23
I have been experiencing this issue on Loki more or less (or exactly? I'm not sure) since Juno was released.

**Comment by cassidyjames** [comment] 2020-12-09 18:19
Since this is targeting Loki and Loki is no longer supported, I am closing. If we see the same issue in newer versions of elementary OS/AppCenter, we can re-open.

**Closed by cassidyjames** 2020-12-09 18:19 UTC
