### ISSUE TITLE
It is not clear how to install an app

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/appcenter#378] opened 2017-07-01 19:22 UTC
The button to install a free app (at least in spanish) says 'Gratis' (ie: 'Free'):

![captura realizada el 2017-07-01 16 20 01](https://user-images.githubusercontent.com/6054951/27764808-3f88811e-5e79-11e7-8680-e3ac7ebaa5cb.png)

At first I found myself thinking: "Is this a button I should press, or just information about the app?" Since there is no 'Install' button anywhere, one defaults to clicking it. Still, I believe this should be made more clear.

**Comment by danrabbit** [comment] 2017-07-01 19:27
Closing as a duplicate of #307

**Closed by danrabbit** 2017-07-01 19:27 UTC
