### ISSUE TITLE
Some application doesn't appear in the application menu after successful install .

### ISSUE THREAD

**Issue by karim-inabi** [elementary/appcenter#747] opened 2018-07-24 18:59 UTC
For some reason the application does not appear in the application menu but when search them in menu search box they appear really weird hope you fix it guys thank you .

**Comment by cassidyjames** [comment] 2018-08-25 23:57
I believe this is a packaging issue with the applications, or perhaps an issue with how the Applications Menu picks up new apps? Regardless, I don't believe it's an issue with AppCenter itself. Confirming with @elementary/desktop-developers before I close this out, though.

**Comment by dahenson** [comment] 2018-08-27 13:46
It might be good to know which applications are showing this behavior. I do believe this has something to do with how the application was packaged, but we would need specific examples in order to troubleshoot.

**Comment by davidmhewitt** [comment] 2018-11-20 11:18
I can confirm that there would be nothing that could be done about this in AppCenter. The issue is either with the applications menu or certain packages themselves.

**Closed by davidmhewitt** 2018-11-20 11:18 UTC
Labels: Status: Incomplete
