### ISSUE TITLE
Search by exact title doesn't work with "special" characters

### ISSUE THREAD

**Issue by inad9300** [elementary/appcenter#405] opened 2017-07-18 18:38 UTC
Examples of this are: "Notes-Up", "Spice-Up" or "P.S. Notes". It is very confusing to look for an app by its exact name and not be able to find it. If characters like this are allowed in app names (and they should), then the search should be ready to handle them.

**Comment by Philip-Scott** [comment] 2017-07-20 00:21
Duplicate of #222. This is actually an upstream bug in appstream. Fixed in this commit: ximion/appstream@82b7032 .

**Closed by Philip-Scott** 2017-07-20 00:21 UTC

**Comment by inad9300** [comment] 2017-07-21 06:01
Thanks for checking for duplicates better than me ;) Good to know things are taken care of.
