### ISSUE TITLE
Add visual gaps in creditcard input?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#290] opened 2017-05-19 10:28 UTC
For readability it would be great if gaps could be added between sets of 4 numbers in the creditcard input. See Stripe's demo for an example: https://stripe.com/docs/checkout

**Comment by danrabbit** [comment] 2017-05-19 14:15
Closing as a duplicate of #250

**Closed by danrabbit** 2017-05-19 14:15 UTC
