### ISSUE TITLE
Search is disabled from within app details page

### ISSUE THREAD

**Issue by alex285** [elementary/appcenter#743] opened 2018-07-18 07:16 UTC
Reproduce

### 1. Open AppCenter

![search1](https://user-images.githubusercontent.com/11244308/42865580-c960cdda-8a72-11e8-8c4e-7e1544145d1b.png)

The focus in on **Search Input** that is empty, and we can search for apps

### 2. Get inside an app

![search2](https://user-images.githubusercontent.com/11244308/42865570-c2aa179e-8a72-11e8-985c-ac24ed61804a.png)

When we get inside an app the search input says "Search Apps" but it is actually disabled. To search again we need to go back to the frontpage or search page if we performed a search before

I think we should be able to make a new search from inside an app details page, or at least search entry hasn't much point to be there if disabled

Perhaps a bit related to https://github.com/elementary/appcenter/issues/554

**Comment by cassidyjames** [comment] 2018-07-18 16:23
This is intentional, and a duplicate of #705. The problem, as stated in the other issue, is that the context of this search would be unclear and seemingly nondeterministic in this view, depending on how you arrived at the app listing. I'm open to reconsidering, but I don't think dropping back to a global app search would be appropriate when on all other views it searches the current view.

**Closed by cassidyjames** 2018-07-18 16:23 UTC
