### ISSUE TITLE
Visual glitches in banners and category cards

### ISSUE THREAD

**Issue by micahilbery** [elementary/appcenter#1014] opened 2019-06-12 03:32 UTC
Sometimes I get weird bars of darker color in some of the category cards or the top banners. In this screenshot you can see them in the communication, finance, and internet cards. Sometimes scrolling away from them fixes or changes them.

![Screenshot from 2019-06-11 22 10 49](https://user-images.githubusercontent.com/10608836/59321406-7dcc4480-8c97-11e9-9dd0-392ba5b824dd.png)

System:
---
OS: elementary 5.0 Juno (Appcenter v3.1.1) 
GFX Card: Nvidia GTX960 (proprietary nvidia driver from appcenter v390.116)
CPU: Intel i7-4770K
RAM: 16GB

**Comment by btkostner** [comment] 2019-06-12 03:46
Can confirm with same specs except a 970 with proprietary driver.

**Comment by danirabbit** [comment] 2023-01-27 18:04
Closing since this is super old and I can't reproduce on OS 7. Please reopen if it can be reproduced in the latest release

**Closed by danirabbit** 2023-01-27 18:04 UTC
Labels: Status: Confirmed
