### ISSUE TITLE
Search bar clickable only on Home tab (applies to Settings app too)

### ISSUE THREAD

**Issue by JohnDumpling** [elementary/appcenter#1623] opened 2021-08-23 10:04 UTC
## What Happened
When I want to search for an app, I can do that only on the Homepage:
![image](https://user-images.githubusercontent.com/89086803/130427989-d17c6c43-0f75-4e2b-8865-f4cb69ae598a.png)

However, when I switch to Installed or really, any other tab (i.e. I open an app description and installation window), the search bar is still present, but I can't select it:
![image](https://user-images.githubusercontent.com/89086803/130428311-27a914ef-2347-4b02-b544-128400c352f6.png)
![image](https://user-images.githubusercontent.com/89086803/130428328-f9178b4f-a238-4943-9e1f-2c5e31d3691e.png)

This issue applies to the System settings too, the only search bar that is clickable is available in the Main menu:
![image](https://user-images.githubusercontent.com/89086803/130428468-936d80c6-f0e9-4341-836d-d00e48b7d904.png)
But when I open any of the Control Panel Plugin windows, the search bar becomes unusable:
![image](https://user-images.githubusercontent.com/89086803/130428543-882f6001-1beb-4251-aab8-d862c53ef930.png)

## Expected Behavior
All of the search bars should be clickable, and thus usable.

## Steps to Reproduce
1. Open AppCenter and on the Homepage, click on the search bar (it should become selected and you should be able to type in it)
2. Now try the Installed tab and click on the search bar (nothing should happen)
3. Also try any search bar that you stumble upon in the AppCenter and System settings. As you can see, the behavior is very inconsistent

## Platform Information
Lenovo Legion 5 running elementary OS 6
AppCenter version: 3.6.3

(If you need PC specs and drivers, please ask, but I don't think they will be necessary)

**Comment by danirabbit** [comment] 2024-02-16 03:59
Closing as a duplicate of #493

**Closed by danirabbit** 2024-02-16 03:59 UTC
