### ISSUE TITLE
App icons in banner and info pages are slightly blurry

### ISSUE THREAD

**Issue by Appeltabak** [elementary/appcenter#279] opened 2017-05-17 17:05 UTC
Maybe it's nitpicking, but the icons shown in the banner on the homepage and at the info pages are a bit blurry:
![image](https://cloud.githubusercontent.com/assets/6260588/26165965/2b2a1b84-3b32-11e7-95c3-8ffdb9bddb17.png)

Some solutions I think of:

1. Don't scale the icons, making them smaller
2. Use SVG icons, making them able to scale nicely
3. Apps should use the right sized icon ;)

**Comment by danrabbit** [comment] 2017-05-17 21:32
This is actually a problem in appstream and can't be fixed in AppCenter. It is currently being worked on upstream.

**Closed by danrabbit** 2017-05-17 21:32 UTC

**Comment by Appeltabak** [comment] 2017-05-18 06:34
@danrabbit I think it's useful to leave the issue open, labelled with 'upstream' or 'blocked' or something, so others can see that this is known issue and can't be fixed right away. But after all it is bugging AppCenter, so therefore I think its nice to keep this open. Maybe linking to issue upstream if there's one?

**Comment by lewisgoddard** [comment] 2017-09-15 19:02
Also an upstream link would be great for tracking.

**Comment by inad9300** [comment] 2017-09-15 19:05
> This is actually a problem in appstream and can't be fixed in AppCenter. It is currently being worked on upstream.

@danrabbit, @lewisgoddard what do you mean by "upstream"/"appstream"? This is quite a new concept for me, I'm afraid.

Is there any progress on this front? 4 months for "slightly" blurry icons sounds like a lot to me, I think this is quite high priority.

**Comment by stsdc** [comment] 2017-09-15 19:07
@inad9300 https://github.com/ximion/appstream

**Comment by inad9300** [comment] 2017-09-15 19:21
Since @danrabbit wasn't clear and didn't reply nor I could find an issue on the AppStream side related to this one, I've opened https://github.com/ximion/appstream/issues/137.

@stsdc, is there some link that you can send me about "upstream" too? Is this somehow the same thing?

**Comment by stsdc** [comment] 2017-09-15 19:29
@inad9300 https://en.wikipedia.org/wiki/Upstream_(software_development)

**Comment by danrabbit** [comment] 2017-09-15 20:52
After some digging it looks like this is probably fixed in the latest version of AppStream. It looks like we need to now make sure that AppCenter Dashboard builds the packages to supply these icon sizes. I've opened an issue for that [here](https://github.com/elementary/houston/issues/541)

**Comment by inad9300** [comment] 2017-09-17 11:28
@Appeltabak and the other people experiencing this problem, are you using a HiDPI display?

In my case I'm using a quite normal display (1920x1080 in 15 inches), so my guess is that this problem is not related to the lack of HiDPI icons, but rather simply to their size.

**Comment by Appeltabak** [comment] 2017-09-27 20:24
@inad9300 Nope, I'm also using a 1920X1080 display. I would also guess that 64x64 sized icons are just stretched to 128x128 instead of properly scaled ones, but we'll see if the new AppStream release would fix it for us, as @danrabbit stated.

**Comment by danrabbit** [comment] 2017-09-27 20:51
I'm closing comments on this issue. It is not a bug in AppCenter. It is currently being tracked in Houston [here](https://github.com/elementary/houston/issues/541).
