### ISSUE TITLE
Failed to Fetch Updates: Failed to obtain authentication

### ISSUE THREAD

**Issue by Aberrantfox** [elementary/appcenter#1168] opened 2020-01-01 23:41 UTC
Experiencing this very frustrating issue.

**What happens**
1. Open app center 
2. Wait < 3 seconds
3. Error popup: 
**Failed to fetch updates**
This may have been caused by external, manually added software repositories or a corrupted sources file.
*Failed to obtain authentication*

**What should happen**
1. Open app center
2. Update occurs as normal

**What I have tried so far**
- Removing the deb cdrom from my source.list (zero change)
- Getting new ppa keys, updating/upgrading manually via the terminal. 

It would be nice if there was at least further information given here so I could maybe debug this myself but I am at a loss. 

Cheers.

**Comment by Aberrantfox** [comment] 2020-01-01 23:43
It appears that restarting my machine after the myriad of steps I did somehow fixed this. Would it be possible to improve the error message. Because it is fixed now and I have absolutely no idea why it is fixed...

**Comment by vikasnataraja** [comment] 2020-01-03 23:15
Same as Issue #1164

**Comment by cassidyjames** [comment] 2020-01-10 18:18
As an update to anyone following this issue: we're investigating this. It seems that cerbere (our daemon to start and restart shell components) is not closing cleanly, which causes issues in the session once you log out and back in.

**Comment by cassidyjames** [comment] 2020-02-18 18:41
@Aberrantfox can you confirm that it works correctly on the first login after booting, but fails after logging out and back in?

**Comment by inad9300** [comment] 2020-02-20 20:57
Having the exact same issue here. I can confirm that it also happens right after booting.

**Comment by inad9300** [comment] 2020-02-20 21:04
Trying to check the "logging out and back in" case... The "Log Out" button does nothing but close the popup. I keep reopening and retrying and it keeps being ignored.

**Comment by inad9300** [comment] 2020-02-20 21:08
Interestingly, opening the popup through Ctrl+Alt+Delete made the action work on the first try :/ And even more interestingly, after logging back in, AppStore no longer shows me the error message! Which seems to be the exact opposite to what @cassidyjames was expecting.

**Comment by danrabbit** [comment] 2020-03-16 23:27
@inad9300 after running all updates are you still able to reproduce this issue?

**Comment by inad9300** [comment] 2020-03-22 09:48
I haven't encountered this problem ever since :)

**Closed** 2020-04-06 13:51 UTC
Labels: Status: Incomplete
