### ISSUE TITLE
Appcenter stays apparently doing nothing

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/appcenter#2096] opened 2023-10-26 20:15 UTC
### What Happened?

Appcenter says there are updates available so I opened it. App looks like this when in fact there are updates available (I checked in terminal)

![Captura de pantalla de 2023-10-26 17 13 53](https://github.com/elementary/appcenter/assets/6054951/f25a6315-fc55-4b32-bc94-a8fc557d7612)

### Steps to Reproduce

Open Appcenter when an update is informed as available

### Expected Behavior

Updates should be shown

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by garzajual** [comment] 2023-11-06 11:55
Me too.

**Comment by AdrianoSiqueira** [comment] 2023-11-19 16:43
Same here, but I am running it in VirtualBox 7.0.12.

**Comment by xvelasqu** [comment] 2023-11-26 12:41
Same problem. I can successfully upgrade packages from Synaptic and Flatpak CLI but AppCenter is stuck at this screen.

**Comment by xvelasqu** [comment] 2023-11-26 12:53
I solved this by running:
`flatpak repair --system`
`flatpak repair --user`

**Comment by sauntor** [comment] 2023-12-07 15:16
> I solved this by running: `flatpak repair --system` `flatpak repair --user`

It can't work for me

**Comment by sauntor** [comment] 2023-12-07 15:25
But if you launch `AppCenter` from terminal, it may works sometimes.
```shell
io.elementary.appcenter --g-fatal-warnings -u
```

**Comment by donnie-j** [comment] 2024-01-21 03:04
This appears to be a long running problem, I think perhaps related to threading model.  If the processes it's running do something unexpected it just hangs, and the WM eventually asks if you want to kill it.

Fixing flatpak (IMHO, flatpak is yet another bad idea) might mitigate for a while, but the problem returns.  This needs to be fixed as a high priority, I've had to revert to apt-get for just about everything.

**Comment by JohnDumpling** [comment] 2024-02-06 10:25
`flatpak-update` currently shows no available updates, but AppCenter never shows any available updates anymore. Confirmed on 3 devices of various age including a virtual machine on my main laptop. I switched one device to Zorin OS (as it has to be reliable, it is for a relative), one I kept on eOS (for testing purposes). I'm patient, hopefully the proposed separation of flatpak & system updates will fix this high priority issue.

**Comment by zeebok** [comment] 2024-02-22 15:28
I can confirm this and *think* I know the cause of it. It seems like if you go to the updates page while the little "Checking for Updates" tool tip at the bottom is still going, it should reveal it properly otherwise you will see what you describe. I am going to try a fix this weekend.

**Comment by Gabriel-p** [comment] 2024-04-29 20:06
What @zeebok says appears to be right. I you wait until the update checking is finished, it won't whos the available updates. You have to click the orange arrow icon to the top right *while* the checking is happening

**Comment by zeebok** [comment] 2024-05-19 07:12
I do also notice that this isn't a present issue in OS8 with the newer iterations of AppCenter, and the portion of code I thought was the cause is not really changed between the versions. I will have to dive a little deeper to figure out what is happening.

**Comment by diogopessoa** [comment] 2024-07-19 07:21
I also face this same problem in the stable 7.1 version of elementary. But in the development version 8, I haven't had this problem so far. I'll keep testing to see if this behavior happens again or not.

**Comment by zeebok** [comment] 2024-08-16 03:53
I found a fix for this in OS 7 and if it gets merged will mean it will be patched for everyone

**Comment by ryonakano** [comment] 2024-08-18 10:55
Closing as fixed in #2205—it looks like the `Fixes` keyword in the PR didn't work here, maybe because the target branch is not main. Thank you @zeebok for the fix!

**Closed by ryonakano** 2024-08-18 10:55 UTC
