### ISSUE TITLE
The size of "Operating System Updates" is always 0 bytes

### ISSUE THREAD

**Issue by ryonakano** [elementary/appcenter#852] opened 2018-10-11 12:39 UTC
![peek 2018-10-11 21-32](https://user-images.githubusercontent.com/26003928/46804359-600fae00-cd9d-11e8-8714-caa0e79de7ec.gif)

## Expected behavior

The size of "Operating System Updates" should not be 0 bytes, because the updates are available.

## Steps to reproduce the behavior

* Open Update tab when operating system updates are available
* Click "Operating System Updates". You should confirm that its size is 0 bytes, although the updates are available.

With AppCenter 0.2.9, on Juno Beta2

**Comment by peteruithoven** [comment] 2018-10-11 12:41
Duplicate of https://github.com/elementary/appcenter/issues/667 ?

**Closed by peteruithoven** 2018-10-11 12:41 UTC

**Comment by ryonakano** [comment] 2018-10-11 12:43
You're right, I should have checked existing issue more…
