### ISSUE TITLE
AppCenter all time have one update.

### ISSUE THREAD

**Issue by grytsalex** [elementary/appcenter#1245] opened 2020-04-03 09:26 UTC
![Снимок экрана от 2020-04-03 12-22-07](https://user-images.githubusercontent.com/32422951/78345598-82574600-75a6-11ea-8e18-a7e3f13d03b3.png)
![Снимок экрана от 2020-04-03 12-23-54](https://user-images.githubusercontent.com/32422951/78345606-86836380-75a6-11ea-9d22-9652024ea09e.png)

In my AppCenter, it constantly reports that there is one update, but when there is nothing to update it.

**Comment by davidmhewitt** [comment] 2020-04-06 13:52
Thanks for the report, however, this seems to be a duplicate of #1193 , I'll close this issue.

**Closed by davidmhewitt** 2020-04-06 13:52 UTC
Labels: Status: Duplicate
