### ISSUE TITLE
App Center opens every time I login

### ISSUE THREAD

**Issue by o-alquimista** [elementary/appcenter#1123] opened 2019-11-03 22:32 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The App Center pops up automatically on every login. First, it fetches updates (I can't run apt update until that finishes). When it does, the app opens up. I believe this is not the intended behavior.

### To Reproduce
1. Login and wait about a minute or so

### Expected behavior

It shouldn't pop up on every login. It's annoying and unavoidable.

### Logs

[journalctl.txt](https://github.com/elementary/appcenter/files/3802225/journalctl.txt)

## Platform Information

![Captura de tela de 2019-11-03 19 30 44](https://user-images.githubusercontent.com/25424263/68093065-72f59480-fe70-11e9-8941-af6aea264e2b.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context

- In System Config > Applications > Startup, there are no entries.

**Comment by ryonakano** [comment] 2019-11-04 00:22
Thank you for your report, but I'll close this issue as a duplicate of #1063.

**Closed by ryonakano** 2019-11-04 00:22 UTC
