### ISSUE TITLE
Header ellipsizes unnecessarily

### ISSUE THREAD

**Issue by jeremypw** [elementary/appcenter#1407] opened 2020-09-15 15:50 UTC
I have searched open and closed issues for duplicates.

## Describe the bug
See screenshot below.  Even though there is plenty of room for the full header, it is ellipsized.

![Screenshot from 2020-09-15 15 41 08](https://user-images.githubusercontent.com/10513844/93233606-cb711000-f76a-11ea-9804-4c9d41ca2edc.png)

### Expected behavior
The header uses the available space

## Platform Information
Odin in VirtualBox

**Comment by cassidyjames** [comment] 2020-09-15 16:08
Duplicate of #1299. I agree there might be a better way to handle this, but Just making the header take up the whole width means buttons will move around unpredictably or it'll look really weird with different lengths of app names.

**Closed by cassidyjames** 2020-09-15 16:08 UTC

**Comment by jeremypw** [comment] 2020-09-15 16:38
Sorry missed duplicate - searched for "ellipsize" and "truncate" !
