### ISSUE TITLE
AppCenter Bug/Crash

### ISSUE THREAD

**Issue by MackMan6160** [elementary/appcenter#594] opened 2018-02-03 20:28 UTC
So, after the recent appstream and appcenter updates my appcenter won't load or crashes. Definitely a bug in the recent update of some sort. I've tried purging the appstream and re-installing appcenter which forces appstream to update to the most current version. I'm on Loki 0.4.3 xenial.

Any answers on:

    If the bug is being worked on?

    My workaround for the time being is using another GUI app like Synaptic to update everything.

    Sudo commands via terminal under a root tab also still work: eg..(sudo apt update) etc..

```

mack@mack-HP-Pavilion-TS-Sleekbook-15:~$ AppCenter
AppCenter: command not found
mack@mack-HP-Pavilion-TS-Sleekbook-15:~$ 
```

**Comment by btkostner** [comment] 2018-02-03 20:31
The command is `appcenter` or `io.elementary.appcenter`. Please try running these and posting the console output.

**Comment by MackMan6160** [comment] 2018-02-03 20:34
mack@mack-HP-Pavilion-TS-Sleekbook-15:~$ io.elementary.appcenter

** (process:8716): WARNING **: ComponentValidator.vala:38: Could not get the contents of blacklist file: Failed to open file '/etc/io.elementary.appcenter/appcenter.blacklist': No such file or directory
[INFO 15:33:37.882529] Application.vala:154: AppCenter version: 0.2.8
[INFO 15:33:37.882601] Application.vala:156: Kernel version: 4.13.0-32-generic
[ERROR 15:33:38.047160] [GLib-GIO] Settings schema 'io.elementary.appcenter.settings' does not contain a key named 'reset-paid-apps'
Trace/breakpoint trap (core dumped)
mack@mack-HP-Pavilion-TS-Sleekbook-15:~$

**Comment by MackMan6160** [comment] 2018-02-04 02:40
Pulled this error as well:

`[ERROR 21:33:33.163606] [GLib-GIO] Settings schema 'io.elementary.appcenter.settings' does not contain a key named 'reset-paid-apps'`

**Comment by tintou** [comment] 2018-02-04 10:00
@MackMan6160 It means that the GSettings schema is not correctly installed on your system. Have you installed appcenter by hand once ? If so, you might want to remove anything related to appcenter in `/usr/local/share/glib-2.0/schemas/`

**Comment by MackMan6160** [comment] 2018-02-04 17:28
`root@mack-HP-Pavilion-TS-Sleekbook-15:/usr/share/glib-2.0# rm -R schemas
`
`** (process:22507): WARNING **: ComponentValidator.vala:38: Could not get the contents of blacklist file: Failed to open file '/etc/io.elementary.appcenter/appcenter.blacklist': No such file or directory
[INFO 12:24:04.278959] Application.vala:154: AppCenter version: 0.2.8
[INFO 12:24:04.279035] Application.vala:156: Kernel version: 4.13.0-32-generic
[ERROR 12:24:04.402003] [GLib-GIO] No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)`

`root@mack-HP-Pavilion-TS-Sleekbook-15:~# apt-get install glib-2.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libspice-client-glib-2.0-dev' for regex 'glib-2.0'
Note, selecting 'libqt5glib-2.0-0' for regex 'glib-2.0'
Note, selecting 'gir1.2-spice-client-glib-2.0' for regex 'glib-2.0'
Note, selecting 'gir1.2-glib-2.0' for regex 'glib-2.0'
Note, selecting 'libspice-client-glib-2.0-1' for regex 'glib-2.0'
Note, selecting 'libspice-client-glib-2.0-8' for regex 'glib-2.0'
Note, selecting 'libqtglib-2.0-0' for regex 'glib-2.0'
gir1.2-glib-2.0 is already the newest version (1.46.0-3ubuntu1).
gir1.2-glib-2.0 set to manually installed.
gir1.2-spice-client-glib-2.0 is already the newest version (0.30-1).
libspice-client-glib-2.0-8 is already the newest version (0.30-1).
libspice-client-glib-2.0-8 set to manually installed.
The following additional packages will be installed:
  libspice-protocol-dev
The following NEW packages will be installed:
  libqt5glib-2.0-0 libqtglib-2.0-0 libspice-client-glib-2.0-dev libspice-protocol-dev
0 upgraded, 4 newly installed, 0 to remove and 1 not upgraded.
Need to get 176 kB of archives.
After this operation, 991 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 libqt5glib-2.0-0 amd64 1.2.0-3 [47.2 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 libqtglib-2.0-0 amd64 1.2.0-3 [47.2 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libspice-protocol-dev all 0.12.10-1 [47.2 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 libspice-client-glib-2.0-dev amd64 0.30-1 [34.2 kB]
Fetched 176 kB in 2s (83.8 kB/s)                        
Selecting previously unselected package libqt5glib-2.0-0:amd64.
(Reading database ... 252903 files and directories currently installed.)
Preparing to unpack .../libqt5glib-2.0-0_1.2.0-3_amd64.deb ...
Unpacking libqt5glib-2.0-0:amd64 (1.2.0-3) ...
Selecting previously unselected package libqtglib-2.0-0:amd64.
Preparing to unpack .../libqtglib-2.0-0_1.2.0-3_amd64.deb ...
Unpacking libqtglib-2.0-0:amd64 (1.2.0-3) ...
Selecting previously unselected package libspice-protocol-dev.
Preparing to unpack .../libspice-protocol-dev_0.12.10-1_all.deb ...
Unpacking libspice-protocol-dev (0.12.10-1) ...
Selecting previously unselected package libspice-client-glib-2.0-dev.
Preparing to unpack .../libspice-client-glib-2.0-dev_0.30-1_amd64.deb ...
Unpacking libspice-client-glib-2.0-dev (0.30-1) ...
Setting up libqt5glib-2.0-0:amd64 (1.2.0-3) ...
Setting up libqtglib-2.0-0:amd64 (1.2.0-3) ...
Setting up libspice-protocol-dev (0.12.10-1) ...
Setting up libspice-client-glib-2.0-dev (0.30-1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
`
`** (process:22706): WARNING **: ComponentValidator.vala:38: Could not get the contents of blacklist file: Failed to open file '/etc/io.elementary.appcenter/appcenter.blacklist': No such file or directory
[INFO 12:26:53.068361] Application.vala:154: AppCenter version: 0.2.8
[INFO 12:26:53.068431] Application.vala:156: Kernel version: 4.13.0-32-generic
[ERROR 12:26:53.208633] [GLib-GIO] No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
`
GRRRRRRRRRR!!!!!!!!!!!!!

**Comment by memnoth** [comment] 2018-02-05 03:03
You need to debug what's going on appcenter while it's running. 
Put logs from gdb here.
Try process as below to get logs.
```
$ ps aux | grep appcenter
hja       4939  0.5  1.3 1029888 106712 ?      Sl   11:38   0:06 io.elementary.appcenter -s

$ sudo kill -9 4939
$ gdb `which io.elementary.appcenter`
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/io.elementary.appcenter...(no debugging symbols found)...done.
(gdb) run
```

**Comment by davidmhewitt** [comment] 2019-05-22 14:39
I'm going to close this issue as we've had no further reports of it being reproduced by anyone else and things have moved on a lot since then. Please re-open if this issue still persists.

**Closed by davidmhewitt** 2019-05-22 14:39 UTC
Labels: Status: Incomplete
