### ISSUE TITLE
Card expiration date format

### ISSUE THREAD

**Issue by PavelVybiral** [elementary/appcenter#297] opened 2017-05-20 07:23 UTC
Hello.
I think there is a small problem when I want to pay for some app. In a window, where I should insert details of my card, there is an field for expiration date and it's labeled by "MM/YY". That's nice, but when I try to write 05/20 (for example), it doesn't allow me to do it. It accepts only 0520.

I know this isn't big issue and most people will understand what should they do, but I think that when there is written to fill the field by YY/MM format, this format should be accepted.

**Comment by tintou** [comment] 2017-05-20 08:30
Closing as a duplicate of #250

**Closed by tintou** 2017-05-20 08:30 UTC
