### ISSUE TITLE
Add support to install localization packages

### ISSUE THREAD

**Issue by febrezo** [elementary/appcenter#895] opened 2018-11-06 09:01 UTC
Several Debian packages like Libreoffice have additional localization packages which are relevant to update the interface and the GUI. At the moment, I can't find an alternative way to install the locales different from using apt in the terminal.

**Comment by davidmhewitt** [comment] 2020-04-06 14:14
I'm just cleaning up the issue tracker and I notice this is a duplicate of #254 , I'll close this issue so that there's just one to track. Thanks for the report.

**Closed by davidmhewitt** 2020-04-06 14:14 UTC
Labels: Status: Duplicate
