### ISSUE TITLE
Search bar gets disabled on "App pages" and "Updates tab"

### ISSUE THREAD

**Issue by uncertainquark** [elementary/appcenter#705] opened 2018-05-03 06:54 UTC
The search bar gets disabled on the following pages:

1. App pages
![screenshot from 2018-05-03 12-04-10](https://user-images.githubusercontent.com/22585732/39563165-a6aeec7c-4ecc-11e8-9242-a2be8e1535cc.png)

2. Updates tab
![screenshot from 2018-05-03 12-04-17](https://user-images.githubusercontent.com/22585732/39563178-b1bb525e-4ecc-11e8-929b-d5dfbc111363.png)

**Comment by cassidyjames** [comment] 2018-05-03 16:10
This is intentional. Since search searches the current context, searching on the app listing would be confusing and inconsistent. Sometimes it would search the category you're browsing, sometimes it would search all apps, etc.

2 is a duplicate of #493.

**Closed** 2018-05-03 16:10 UTC
Labels: Status: Design Conflict, Status: Duplicate
