### ISSUE TITLE
High memory consumption (Juno 5)

### ISSUE THREAD

**Issue by KeironO** [elementary/appcenter#807] opened 2018-09-17 15:53 UTC
Since updating this morning, I'm experiencing high memory consumption using appcenter.

![alt text](https://i.imgur.com/ffhCf0R.jpg)

**Comment by davidmhewitt** [comment] 2018-11-13 15:04
This seems to be a duplicate of #494 

I'll close this issue so we can track it in just one place.

**Closed by davidmhewitt** 2018-11-13 15:04 UTC
