### ISSUE TITLE
AppCenter shows system updates even when there are none

### ISSUE THREAD

**Issue by janxkoci** [elementary/appcenter#1119] opened 2019-11-02 12:39 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
After the latest update to AppCenter, it started to show available updates in parts of the UI even when there are no updates to install.

Screenshot will make it more clear:

![Snímek z 2019-11-02 13-27-15](https://user-images.githubusercontent.com/19331850/68070948-3f820f80-fd75-11e9-81e0-365fd5c653ff.png)

Note that there is a Section for apps with update available, button to update etc. - but the list actually says there ane no packages with update available and clicking the button does almost nothing (it checks something and then goes back to the same state).

### To Reproduce
1. Open AppCenter
2. Switch tab to Installed
3. See the problem

### Expected behavior
No updates shoud be listed if there are none available. No button to update should be shown either.

## Platform Information

![Snímek z 2019-10-06 12-03-56](https://user-images.githubusercontent.com/19331850/68071012-fda59900-fd75-11e9-967c-a0dbcc9abf83.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
This only started to happen after the latest update (the screenshot above shows v3.2.0).

**Comment by janxkoci** [comment] 2019-11-02 12:46
Now I noticed it's possibly a duplicate of #1064 - I didn't see it before because I only looked at bugs from October, when the new version was introduced. The bug linked has the package from PPA, which I didn't expect.

Also wanted to add that I can see the latest version with it's new features, so #1113 doesn't apply here.

**Comment by vjr** [comment] 2019-11-02 12:49
Are you sure there are no updates for your system? I noticed you have kernel `4.15.0-65` while I believe the current kernel is `xxx-66`

**Comment by janxkoci** [comment] 2019-11-02 13:21
Ah sorry, the screenshot of system settings is few days old, I have 4.15.0-66 now. The AppCenter screenshot is from today though..

**Comment by Angedestenebres** [comment] 2019-11-05 18:44
I have this issue too. I got it for the last 3 updates :

![Capture d’écran de 2019-11-05 19-40-31](https://user-images.githubusercontent.com/21110485/68235881-5ab67e80-0004-11ea-9827-f7fabf3587d3.png)

Each time I used the button to apply all updates.

**Comment by terrakok** [comment] 2019-11-06 09:07
I have this issue too

**Comment by davidmhewitt** [comment] 2019-11-08 00:56
A fix for this issue has been merged in #1129. When the new version of AppCenter comes out (3.2.1), we should see this issue resolved.

I'll close this issue but if you are still experiencing this issue *after* the new version of AppCenter comes out, please leave another comment.

This also appears to be a duplicate of #1001 and #1064 so I'll close those issues too.

**Closed by davidmhewitt** 2019-11-08 00:56 UTC
