### ISSUE TITLE
Indicate what's new with each new update to an app

### ISSUE THREAD

**Issue by yeboahnanaosei** [elementary/appcenter#410] opened 2017-07-25 00:29 UTC
I think it will be a cool feature to display what's new in a new update to an app. 
Using Spice-Up as example, you can have something like

#### *Latest Update: 0.1.9*
What's new:
* Ability to add videos
* Added slide transitions
* Text can now be animated
* You can crop images

**Comment by danrabbit** [comment] 2017-07-25 00:32
Closing as a duplicate of #24

**Closed by danrabbit** 2017-07-25 00:32 UTC
