### ISSUE TITLE
Give feedback about apps

### ISSUE THREAD

**Issue by 20alice2emanueli** [elementary/appcenter#1221] opened 2020-02-23 19:48 UTC
I would like to be able to give suggestions and opinions about the apps, and I would like the app creators to see and give feedback to users.I am very happy that elementary OS has many native apps that I have used almost all of them, and all are wonderful, you and the developers involved are doing a great job ... when I have money I would love to help finance. keep up the great work. tell all the developers that you are on the right track. We love Elementary OS. And we love Apps too!

**Comment by NathanBnm** [comment] 2020-02-24 12:35
@20alice2emanueli you can do so on the respective GitHub repos no?

**Comment by 20alice2emanueli** [comment] 2020-02-24 20:09
Yes, I'm sorry, I'm a layman and I can't do it easily ... For simple users who want to give an opinion or suggestion it is a little difficult to create a github account. thank you for replying. have an excellent day!

**Comment by danrabbit** [comment] 2020-04-19 21:38
GitHub really is the best way to report issues or request features, but for other kinds of contact the only other realistic channel we have is email. So, I think that would make this a duplicate of https://github.com/elementary/appcenter/issues/725

**Closed by danrabbit** 2020-04-19 21:38 UTC
Labels: Priority: Wishlist
