### ISSUE TITLE
AppCenter Network Issue

### ISSUE THREAD

**Issue by keyxmakerx** [elementary/appcenter#422] opened 2017-08-01 10:18 UTC
AppCenter showing error "Network is not Available". Device is confirmed connected to the internet. No Debug information is shown. All unused ethernet ports are disabled.

**Comment by davidmhewitt** [comment] 2017-08-04 09:21
Thank you for the report.

This is a duplicate of #342 so I will close this and the issue can be tracked there.

**Closed by davidmhewitt** 2017-08-04 09:21 UTC
