### ISSUE TITLE
My AppCenter don't want run 

### ISSUE THREAD

**Issue by oussamaexe** [elementary/appcenter#1557] opened 2021-07-22 08:48 UTC
i have problem with AppCenter sometimes he frezze or don't want run he make me log out and login a lot of times so can u help me with that

**Comment by danirabbit** [comment] 2023-01-28 00:16
Closing since this is old and there's no steps to reproduce or logs. Please reopen if you can still reproduce the issue with steps to reproduce

**Closed by danirabbit** 2023-01-28 00:16 UTC
