### ISSUE TITLE
Show installation progress of newly downloaded apps in "Updates" tab.

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/appcenter#624] opened 2018-02-27 19:33 UTC
In the current system, when a new app is downloaded, its progress is visible only in the app's page. This makes it harder to manage multiple new app downloads. So it could be better if the downloads of all new apps (apps that are not installed) are shown in one single place for users to manage or keep track of. A trivial solution would be to show all the newly installing apps in the "Updates" tab.

**Comment by cassidyjames** [comment] 2018-03-03 03:51
Thanks for the issue! It appears this is a duplicate of #14.

**Closed by cassidyjames** 2018-03-03 03:51 UTC
Labels: Status: Duplicate
