### ISSUE TITLE
Firefox missing from AppCenter on Juno

### ISSUE THREAD

**Issue by uncertainquark** [elementary/appcenter#735] opened 2018-07-08 14:48 UTC
Not sure why but Firefox is missing from AppCenter on Juno Beta-1. Considering that is is a rather important app that many users install and as a priority post-install, I thought it might be important to mention.

![screenshot from 2018-07-08 20-16-19](https://user-images.githubusercontent.com/22585732/42421017-1b223822-82ec-11e8-8f1e-38eb099ddf0e.png)

**Comment by codygarver** [comment] 2018-07-10 06:58
Duplicate of elementary/appstream-data#8

**Closed by codygarver** 2018-07-10 06:58 UTC
