### ISSUE TITLE
Multiple Payment Options for the Appcenter 

### ISSUE THREAD

**Issue by lennarthlion** [elementary/appcenter#986] opened 2019-04-12 09:17 UTC
I am German and don't want to have a credit card, as it is not needed or common in our culture. 

My preferred way of paying is paypal. But i do understand people who don't want to use it. 

As soon as more apps than just "Agenda" will have minimum prices on the appcenter you can do whatever you like, but you will always exclude some people with just one payment method. 

The only solution i see is multiple payment methods. At least two. You won't get everybody in the boat with just one. 

That stripe for some reason seems to demand to be exclusive is very unfortunate. 

If you want to keep your german user base while having the need for credit cards, you would need at least to keep the zero a general do-not-pay option. I would prefer very much to be able to pay in the appcenter in the near future.

**Comment by peteruithoven** [comment] 2019-04-12 09:25
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/appcenter/issues/291, which was split up in issues like: 
- https://github.com/elementary/appcenter/issues/280
- https://github.com/elementary/appcenter/issues/314
- https://github.com/elementary/appcenter/issues/315
- https://github.com/elementary/appcenter/issues/316
- https://github.com/elementary/appcenter/issues/956

**Closed by peteruithoven** 2019-04-12 09:25 UTC
