### ISSUE TITLE
Feature: show tooltip on loading spinner on right top corner

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/appcenter#1476] opened 2021-01-13 20:49 UTC
When Appcenter loads something in background (probably fetching package lists etc.), a spinner is shown.

As and advanced user, I'd like to know what AppCenter is working on.

The current task should briefly be described in a tooltip when I move my cursor over the spinner.

**Comment by cassidyjames** [comment] 2021-01-13 21:09
Duplicate of #394

**Closed by cassidyjames** 2021-01-13 21:09 UTC
