### ISSUE TITLE
Mis-styled label in app description heading

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/appcenter#1431] opened 2020-10-12 19:50 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Go to the Installed tab on AppCentre.
2. Open an update with descriptive text.
3. Headings appear green.

Note: Heading colour fixes itself when window is out of focus and re-focused (tab out and tab back in).

### Expected behavior

App description headings shouldn't be green.

### Screenshots or screen recordings

![Screenshot from 2020-10-13 03-35-56](https://user-images.githubusercontent.com/31680656/95784604-b904da80-0d06-11eb-870b-4209ce3e4d3a.png)

## Platform Information

![Screenshot from 2020-10-13 03 47 39](https://user-images.githubusercontent.com/31680656/95784681-db96f380-0d06-11eb-9bd8-81974c732fee.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by cassidyjames** [comment] 2020-10-12 20:23
Thanks for filing this! It is actually a duplicate of https://github.com/elementary/stylesheet/issues/827

**Closed** 2020-10-12 20:23 UTC
Labels: Status: Duplicate
