### ISSUE TITLE
Drivers in the update tab is confusing

### ISSUE THREAD

**Issue by nloomans** [elementary/appcenter#374] opened 2017-06-30 15:06 UTC
First of, the AppCenter is just amazing, you guys really did a good job on that.

However, I find the fact that the uninstalled drivers are in updates tab confusing, because I only expect already installed apps in it. I therefor assumed that these where already installed. I have also heard people say online that elementary doesn't have a driver manager at all because of this. 

I think it would be a lot better if we had a small application just to handle the drivers. That way it would easily searchable when someone types drivers in the applications menu. Something like the one that Ubuntu uses, but then obliviously a good looking one ;-).

![The driver manager of Ubuntu](https://user-images.githubusercontent.com/7829481/27741681-3850db80-5db6-11e7-8c81-49d7e2196c56.png)

**Comment by danrabbit** [comment] 2017-06-30 16:42
Closing as a duplicate of #247

**Closed by danrabbit** 2017-06-30 16:42 UTC
