### ISSUE TITLE
Higher RAM usage with time

### ISSUE THREAD

**Issue by lawki** [elementary/appcenter#1389] opened 2020-08-07 11:30 UTC
## Prerequisites
- [ x ] I have searched open and closed issues for duplicates.

## Describe the bug
The AppCenter Daemon is using higher than normal memory as the time passed reaching 400MB at the end of the day, the only solution seems to be killing the app and starting it

### To Reproduce
1. After starting AppCenter notice the RAM usage,
2. Notice the RAM usage after 2-3 hours, do the same after 5-6 hours.

### Expected behavior
RAM usage hovers at value noticed on startup of AppCenter/System.

### Actual behavior
RAM usage keeps rising, starting at 90-100MB on startup then reaching at 400-500MB after 5-6 hours.

### Screenshots or screen recordings
![initial RAM usage](https://i.imgur.com/q24wNJZ.png "initial RAM usage")
![RAM usage after 5 hours](https://i.imgur.com/X1a2m3a.png "RAM usage after 5 hours")

## Platform Information

 - elementary OS
 - 5.1.6 Hera
 - Quad-Core AMD A8-7410 APU with AMD Radeon R5 Graphics

- [ ] I'm using the latest version from git that I've manually compiled
- [ x ] I'm using the latest released stable version

**Comment by fitojb** [comment] 2020-08-13 06:39
cf. issue #1170

**Comment by Scotty-Trees** [comment] 2020-10-06 23:18
Just wanted to comment real quick, I have this issue as well on Pop!_OS 20.04, the App Center (aka Pop! Shop) will go upwards to use over 1GB of RAM. And even if I close the app, io.elementary.appcenter will still use that 1GB of RAM. Bit of a naughty bug going on there I suspect. Below is a screenshot of my System Monitor, showing the store is using over 1GB of RAM, and it's not even running. The ram usage starts off small, but exponentially increases over time when I use the store to install apps or use it to update my system. Hope this issue can be resolved someday!

![Screenshot from 2020-10-06 15-37-52](https://user-images.githubusercontent.com/45135187/95269995-38bf1080-0800-11eb-92a7-fcea99bf828d.png)

**Comment by lawki** [comment] 2020-10-10 20:08
@Scotty-Trees well I did clean install of eOS about a month ago and since then it hasn't come back. 

And the high RAM usage comes up because even though `Pop! Shop` is not running, it's daemon is checking for updates. Meaning one doesn't even have to open the `Pop! Shop` to notice the heavy RAM usage, it does it in the background because of the updates check on startup.

One ugly solution that I tried was just kill it after noticing the increase, by -
1. Finding the PID `ps -e | grep -i appcenter`,
2. And `kill <pid>`

**Comment by cassidyjames** [comment] 2020-10-12 20:53
@Scotty-Trees for what it's worth, Pop!_OS ships a fork of AppCenter with their own changes, and frequently lags behind the latest upstream releases. So issues there may not be the same as issues here.

This issue as originally reported appears to be a duplicate of #1170

**Closed by cassidyjames** 2020-10-12 20:53 UTC

**Comment by Scotty-Trees** [comment] 2020-10-12 21:03
@cassidyjames Ah good to know, I was unaware that it was a fork! Thanks for replying and I'll see if I can bring it up to the Pop! devs attention, cheers.
