### ISSUE TITLE
AppCenter crashes with segmentation fault

### ISSUE THREAD

**Issue by peter-veres** [elementary/appcenter#1999] opened 2023-02-08 17:08 UTC
On latest Elementary OS 7, AppCenter crashes when opening the Office, Education, System categories with `Segmentation fault` (error returned when AppCenter is launched from terminal `/usr/bin/io.elementary.appcenter`).

When launched using gdb and when I click one of the affected categories, I see following output in gdb:
```
Thread 1 "io.elementary.a" received signal SIGSEGV, Segmentation fault.
0x00007ffff70239fb in as_release_get_timestamp () from /lib/x86_64-linux-gnu/libappstream.so.4
(gdb) 

```

**Comment by tintou** [comment] 2023-02-08 17:18
This is a duplicate of #1989 which will be fixed in an upcoming update

**Closed by tintou** 2023-02-08 17:18 UTC
