### ISSUE TITLE
Want to install Available Updates in Elementary Appcenter however

### ISSUE THREAD

**Issue by Th3Bull3t** [elementary/appcenter#1405] opened 2020-09-11 12:52 UTC
Getting the error      ¨waiting for package manager lock¨   by every start of an update or install of new software.

Hope somebody can help me here with some commands :+1: 

Kind Regards

![image](https://user-images.githubusercontent.com/71134056/92927748-66ea4400-f43e-11ea-8ab5-30d3b436be2c.png)

**Comment by danrabbit** [comment] 2020-09-11 18:03
Package manager lock means something else is using the package manager and AppCenter is waiting for it to be done. Are you perhaps using apt from Terminal or running another package manager like Synaptic or Ubuntu's updates tool?

**Comment by Th3Bull3t** [comment] 2020-09-20 07:21
Hi,

Thanks for your Response. I know i used an APT command in the past but can find synaptic or ubuntu update tool in appcenter. Do you know how i can check this ?

Sorry I am a Linux Newbie :)

**Comment by Th3Bull3t** [comment] 2020-09-21 06:35
> Package manager lock means something else is using the package manager and AppCenter is waiting for it to be done. Are you perhaps using apt from Terminal or **running another package manager** like Synaptic or Ubuntu's updates tool?

Hi Danrabbit, with your words ¨running another package manager¨ you let me search in the right direction. I found ¨GDebi Packet installer¨ and because i cannot install and remove software in GUI because of above appcenter error is start searching to uninstall GDEbi with a command. i found the code: `sudo dpkg --configure -a` and get a message that gdebi is trying to update a driver but can´t because secureboot is enabled. GDebi let me fix this to create a pass that i have to fill in after reboot to know i am the owner of this laptop. After this the driver is installed and Appcenter is no longer locked. 

Problem Solved is somekind unconvenient way :)

Thanks man

Regards

**Comment by danirabbit** [comment] 2022-12-27 23:14
Gonna close this as a duplicate of #114

**Closed by danirabbit** 2022-12-27 23:14 UTC
