### ISSUE TITLE
Freeze when attempting to install GIMP

### ISSUE THREAD

**Issue by jamieb22** [elementary/appcenter#1154] opened 2019-12-05 06:10 UTC
## Prerequisites

- [x] I have searched open and closed issues for duplicates.

## Describe the bug

Tried to install GIMP from App Center, and the App Center just freezed. The process io.elementary.a is running permanently at 100% of CPU.

### To Reproduce

1. Go to 'Search' then choose GIMP
2. Click on 'install"
3. Dialog pops up saying 'Install Non Curated App'
4. Click on Install Anyway

### Expected behavior

I expect App Center to go ahead and install the app.

### Screenshots or screen recordings

[appcenter_screen_record.zip](https://github.com/elementary/appcenter/files/3925338/appcenter_screen_record.zip)

### Logs

[appcenter.log](https://github.com/elementary/appcenter/files/3925342/appcenter.log)

## Platform Information

![about](https://user-images.githubusercontent.com/6212848/70208397-21be1680-1736-11ea-93d7-04f20f1f6d9a.png)

Please check what applies:

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by marcsitkin** [comment] 2019-12-12 15:19
App Center freezes when installing GIMP from the description screen. Installed after a reboot from the search results screen.

**Comment by danirabbit** [comment] 2023-01-28 00:28
Closing since this is from before we dropped Ubuntu repo support and I can confirm installing from Flatpak works as expected

**Closed by danirabbit** 2023-01-28 00:28 UTC
