### ISSUE TITLE
AppCenter needs to check for apt updates in the first run. 

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/appcenter#558] opened 2018-01-04 14:30 UTC
AppCenter as of now don't check for apt updates after a fresh install. So running app center in the first run usually shows no new apps nor updates. In some forums, the fix to this problem was given to be, open terminal and run `sudo apt-get update` and app center starts working. (This shouldn't be the case. One of the goals of elementary is to reduce dependence on the terminal). So this problem may be fixed if AppCenter automatically runs this command when started for first time. And also possibly show progress about it.

**Comment by peteruithoven** [comment] 2018-01-04 15:45
Isn't  this a duplicate of https://github.com/elementary/appcenter/issues/1 ?

**Closed** 2018-03-01 17:52 UTC
Labels: Status: Duplicate
