### ISSUE TITLE
Weird error message in app center and terminal EOS 6 beta

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/appcenter#1535] opened 2021-05-19 23:05 UTC
So, I have decided to reinstall the beta all over again. I am getting a couple of errors right out of the box.

## What Happened
When opening the app center and that spinner(on the top right corner) is spinning searching for updates, after about a minute or so, I'd get this error window. And it is the same error I get on the terminal when I run `sudo apt update`
at first, it started by the updating the repos getting stuck on "waiting for headers" forever like so
![Screenshot from 2021-05-19 00-41-31@2x](https://user-images.githubusercontent.com/49320606/118895340-81da5580-b8f5-11eb-9865-f9a3b2e69a45.png)

then, it became a pop up error message in the app store like so:
![Screenshot from 2021-05-19 00-42-51@2x](https://user-images.githubusercontent.com/49320606/118895395-9c143380-b8f5-11eb-9828-853caab64057.png)

This is now the full error message I am getting in that little pop up:
```
E: Release file for http://ppa.launchpad.net/elementary-os/daily/ubuntu/dists/focal/InRelease is not valid yet (invalid for another 3h 54min 10s). Updates for this repository will not be applied.
E: Release file for mirror://mirrors.ubuntu.com/mirrors.txt/dists/focal-updates/InRelease is not valid yet (invalid for another 1h 13min 38s). Updates for this repository will not be applied
```

then like this:
![Screenshot from 2021-05-19 18-50-32@2x](https://user-images.githubusercontent.com/49320606/118895410-a6363200-b8f5-11eb-886a-71d8c98f4ba1.png)

Then the terminal just would never accept `sudo apt update` anymore, instead, I am getting this message:

![Screenshot from 2021-05-19 18-51-24@2x](https://user-images.githubusercontent.com/49320606/118895504-d1208600-b8f5-11eb-8362-70165d4c9c22.png)

## Steps to Reproduce
Just open the app center.
AND
run `sudo apt update` in terminal

## Platform Information
Inspiron-7573-d1795795
Quad-Core Intel® Core™ i7-8550U CPU @ 1.80GHz
Intel® UHD Graphics 620 (Kabylake GT2)
NVIDIA Corporation GM108M [GeForce MX130]

**Comment by davidmhewitt** [comment] 2021-09-01 10:04
This looks like either a temporary issue with the servers hosting the repositories, or the date and time was set incorrectly on your PC.

I'm going to close this issue as we've had no other reports about it, so it's not widely reproducible.

**Closed by davidmhewitt** 2021-09-01 10:04 UTC
