### ISSUE TITLE
App Store is not retrieving app and system updates

### ISSUE THREAD

**Issue by alucarbonx** [elementary/appcenter#2061] opened 2023-07-26 14:20 UTC
### What Happened?

It's been around a month since my App Store finds no updates whenever I open it or check manually for updates using CTRL+R. I disabled automatic updates a while ago because I prefer to update apps myself. Right now the App Store behaves as if all apps and the system are up to date. However, when I run >sudo apt update && sudo apt upgrade I do find updates available. App Store version is 7.3.0. Please advise.

### Steps to Reproduce

Opened App Store
No Updates Available

### Expected Behavior

System and App Updates Available

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by prism-zip** [comment] 2024-06-21 06:35
I have the same problem

**Comment by danirabbit** [comment] 2024-06-21 20:59
Hey thanks for your report! I'm going to close this as "outdated" since AppCenter no longer handles any system package updates in the latest version so this issue will no longer be reproducible in OS 8. We've basically completely rewritten updates handling for the next release

**Closed by danirabbit** 2024-06-21 20:59 UTC
