### ISSUE TITLE
Indicator for elementary os apps

### ISSUE THREAD

**Issue by eliocamp** [elementary/appcenter#292] opened 2017-05-19 14:01 UTC
It would be nice to have a way to identify apps that are developed specifically for elementary or that are pushed through the AppCenter system instead of the other sources now available. Maybe a small badge somewhere in the icon. In future, when there's a better search functionality, maybe even add a filter to show only elementary OS apps.

**Comment by danrabbit** [comment] 2017-05-19 14:11
Closing as a duplicate of #233

**Closed by danrabbit** 2017-05-19 14:11 UTC
