### ISSUE TITLE
Date of last released version differs compared to flathub

### ISSUE THREAD

**Issue by stsdc** [elementary/appcenter#1717] opened 2021-10-09 18:57 UTC
### What Happened?

AppCenter correctly displays version, but not the release date. 

![image](https://user-images.githubusercontent.com/6031763/136670787-cec40779-d1f4-4cf5-9d19-39b8e414529e.png)

### Steps to Reproduce

1. Open gitg on AppCenter
2. Open gitg on Flathub
3. Compare release dates

### Expected Behavior

Expected dates to be the same,

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by davidmhewitt** [comment] 2021-10-09 19:05
The last release of Gitg was 25 July 2019, so AppCenter is showing the correct date for when Gitg was released here.

The date on Flathub is possibly the date that some flathub maintainer last changed the packaging or something?

Either way, this is working as intended, so I'll close this.

**Closed by davidmhewitt** 2021-10-09 19:05 UTC
