### ISSUE TITLE
Add an option to store credit card details locally

### ISSUE THREAD

**Issue by MMurzik** [elementary/appcenter#786] opened 2018-08-29 16:24 UTC
Would you mind to add an optional feature to securely store credit card information on local machine (encrypted with user password, or another chosen password or something else)?
If yes it would increase the amount of money donated to developers twice, at least at my side )
The problem is if you need to install some utility in a hurry it is faster to type 'zero' at the price field than to pick up a card and enter all those numbers.
And if I installed some software at 'zero' price, I cannot donate anymore without re-installing this app. Please add a button to donate for the installed apps. And a button to donate quickly to elementary project itself without re-entering all this credit card stuff.
Thank you!

**Comment by cassidyjames** [comment] 2018-08-30 02:00
Thanks for taking the time to fill out an issue report. I believe this would be a duplicate of #156. :wink: We definitely would like to gain the ability to one-click purchases using saved payment information in the future, likely using Stripe's customer feature (which will require a little work on the API side as well).

**Closed by cassidyjames** 2018-08-30 02:00 UTC
