### ISSUE TITLE
Login loop after installing Nvidia driver from AppCenter

### ISSUE THREAD

**Issue by mpanhans** [elementary/appcenter#1526] opened 2021-05-05 04:10 UTC
## What Happened
I noticed a driver called nvidia-340 appeared in the AppCenter, so I installed it and rebooted the machine. At the login page, I got stuck in a login loop where each time the password is entered, I am brought back to the login page again. 

I was only able to log back in to eOS by using the tty terminal to purge the Nvidia drivers, and then rebooting. 

## Expected Behavior
It appears this is a known issue on Ubuntu 20.04 with proprietary Nvidia drivers:
https://www.reddit.com/r/linuxmasterrace/comments/gfdoff/ubuntu_2004_login_loop_please_help/
https://askubuntu.com/questions/1229821/login-loop-after-installing-20-04

I don't know the right fix, but it seems something should be done so others do not get caught in a login loop from installing a suggestion from the AppCenter.

## Platform Information
eOS 6 Public Beta
2010 MacBook Pro with Nvidia GeForce

**Comment by hanaral** [comment] 2021-05-22 10:25
Assuming that you have the infamous GeForce 320M then the issue isn't the ones that you ave linked.
The problem with the GeForce 320M is that NVidia's legacy drivers for them are broken and have been broken for years because they couldn't be bothered to disable a specific feature present on the normal version of that card but not on the mobile one inside the 2010 macbook(s). I was able to get it to boot after hours of copy/pasting stuff to stop the kernel from loading the thing breaking it, but it isn't worth the effort because suspending and display brightness doesn't work.
I know performance is pretty lacking but just stick to the builtin MESA drivers

**Comment by ryonakano** [comment] 2021-05-22 11:40
I do also have an old MBA (Late 2010) that comes with the same GPU and encountered exactly the same issue. I'd like to know a solution if exists but for now I gave up installing Linux and revert to macOS High Sierra :sweat_smile:

But apparently this is not an issue we can fix in elementary ecosystem, it's an issue in the proprietary graphic driver NVidia developed, so closing as out of scope

**Closed by ryonakano** 2021-05-22 11:40 UTC
