### ISSUE TITLE
Operating System Updates

### ISSUE THREAD

**Issue by technicallyblue** [elementary/appcenter#1223] opened 2020-02-28 12:08 UTC
Periodically the Appcenter will notify me that  "org.gnome.Platform Flatpak runtime" needs updating, but it never works. It is the only update that doesn't prompt me for the password. I tried "apt update" and "apt upgrade" in the terminal and the message keeps coming back. I suppose this isn't urgent as everything else runs smoothly. So, low priority, but kinda annoying.

Thanks

**Comment by davidmhewitt** [comment] 2020-02-28 14:03
This seems like a duplicate of #1204 so I'll close this issue in favor of that one.

Additionally, `apt upgrade` will not update flatpak packages. You would need to use `flatpak update` to see if trying to update this via the terminal would work.

**Closed by davidmhewitt** 2020-02-28 14:03 UTC
