### ISSUE TITLE
[Feature Request] Pay with cryptocurrencies

### ISSUE THREAD

**Issue by armaccloud** [elementary/appcenter#716] opened 2018-05-20 14:22 UTC
Hi,
Cryptocurrencies are being used more and more.
Can the option to pay with cryptocurrencies, such as Dash / Bitcoin / Ethereum be added to the app center?

**Comment by peteruithoven** [comment] 2018-05-20 15:40
Seems like a duplicate of: https://github.com/elementary/appcenter/issues/229 ?
It probably depends on Stripe supporting cryptocurrencies.

**Comment by danrabbit** [comment] 2018-05-20 16:06
Yes, duplicate of #229

**Closed by danrabbit** 2018-05-20 16:06 UTC

**Comment by eljefuri** [comment] 2018-11-08 13:02
This is not exclusively a duplicate of #229. Inadvertently or not, @armaccloud is making a point that a variety of payment methods should be supported. Most of the world does not use the Visa/MasterCard network.
