### ISSUE TITLE
Adding release log details

### ISSUE THREAD

**Issue by ScarWar** [elementary/appcenter#461] opened 2017-08-17 15:02 UTC
Many times I download apps and I want to see the release log. To me, seeing what bugs are fixed gives the ability to help the developer in finding new bugs, or if I tried an app in the past and removed it because of bugs or crashes, I can see if the bug is fixed and try it again. I can learn new features and abilities which make me a better user of the app.
Same thing for system updates. Every distro has bugs which need to be fixed and features which may not work as expected, and every release has new features, knowing this information helps me as a user.
I think a release log should be add to the app pages in the app store, or at least the a link to the release log. 

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by davidmhewitt** [comment] 2017-08-17 15:27
This is a duplicate of #296 which has been fixed in #424.

So, this will hopefully make it into the next update of AppCenter.

Thank you for the report,
David

**Closed** 2017-08-17 15:27 UTC
