### ISSUE TITLE
CPU usage too high

### ISSUE THREAD

**Issue by arkhenstone** [elementary/appcenter#1160] opened 2019-12-19 14:19 UTC
For some reason, CPU usage can get up to 100% of a thread as seen on this image : 
![image](https://user-images.githubusercontent.com/17592744/71179975-89657d00-2271-11ea-9244-f93d9d4a58cd.png)

Of course I'm on Hera (update from Juno), Kernel 4.15.0-72-generic, Intel i5-8250U @ 3.4GHz, updates are completed, no task going, and it's constant. 

If anything I did was installing an app with Sideload in the morning from flathub, and I had 6 hours uptime, 4 of which the app center was launched.

Don't hesitate to ask for more information.

**Comment by robertgorbul** [comment] 2020-01-22 20:00
Hi! Recently I noticed occasional performance drops and found out that rarely Appcenter stays in the background with 60-80% CPU usage. Unfortunately I couldn't catch it during screencast but maybe that video still will be helpful:
[Screencast from 2020-01-22 22.52.10.webm.tar.gz](https://github.com/elementary/appcenter/files/4099670/Screencast.from.2020-01-22.22.52.10.webm.tar.gz)
Github don't support webm so I've put it into archive (9mb)

**Comment by Marszczak** [comment] 2020-02-22 17:16
Same happened to me today - cannot reproduce tho...

**Comment by davidmhewitt** [comment] 2020-04-14 16:16
If anyone is able to reproduce this issue, please can you run `pkmon` in the terminal while it is happening so we can see if it's actually PackageKit stuck in a loop.

If `pkmon` is outputting loads of lines to the terminal, please copy a section of them (they'll likely be repeating) and add them to the issue. Additionally, please confirm you have no broken PPAs or repositories added to your system by running an `apt update` and noting if there are any errors or warnings.

**Comment by wout** [comment] 2020-04-20 06:25
Not sure if it is the same issue, but lately I find AppCenter processor hogging a lot. Currently, it isn't even open, and I last opened it more than 16 hours ago:

![image](https://user-images.githubusercontent.com/107324/79720098-cef58d80-82d7-11ea-8665-2ea9e2a71f7e.png)

The only thing that helps would be to kill it. `pkmon` doesn't move a bit.

**Comment by egee-irl** [comment] 2020-04-21 16:44
Same story here - it seems to have gotten worse after the most recent updates.

In the screenshot below, I haven't even opened AppCenter at all; I didn't even realize it was in Plank until I opened htop and saw the cpu usage.

`pkmon` outputs this:

```
egee@egee-workstation:~$ pkmon
Transactions:
 [none]
daemon connected=0
daemon connected=1
network status=online
```

I've also confirmed that `apt update` works just fine. Output:

```
Fetched 7,775 kB in 8s (1,022 kB/s)                                                                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
38 packages can be upgraded. Run 'apt list --upgradable' to see them.
egee@egee-workstation:~$ 
```

I have a strong suspicion that this has _something_ to do with the Flatpak integration.

![image](https://user-images.githubusercontent.com/6679968/79890344-36810b00-83b4-11ea-9ec4-ea50f5c2f91f.png)

**Comment by egee-irl** [comment] 2020-04-21 18:10
Update -

I ran `flatpak update` and `apt upgrade` to update everything on my system manually outside of AppCenter.

When I opened AppCenter to check for updates, it reports some 2gb worth of updates, despite there not being any updates available (see attached screenshot).

When I click "Update All" in AppCenter, I am prompted for my password and each package in the list is quickly updated and removed leaving me with "No components with updates".

Despite this, AppCenter continues to use an almost hilariously obscene amount of CPU and the app itself reports 1 update but does not show it in the list.

Before running AppCenter's update

![image](https://user-images.githubusercontent.com/6679968/79898630-6a622d80-83c0-11ea-95f3-d54fa70fdf58.png)

After running AppCenter's update

![image](https://user-images.githubusercontent.com/6679968/79898801-b2815000-83c0-11ea-94b2-ff02fbfb383f.png)

**Comment by davidmhewitt** [comment] 2020-04-21 20:34
Interesting, that seems to confirm it's not PackageKit. We had seen an issue in the past where PackageKit would occasionally lock up the CPU like that.

This isn't obviously reproducible as it's not happening on my machine and AppCenter has been happily running in the background for a couple of days of uptime with 0% CPU usage.

I suspect that killing AppCenter will probably (temporarily) fix the issue, but to humor me, could you run the following in the terminal to start AppCenter with debug logging:

```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter -s
```

This won't show an AppCenter window, it will run in the background like it does when you start the computer. You should get a bunch of debug logging from that and the CPU usage will probably be pretty high to start with as it does its initial check for updates, but then should settle down to 0%.

As long as you keep that terminal open, it will continue to run. I'd be interested to see if there is anything going on in the logging if/when that high CPU usage issue happens again.

**Comment by egee-irl** [comment] 2020-05-03 13:32
I haven't been able to reproduce this since posting my last comment, and I've been running AppCenter in debug mode this whole time.

If commentators or Googlers see this issue occurring for them, please try to above mentioned debugging hook for AppCenter and try to reproduce it again.

As it stands, we don't have enough information about the issue to reproduce it, let alone fix it. Let's hope it stays away for good! :crossed_fingers:

**Comment by wout** [comment] 2020-05-09 07:54
I just hat AppCenter hogging again. So I ran:

```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter -s
```

Then waited for a minute and it started again:

![image](https://user-images.githubusercontent.com/107324/81467621-cce56700-91d1-11ea-8aa1-42b3c657d2f7.png)

It's now almost 10 minutes later and it's still going.
Here is the last part of the output.

```
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:02.224: role now resolve
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:02.294: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:02.792: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:02.792: adding state 0x558d7b9881c0
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:02.792: role now remove-packages
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:02.829: using frontend gnome
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:02.829: using socket in /tmp/gpk-10298_cbbebcde.socket
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:04.576: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:05.416: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:07.980: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:07.997: remove state 0x558d7b9881c0
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:07.999: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:07.999: role now get-packages
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:08.010: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:08.081: emit updates-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:09.397: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:09.416: role now get-updates
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:09.457: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:09.764: emit updates-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:10.402: emit transaction-list-changed
** (io.elementary.appcenter:2152): DEBUG: 08:46:10.402: UpdateManager.vala:69: PackageKit backend reports 0 updates
** (io.elementary.appcenter:2152): DEBUG: 08:46:11.434: UpdateManager.vala:97: Flatpak backend reports 0 updates
** (io.elementary.appcenter:2152): DEBUG: 08:46:11.434: UpdateManager.vala:134: No OS updates found
** (io.elementary.appcenter:2152): DEBUG: 08:46:11.434: UpdateManager.vala:146: 0 app updates found
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:11.547: adding state 0x558d7b988280
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:11.547: role now search-name
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:11.587: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:12.513: remove state 0x558d7b988280
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:12.513: adding state 0x558d7b988340
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:12.513: role now get-details
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:12.513: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:12.528: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:13.301: remove state 0x558d7b988340
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:13.301: role now depends-on
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:13.303: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:13.314: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:14.030: role now get-details
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:14.038: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:14.043: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:14.845: role now get-packages
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:14.852: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:14.863: emit transaction-list-changed
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:46:16.179: emit transaction-list-changed

(io.elementary.appcenter:2152): Gtk-WARNING **: 08:46:22.938: Child name 'Graphics' not found in GtkStack
```

The full output since start of debug command can be found here:
https://gist.github.com/wout/5f948148a5ddd67bde50a5e57dd4cb8a

**Comment by davidmhewitt** [comment] 2020-05-09 08:29
@wout Interesting, so there's nothing new being printed to the logs while it's using 100% CPU and you leave it alone? Your logs only cover 3 minutes, but you say it's been using 100% CPU for over 10?

The logs pause for about 80 seconds here:
```
** (io.elementary.appcenter:2152): DEBUG: 08:43:41.156: UpdateManager.vala:146: 0 app updates found
(io.elementary.appcenter:2152): PackageKit-DEBUG: 08:45:00.762: emit updates-changed
```

Did you do anything with `apt`/`apt-get` on the command line around then? Or use something else that potentially installs/updates/removes packages? Usually `updates-changed` is something else using apt.

Then there's some logs further down that seem to suggest you removed a package with AppCenter?

I'm just trying to understand what else happened with the computer during this time in case it's important in reproducing the issue.

**Comment by wout** [comment] 2020-05-09 10:25
@davidmhewitt As you can see in the gist, the first line is at `08:43:35.748`, the last one `08:51:20.763`. In those 8 minutes, I did nothing but take screenshots and uninstall the app Dot Matrix, while the AppCenter window was still open. At the time I reported here, it was running over 10 minutes, with three instances of the AppCenter each taking 100% of a core.

But before I ran the debug command, it was already hogging for at least 15 minutes. So I killed it, ran the debug command, opened the AppCenter and there they were again at 100%. So even after killing, merely opening up the AppCenter made them continue.

I noticed something strange, but I'm not absolutely sure if it's something. Before killing, there were only two cores occupied at 100%. After killing and re-opening, there were three. The third one might be the debug process of course.

**Comment by davidmhewitt** [comment] 2020-05-10 19:46
@wout yes, sorry, I see that there are 8 minutes of logs, but was I was surprised about was that there are seemingly only approx. 3 minutes where it was logging activity. The rest is relatively quiet.

While this issue is happening, is AppCenter otherwise functional? Can you reliably reproduce this every time you start it now?

If you can reproduce this again, can you show us the output of:
```
top -H -p `pidof io.elementary.appcenter`
```

**Comment by wout** [comment] 2020-05-11 07:49
@davidmhewitt I can't really reproduce this. I'll have to wait until AppCenter starts hogging again because it happens out of the blue. I haven't found a way to invoke this manually.

Once it happens, I'll report back.

**Comment by wout** [comment] 2020-05-20 06:07
So, I just did a reboot for the first time a few minutes in, it started again. It's now running for 20 minutes, and I haven't opened AppCenter. Here is the information you asked for:

![image](https://user-images.githubusercontent.com/107324/82410577-1a7e9100-9a68-11ea-84dc-a0bbfaf7ccbe.png)

So **content-loading** is the bad guy here I guess.

**Comment by davidmhewitt** [comment] 2020-05-20 08:16
`content-loading` is a thread within AppCenter that loads the extra information about an app (screenshots, etc...) when you open its info page within AppCenter.

From the code, I don't think I can see a way that thread can be running if you haven't opened AppCenter and clicked on an application.

This is also differerent to your previous screenshots in that AppCenter is only utilising 1 core at 100% instead of multiple.

What happens if you open AppCenter and browse around a few apps while running that `top` I provided earlier? Do you see `content-loading` threads start and stop?

**Comment by wout** [comment] 2020-05-20 09:04
I've let it be for a while but it does not go away:

![image](https://user-images.githubusercontent.com/107324/82426622-00e94380-9a80-11ea-8761-93a834d3d4b7.png)

Since rebooting this morning, I didn't open AppCenter. After opening and clicking on one app, a second process called **content-loading** is started:

![image](https://user-images.githubusercontent.com/107324/82426863-49086600-9a80-11ea-99df-ef40cc6b2553.png)

And so is every time I click on one, until 🤯️:

![greedy-elementaryos-appcenter](https://user-images.githubusercontent.com/107324/82427416-ff6c4b00-9a80-11ea-8599-e6838cda4e0e.png)

It doesn't go beyond 8, that's the number of cores available.

**Comment by davidmhewitt** [comment] 2020-05-20 09:56
@wout I don't think there's much more information we can get from that running instance of AppCenter, so feel free to kill it to save some energy ;)

I'd be interested to see if that happens every time you open it and open app pages.

Then, I'd also be interested to see what happens if you try deleting the screenshot cache folder at `~/.cache/io.elementary.appcenter/screenshots` and then trying to reproduce it.

**Comment by wout** [comment] 2020-05-20 11:01
Same happens. After killing it, and opening those app pages, they start again:

![greedy-elementaryos-appcenter-02](https://user-images.githubusercontent.com/107324/82438149-7e1cb480-9a90-11ea-90d4-999c8c2ea88e.png)

But... 🥁️ I think we have a winner with deleting the screenshot cache dir 🎉️:

![greedy-elementaryos-appcenter-punished](https://user-images.githubusercontent.com/107324/82438595-39dde400-9a91-11ea-83c4-e37cef29a1d9.png)

No more **content-loading** processes. And, app images are loading instantaneously now. Before they were just grey placeholders with a spinner in the middle, and the image would never load.

**Comment by davidmhewitt** [comment] 2020-05-20 11:06
Great, I'll put a note on my to-do list to look at the screenshot caching code to see if I can improve it and stop this happening again in future.

Thanks for all your help in narrowing down the issue. I'll leave this issue open for now so other people can find it easier and use the troubleshooting steps to see if they have the same issue or a different one.

**Comment by davidmhewitt** [comment] 2020-06-02 12:14
Found what causes this and opened a PR here to solve the issue:
https://github.com/elementary/appcenter/pull/1350

When the screenshot cache folder goes over 100MB, there is some code that's supposed to clean it up and keep it under 100MB. That code isn't great and gets stuck.

My PR rewrites the screenshot caching code to be a lot more fail-safe and simple. Once this PR is merged, this issue will be closed/fixed.

Thanks again to everyone for helping track this down.

**Closed** 2020-06-08 07:09 UTC
Labels: Status: Confirmed, Status: In Progress

**Comment by joe733** [comment] 2021-02-13 04:09
Umm.. it's still on the hike.. along with gala https://github.com/elementary/gala/issues/468#issuecomment-778559641

![Screenshot from 2021-02-13 09-33-44](https://user-images.githubusercontent.com/38415384/107841232-33da2100-6ddf-11eb-8478-a6bb5205ecc5.png)
