### ISSUE TITLE
Se cierra la appcenter sin motivo aparente / The appcenter is closed for no apparent reason

### ISSUE THREAD

**Issue by RaidenSkyhard** [elementary/appcenter#1244] opened 2020-04-02 17:37 UTC
I has one month using Elementary OS, but in the last two weeks I have many problems with the appcenter. The program closes with no aparent reason searching apps and updating.

**Comment by davidmhewitt** [comment] 2020-04-06 13:30
I think crashing when updating is maybe a duplicate of https://github.com/elementary/appcenter/issues/1197 which we are working on a fix for.

Can you provide more information about the crashes while searching? Does it happen when searching for certain things? Does it happen every time at the same place?

Also, if you run the following from the terminal and then make it crash again, maybe there is something in the logs that can help us:
```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

**Comment by davidmhewitt** [comment] 2020-04-14 15:55
The crash while updating should now be fixed.

I'm going to close this issue as I can't reproduce a crash while searching and I'm cleaning up the issue tracker. But if you are still able to reproduce the crash while searching, please add the extra details I have requested and re-open the issue.

**Closed by davidmhewitt** 2020-04-14 15:55 UTC
Labels: Status: Incomplete
