### ISSUE TITLE
On new installation appcenter won't start

### ISSUE THREAD

**Issue by amzamora** [elementary/appcenter#500] opened 2017-10-12 17:00 UTC
In every new installation of elementary until now i had to type on the terminal:
```
sudo apt-get update
```
To be able to open the AppCenter.

When launch AppCenter from terminal, before updating the repositories i get this:
```
** (process:2231): ERROR **: Client.vala:85: Metadata files have errors: /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-backports_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-backports_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/cl.archive.ubuntu.com_ubuntu_dists_xenial_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/packages.elementary.io_appcenter_dists_xenial_main_dep11_Components-amd64.yml.gz
Trace/breakpoint trap (core dumped)
```

**Comment by davidmhewitt** [comment] 2020-04-19 19:37
I'm going to close this issue since I vaguely remember adding better error handling to loading faulty appstream files at some point.

If someone comes across this issue and can reproduce, feel free to re-open.

**Closed by davidmhewitt** 2020-04-19 19:37 UTC
