### ISSUE TITLE
Don't show non-curated apps in "other apps" section

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#958] opened 2019-02-26 21:11 UTC
Right now [Wineglass](https://appcenter.elementary.io/com.github.aggalex.wineglass) has a developer name of "Alex". Apparently a random other non-curated app in AppCenter also has its developer name as "Alex", so it incorrectly shows up under other apps by the same developer.

**Comment by danrabbit** [comment] 2019-02-26 22:54
I wonder if we should maybe be doing some kind of RDNN matching instead of just blindly trusting the developer name tag since there's no real way to prevent namespace collisions there

**Comment by danrabbit** [comment] 2022-05-22 00:29
Closing as a duplicate of #1814 since it has more information

**Closed by danrabbit** 2022-05-22 00:29 UTC
