### ISSUE TITLE
Lack of kernel headers result in borked wifi driver installation and immediate loss of internet

### ISSUE THREAD

**Issue by Vitorvlv** [elementary/appcenter#1614] opened 2021-08-20 01:49 UTC
## What Happened

I have a broadcom wireless card. Right now this card has 3 drivers for linux. A closed source one, a reverse engineered open source one in the kernel and a official open source one also in the kernel, which is the default in a new installation of elementary os. Some more info on the Arch Wiki: https://wiki.archlinux.org/title/Broadcom_wireless

In the driver section of the app center it gave me the choice of installing the cloused source driver, which was nice, it performs way better than the one in the kernel for me.

Unfortunately the installation doesn't complete correctly. While installing the wifi stops working, and after rebooting the wireless card is not recognized anymore. There's no error messages on the app center, nothing to warn the user something went wrong or the reason.

To figure it out what was going wrong, I performed the installation through the terminal, and it turns out dkms is complaining about missing kernel headers. 

apt install linux-headers-5.11.0-27-generic and then trying to install the driver again is enough to solve the issue.  

But If I wasn't someone with a little bit of experience on linux already I wouldn't know that, so either the kernel headers should come installed by default, or they should be installed automatically when the user installs the wireless driver from the app center.

## Platform Information
* OS: Elementary OS 6
* Wireless card: BCM43224
* Wireless driver shown in the app center: bcmwl-kernel-source

**Comment by davidmhewitt** [comment] 2021-08-20 06:21
Thanks for the report!

This appears to be a duplicate of #1603 where I've recently added some more discussion about how it appears to be an Ubuntu packaging issue, but how we should look to see if there's a way we can make this more friendly as you suggest.

I'll close this issue as a duplicate.

**Closed by davidmhewitt** 2021-08-20 06:21 UTC
