### ISSUE TITLE
The indicator of available updates is broken

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/appcenter#1172] opened 2020-01-10 12:02 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The notifications of available updates is broken.

### To Reproduce
Wait for available updates and the AppCenter icon to show up in Plank.

### Expected behavior
The number of updates available should be the same (and correct).

### Screenshots or screen recordings
![Captura de pantalla de 2020-01-10 08-53-26](https://user-images.githubusercontent.com/6054951/72151558-49347e80-3387-11ea-8869-817444fe48f2.png)
Shows `0` updates. This is wrong in itself, but also wrong because there are indeed updates.

![Captura de pantalla de 2020-01-10 08-53-35](https://user-images.githubusercontent.com/6054951/72151593-5c474e80-3387-11ea-8e6d-f1a3623a814a.png)
No indication of available updates in the `Installed`button.

![Captura de pantalla de 2020-01-10 08-53-42](https://user-images.githubusercontent.com/6054951/72151612-6d905b00-3387-11ea-8268-6a87d6867c83.png)
There are indeed a number of available updates.

## Platform Information
![Captura de pantalla de 2020-01-10 09-01-30](https://user-images.githubusercontent.com/6054951/72151764-d37ce280-3387-11ea-97b6-5903e9acd11e.png)

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Related to #874, but more broken.

**Comment by KomalleanaByzantis** [comment] 2020-01-24 20:30
This is already referenced in #1136. I have contributed a small report of my own on said issue.

**Comment by davidmhewitt** [comment] 2020-02-13 18:09
Closing as a duplicate of #1136

**Closed by davidmhewitt** 2020-02-13 18:09 UTC
