### ISSUE TITLE
Same apps are displayed several times on the home page.

### ISSUE THREAD

**Issue by NathanBnm** [elementary/appcenter#946] opened 2019-01-26 21:18 UTC
Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/51792897-33e73400-21b8-11e9-9c8d-8b65537ff370.png)

**Comment by peteruithoven** [comment] 2019-01-26 21:20
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/appcenter/issues/939

**Closed by peteruithoven** 2019-01-26 21:20 UTC
