### ISSUE TITLE
appcenter crashes on clicking pay

### ISSUE THREAD

**Issue by aaronrossdickey** [elementary/appcenter#829] opened 2018-09-28 22:56 UTC
I attempted to purchase an app with a debit card, bank declined the transaction. Attempted to use a credit card, input the card details and clicked pay, appcenter crashed.

Checking the debug output and the only entry I got when I clicked the pay button was segmentation fault (core dumped)

**Comment by peteruithoven** [comment] 2018-09-28 23:11
Which app? Are you running Loki or Juno? Have you set your system to another language?

**Comment by aaronrossdickey** [comment] 2018-09-28 23:50
Formater, Loki, no US English is the language.

**Comment by peteruithoven** [comment] 2018-09-29 00:18
I was hoping to reproduce the issue, I tried on Juno (beta 1) and Loki (in VirtualBox) and in both I was able to pay and install. 
Do you experience similar issues with other apps?

**Comment by davidmhewitt** [comment] 2020-04-09 07:54
I'm cleaning up the issue tracker and I feel it's best to close this issue as we never got the root cause and it's been a long time since we had any reports like this. Please feel free to re-open or open a new issue if it's something you're still experiencing occasionally.

**Closed by davidmhewitt** 2020-04-09 07:54 UTC
