### ISSUE TITLE
Updates not completing for flatpak runtime

### ISSUE THREAD

**Issue by selwynorren** [elementary/appcenter#1529] opened 2021-05-06 23:38 UTC
## What Happened
Constantly requiring updates of two elements:
1.  io.elementary.Platform Flatpak runtime
2. io.elementary.Sdk Flatpak runtime

Even if updated is run, after a few minutes it requires these same two files to be updated again

## Expected Behavior
To be updated and be done with it, until they are needed to be updated again

## Steps to Reproduce
1. Make use of Elementary OS 6 Beta or Latest Daily Build

## Platform Information
Elementary OS 6 Beta with Updates

**Comment by pierrers-design** [comment] 2021-05-08 19:18
Same issue as the #1530, and I have the same bug, these two packages stay after many reboot and even with updating flatpak from command line.

**Comment by selwynorren** [comment] 2021-05-10 08:26
This mornings update, seems to have resolved the issue for me, I am no longer getting the update notifications, Thanks guys

**Comment by RedBearAK** [comment] 2021-05-10 19:59
> This mornings update, seems to have resolved the issue for me, I am no longer getting the update notifications, Thanks guys

I'm still having the issue, just attempted the update a few minutes ago. (Mid-day, Monday, Alaska time.) 

The updates keep showing up in AppCenter, but when you run `sudo apt update` and `sudo apt upgrade` or even `sudo apt full-upgrade` in a terminal, no Flatpak related updates are listed. It's as if the information about these Flatpak updates are stuck in some kind of AppCenter cache, but they don't really exist. That's why they keep failing and won't go away. 

Issue #1530 is definitely a duplicate of this.

**Comment by RedBearAK** [comment] 2021-05-13 07:43
Problem seems to have disappeared after a bunch of new updates came in. Tried several reboots and checking for updates, AppCenter always shows no updates available now. No more Flatpak ghosts.

**Comment by meisenzahl** [comment] 2021-05-13 08:51
If someone can reproduce it, please comment and then we can reopen.

**Closed by meisenzahl** 2021-05-13 08:51 UTC

**Comment by codydietrich** [comment] 2021-08-16 20:23
I am encountering this issue on Elementary OS 6 stable build. I see these 2 updates in AppCenter, and they have been present since my install of eOS 6 a few days ago.
```
org.freedesktop.Platform Flatpak runtime
org.freedesktop.Sdk Flatpak runtime
```

If I run `flatpak update` on the command line I get the following error:
```
$ flatpak update
Looking for updates…


        ID                                             Branch            Op           Remote            Download
 1. [✗] org.freedesktop.Platform.GL.default            20.08             i            flathub           1.0 kB / 106.4 MB

Warning: While trying to checkout 3fbdbccc95abfb14b4a0fd619f8dd80106abd6c8538596d6b47cc9b0ea865ddd into /home/cody/.local/share/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/20.08/.3fbdbccc95abfb14b4a0fd619f8dd80106abd6c8538596d6b47cc9b0ea865ddd-1UKV70: Opening content object 3f1054489afcf678e95c68818581684f8a4f8237d3c7d50d59fec1fdbd07a912: Couldn't find file object '3f1054489afcf678e95c68818581684f8a4f8237d3c7d50d59fec1fdbd07a912'
Installation complete.
```

Hope this helps.

**Comment by bambukouk** [comment] 2022-07-03 09:08
I am experiencing very `similar problem?`:

https://elementaryos.stackexchange.com/questions/29875/unwanted-os-system-components-update
