### ISSUE TITLE
Number of updates indicated in Plank, but not in the app itself

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/appcenter#874] opened 2018-10-25 16:08 UTC
See below:

![captura de pantalla de 2018-10-24 17-36-13](https://user-images.githubusercontent.com/6054951/47514529-ff7d7800-d856-11e8-8acd-0236590252c7.png)

**Comment by danrabbit** [comment] 2020-04-27 23:16
Closing as a duplicate of #81

**Closed by danrabbit** 2020-04-27 23:16 UTC
