### ISSUE TITLE
App Center is making my CPU go crazy

### ISSUE THREAD

**Issue by belenos** [elementary/appcenter#693] opened 2018-04-25 18:50 UTC
App Center running on Pop!_OS 18.04 is showing an odd behaviour lately, demanding a lot of CPU power while running in background (I've only noticed it bc the system hanged twice while I was watching an youtube video). Fresh install, updated this morning e running for about 3-4 hours. 

Here are the system monitor screenshots before and after killing the process:

![screenshot from 2018-04-25 15-34-00](https://user-images.githubusercontent.com/1954831/39266378-3cb18f0a-48a0-11e8-8955-fc0c04d5147f.png)
![screenshot from 2018-04-25 15-34-41](https://user-images.githubusercontent.com/1954831/39266381-4078bb90-48a0-11e8-8a59-77fdb5a3e7bb.png)

I've submitted this issue to pop_os github page as well (https://github.com/pop-os/pop/issues/218). Let me know if you guys have any difficulties to reproduce this behaviour.

**Comment by davidmhewitt** [comment] 2018-11-21 15:33
Sorry it's taken so long to get a reply to this issue, I'm going through the issue tracker and seeing which ones may or may not still be relevant.

Do you still experience this issue? If so, could you run `pkmon` in a console while this issue is happening and post a snippet of the output?

**Comment by mikelmason** [comment] 2019-01-08 19:35
Mine eats CPU also. And crashes. I notice the temp on my video card increases as well (nvidia gtx1050ti/intel).

Where are the logs stored for app center?

pkmon
[Transactions:
 [none]
daemon connected=1
network status=online
Transactions:
 1	/366_dbcdccca
/366_dbcdccca	allow_cancel 1
/366_dbcdccca	percentage   -1
/366_dbcdccca	role         search-name
/366_dbcdccca	status       setup
/366_dbcdccca	status       loading-cache
/366_dbcdccca	percentage   0
/366_dbcdccca	percentage   100
/366_dbcdccca	percentage   0
/366_dbcdccca	percentage   50
Transactions:
 1	/366_dbcdccca
 2	/367_aabeccba
/367_aabeccba	allow_cancel 1
/367_aabeccba	percentage   -1
/367_aabeccba	role         search-name
/367_aabeccba	status       wait
/366_dbcdccca	percentage   100
/366_dbcdccca	status       query
/366_dbcdccca	percentage   -1
/366_dbcdccca	percentage   100
/366_dbcdccca	status       finished
/366_dbcdccca	exit code: success
Transactions:
 1	/367_aabeccba
/367_aabeccba	status       setup
/367_aabeccba	status       loading-cache
Transactions:
 1	/367_aabeccba
 2	/368_edcabcad
/368_edcabcad	allow_cancel 1
/368_edcabcad	percentage   -1
/368_edcabcad	role         get-details
/368_edcabcad	status       wait
/367_aabeccba	percentage   0
/367_aabeccba	percentage   100
/367_aabeccba	percentage   0
/367_aabeccba	percentage   50
/367_aabeccba	percentage   100
/367_aabeccba	status       query
/367_aabeccba	percentage   -1
/367_aabeccba	percentage   100
/367_aabeccba	status       finished
/367_aabeccba	exit code: success
Transactions:
 1	/368_edcabcad
/368_edcabcad	status       setup
/368_edcabcad	status       loading-cache
Transactions:
 1	/368_edcabcad
 2	/369_bbacabee
/369_bbacabee	allow_cancel 1
/369_bbacabee	percentage   -1
/369_bbacabee	role         get-details
/369_bbacabee	status       wait
/368_edcabcad	percentage   0
/368_edcabcad	percentage   100
/368_edcabcad	percentage   0
/368_edcabcad	percentage   50
/368_edcabcad	percentage   100
/368_edcabcad	status       query
/368_edcabcad	status       finished
/368_edcabcad	exit code: success
Transactions:
 1	/369_bbacabee
/369_bbacabee	status       setup
/369_bbacabee	status       loading-cache
Transactions:
 1	/369_bbacabee
 2	/370_cdedabde
/370_cdedabde	allow_cancel 1
/370_cdedabde	percentage   -1
/370_cdedabde	role         depends-on
/370_cdedabde	status       wait
/369_bbacabee	percentage   0
/369_bbacabee	percentage   100
/369_bbacabee	percentage   0
/369_bbacabee	percentage   50
/369_bbacabee	percentage   100
/369_bbacabee	status       query
/369_bbacabee	status       finished
/369_bbacabee	exit code: success
Transactions:
 1	/370_cdedabde
/370_cdedabde	status       setup
/370_cdedabde	status       loading-cache
Transactions:
 1	/370_cdedabde
 2	/371_baaaabad
/371_baaaabad	allow_cancel 1
/371_baaaabad	percentage   -1
/371_baaaabad	role         depends-on
/371_baaaabad	status       wait
/370_cdedabde	percentage   0
/370_cdedabde	percentage   100
/370_cdedabde	percentage   0
/370_cdedabde	percentage   50
/370_cdedabde	percentage   100
/370_cdedabde	status       query
/370_cdedabde	status       finished
/370_cdedabde	exit code: success
Transactions:
 1	/371_baaaabad
/371_baaaabad	status       setup
/371_baaaabad	status       loading-cache
/371_baaaabad	percentage   0
/371_baaaabad	percentage   100
/371_baaaabad	percentage   0
/371_baaaabad	percentage   50
/371_baaaabad	percentage   100
/371_baaaabad	status       query
/371_baaaabad	status       finished
Transactions:
 [none]
/371_baaaabad	exit code: success
Transactions:
 1	/372_abaceeaa
/372_abaceeaa	allow_cancel 1
/372_abaceeaa	percentage   -1
/372_abaceeaa	role         search-name
/372_abaceeaa	status       setup
/372_abaceeaa	status       loading-cache
/372_abaceeaa	percentage   0
/372_abaceeaa	percentage   100
/372_abaceeaa	percentage   0
/372_abaceeaa	percentage   50
Transactions:
 1	/372_abaceeaa
 2	/373_eabeddde
/373_eabeddde	allow_cancel 1
/373_eabeddde	percentage   -1
/373_eabeddde	role         search-name
/373_eabeddde	status       wait
/372_abaceeaa	percentage   100
/372_abaceeaa	status       query
/372_abaceeaa	percentage   -1
/372_abaceeaa	percentage   100
/372_abaceeaa	status       finished
/372_abaceeaa	exit code: success
Transactions:
 1	/373_eabeddde
/373_eabeddde	status       setup
/373_eabeddde	status       loading-cache
Transactions:
 1	/373_eabeddde
 2	/374_ddaeeced
/374_ddaeeced	allow_cancel 1
/374_ddaeeced	percentage   -1
/374_ddaeeced	role         get-details
/374_ddaeeced	status       wait
/373_eabeddde	percentage   0
/373_eabeddde	percentage   100
/373_eabeddde	percentage   0
/373_eabeddde	percentage   50
/373_eabeddde	percentage   100
/373_eabeddde	status       query
/373_eabeddde	percentage   -1
/373_eabeddde	percentage   100
/373_eabeddde	status       finished
/373_eabeddde	exit code: success
Transactions:
 1	/374_ddaeeced
/374_ddaeeced	status       setup
/374_ddaeeced	status       loading-cache
Transactions:
 1	/374_ddaeeced
 2	/375_edaeaaec
/375_edaeaaec	allow_cancel 1
/375_edaeaaec	percentage   -1
/375_edaeaaec	role         get-details
/375_edaeaaec	status       wait
/374_ddaeeced	percentage   0
/374_ddaeeced	percentage   100
/374_ddaeeced	percentage   0
/374_ddaeeced	percentage   50
/374_ddaeeced	percentage   100
/374_ddaeeced	status       query
/374_ddaeeced	status       finished
/374_ddaeeced	exit code: success
Transactions:
 1	/375_edaeaaec
/375_edaeaaec	status       setup
/375_edaeaaec	status       loading-cache
Transactions:
 1	/375_edaeaaec
 2	/376_ccccbeae
/376_ccccbeae	allow_cancel 1
/376_ccccbeae	percentage   -1
/376_ccccbeae	role         depends-on
/376_ccccbeae	status       wait
/375_edaeaaec	percentage   0
/375_edaeaaec	percentage   100
/375_edaeaaec	percentage   0
/375_edaeaaec	percentage   50
/375_edaeaaec	percentage   100
/375_edaeaaec	status       query
/375_edaeaaec	status       finished
/375_edaeaaec	exit code: success
Transactions:
 1	/376_ccccbeae
/376_ccccbeae	status       setup
/376_ccccbeae	status       loading-cache
Transactions:
 1	/376_ccccbeae
 2	/377_dbceeaab
/377_dbceeaab	allow_cancel 1
/377_dbceeaab	percentage   -1
/377_dbceeaab	role         depends-on
/377_dbceeaab	status       wait
/376_ccccbeae	percentage   0
/376_ccccbeae	percentage   100
/376_ccccbeae	percentage   0
/376_ccccbeae	percentage   50
/376_ccccbeae	percentage   100
/376_ccccbeae	status       query
/376_ccccbeae	status       finished
/376_ccccbeae	exit code: success
Transactions:
 1	/377_dbceeaab
/377_dbceeaab	status       setup
/377_dbceeaab	status       loading-cache
/377_dbceeaab	percentage   0
/377_dbceeaab	percentage   100
/377_dbceeaab	percentage   0
/377_dbceeaab	percentage   50
/377_dbceeaab	percentage   100
/377_dbceeaab	status       query
/377_dbceeaab	status       finished
/377_dbceeaab	exit code: success
Transactions:
 [none]
Transactions:
 1	/378_cbaecbae
/378_cbaecbae	allow_cancel 1
/378_cbaecbae	percentage   -1
/378_cbaecbae	role         search-name
/378_cbaecbae	status       setup
/378_cbaecbae	status       loading-cache
/378_cbaecbae	percentage   0
/378_cbaecbae	percentage   100
/378_cbaecbae	percentage   0
/378_cbaecbae	percentage   50
Transactions:
 1	/378_cbaecbae
 2	/379_bddbcbba
/379_bddbcbba	allow_cancel 1
/379_bddbcbba	percentage   -1
/379_bddbcbba	role         search-name
/379_bddbcbba	status       wait
/378_cbaecbae	percentage   100
/378_cbaecbae	status       query
/378_cbaecbae	percentage   -1
/378_cbaecbae	percentage   100
/378_cbaecbae	status       finished
/378_cbaecbae	exit code: success
Transactions:
 1	/379_bddbcbba
/379_bddbcbba	status       setup
/379_bddbcbba	status       loading-cache
Transactions:
 1	/379_bddbcbba
 2	/380_acbbdccd
/380_acbbdccd	allow_cancel 1
/380_acbbdccd	percentage   -1
/380_acbbdccd	role         get-details
/380_acbbdccd	status       wait
/379_bddbcbba	percentage   0
/379_bddbcbba	percentage   100
/379_bddbcbba	percentage   0
/379_bddbcbba	percentage   50
/379_bddbcbba	percentage   100
/379_bddbcbba	status       query
/379_bddbcbba	percentage   -1
/379_bddbcbba	percentage   100
/379_bddbcbba	status       finished
/379_bddbcbba	exit code: success
Transactions:
 1	/380_acbbdccd
/380_acbbdccd	status       setup
/380_acbbdccd	status       loading-cache
Transactions:
 1	/380_acbbdccd
 2	/381_beababca
/381_beababca	allow_cancel 1
/381_beababca	percentage   -1
/381_beababca	role         get-details
/381_beababca	status       wait
/380_acbbdccd	percentage   0
/380_acbbdccd	percentage   100
/380_acbbdccd	percentage   0
/380_acbbdccd	percentage   50
/380_acbbdccd	percentage   100
/380_acbbdccd	status       query
/380_acbbdccd	status       finished
/380_acbbdccd	exit code: success
Transactions:
 1	/381_beababca
/381_beababca	status       setup
/381_beababca	status       loading-cache
Transactions:
 1	/381_beababca
 2	/382_eceedcbd
/382_eceedcbd	allow_cancel 1
/382_eceedcbd	percentage   -1
/382_eceedcbd	role         depends-on
/382_eceedcbd	status       wait
/381_beababca	percentage   0
/381_beababca	percentage   100
/381_beababca	percentage   0
/381_beababca	percentage   50
/381_beababca	percentage   100
/381_beababca	status       query
/381_beababca	status       finished
/381_beababca	exit code: success
Transactions:
 1	/382_eceedcbd
/382_eceedcbd	status       setup
/382_eceedcbd	status       loading-cache
Transactions:
 1	/382_eceedcbd
 2	/383_aadbbaed
/383_aadbbaed	allow_cancel 1
/383_aadbbaed	percentage   -1
/383_aadbbaed	role         depends-on
/383_aadbbaed	status       wait
/382_eceedcbd	percentage   0
/382_eceedcbd	percentage   100
/382_eceedcbd	percentage   0
/382_eceedcbd	percentage   50
/382_eceedcbd	percentage   100
/382_eceedcbd	status       query
/382_eceedcbd	status       finished
/382_eceedcbd	exit code: success
Transactions:
 1	/383_aadbbaed
/383_aadbbaed	status       setup
/383_aadbbaed	status       loading-cache
/383_aadbbaed	percentage   0
/383_aadbbaed	percentage   100
/383_aadbbaed	percentage   0
/383_aadbbaed	percentage   50
/383_aadbbaed	percentage   100
/383_aadbbaed	status       query
/383_aadbbaed	status       finished
/383_aadbbaed	exit code: success
Transactions:
 [none]

](url)

**Comment by yourpalal** [comment] 2019-04-15 15:23
This may not be the same issue, but I had the same thing happen on Pop_os. What I found was that packagekitd was repeatedly spinning up to 100% CPU. The issue in my case was that one of my apt sources had an expired key, so the apt update was failing. The store should implement an exponential fallback strategy IMO. The current strategy seems to by retrying at a fixed interval.

On a laptop, this will cause the processor to use much more power, the fan to spin, the battery to drain faster etc.

I'm guessing the place to handle this might be https://github.com/elementary/appcenter/blob/583a0e9a3d1ff3b9a0ce17469ddf67954f5cf326/src/Core/Client.vala#L135

**Comment by davidmhewitt** [comment] 2019-04-15 15:53
This is not an appcenter issue, packagekit would do this by itself without any involvement from appcenter. Sure, appcenter triggers a packagekit refresh initially, but it gets stuck in an infinite loop itself, see: https://github.com/hughsie/PackageKit/pull/295

**Comment by yourpalal** [comment] 2019-04-15 15:54
Great clarification thanks!

**Comment by DenisNovac** [comment] 2019-11-17 16:50
I had this issue when i tried Elementary first time (1.5 years ago) and for now it is still here. I am having Quad core Intel Core i5-8300H. After fresh install i tried to upgrade packages from AppCenter and my machine just freezed with cooler speed higher than in some modern games. I checked it next time and this is what i saw (insane values!):

![2019-11-17 15-58-48](https://user-images.githubusercontent.com/22966999/69010716-1fad3700-0984-11ea-9962-7aa531a03801.png)

For now i use only apt upgrade...

**Comment by davidmhewitt** [comment] 2019-11-17 17:11
@DenisNovac The version of AppCenter included in the .iso you will have used to do a fresh install of elementary will still be the same version of AppCenter that was included in the .iso 1.5 years ago so it will still have the same issue. There is a refreshed .iso coming soon.

However, there have been numerous improvements to AppCenter since then, so I'd be interested to hear if you can still reproduce this issue in the version of AppCenter that will be on your system after you've done all upgrades.

**Comment by DenisNovac** [comment] 2019-11-18 04:10
@davidmhewitt thank you for answer. I'll check it out as soon as possible.

**Comment by danrabbit** [comment] 2020-04-27 22:58
Closing since the issue wasn't reconfirmed after an update. We're tracking other CPU related issues in #1160 and there is further debugging direction there

**Closed by danrabbit** 2020-04-27 22:58 UTC
Labels: Status: Incomplete
