### ISSUE TITLE
AppCenter display number of updates in plank though there are none

### ISSUE THREAD

**Issue by jegjessing** [elementary/appcenter#420] opened 2017-07-31 18:43 UTC
I have installed all updates, but still the indicator shows that there are updates. This was a problem in the early version of Loki, but got fixed. But now it's back :-1:

**Comment by davidmhewitt** [comment] 2017-07-31 18:45
Thanks for the report. 

This is a duplicate of #390.

**Closed by davidmhewitt** 2017-07-31 18:45 UTC
