### ISSUE TITLE
Package descriptions are escaped

### ISSUE THREAD

**Issue by BWPanda** [elementary/appcenter#1354] opened 2020-06-06 12:39 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Package descriptions are being escaped, which results in `&amp;` being displayed instead of `&`.

The same bug for package names was fixed in https://github.com/elementary/appcenter/issues/1153. We just need to do the same/similar for package descriptions now.

### To Reproduce
1. Open the AppCentre
2. Search for 'multitask'
3. Click on 'Multitasking & Window Management'

### Expected behavior
Ampersands displayed properly (e.g. `&`) in description text.

### Screenshots or screen recordings

![Screenshot from 2020-06-06 22-32-21](https://user-images.githubusercontent.com/2385329/83944307-dfd96e80-a845-11ea-9fac-26f1f8ea1809.png)

![Screenshot from 2020-06-06 22-35-50](https://user-images.githubusercontent.com/2385329/83944373-5fffd400-a846-11ea-854c-deddeab1195a.png)

**Comment by Ks5810** [comment] 2020-06-25 19:46
Has this been fixed? I cannot reproduce it anymore.

**Comment by feoh** [comment] 2020-07-30 01:30
This definitely seems fixed. Resolving.

![image](https://user-images.githubusercontent.com/330070/88870174-b3f1be00-d1e2-11ea-8cf7-fd7bf6aa3fa8.png)

**Comment by feoh** [comment] 2020-07-30 01:33
This is almost definitely fixed. Looks like the original reporter needs to resolve this? What say you @BWPanda ? :)

![Screenshot of same package with no escaping](https://user-images.githubusercontent.com/330070/88870308-0632df00-d1e3-11ea-93c7-50ed7b0f909f.png)

**Comment by BWPanda** [comment] 2020-07-30 02:16
Sorry, can't test. I'm no longer using Elementary. Feel free to close if you think it's fixed.

**Closed** 2020-07-30 07:27 UTC
Labels: Bitesize
