### ISSUE TITLE
Clicking on "Application installed" notification should open the said Application

### ISSUE THREAD

**Issue by moonmehta** [elementary/appcenter#329] opened 2017-06-03 09:07 UTC
Clicking on the said notification does nothing as of now. It should open the app instead.

![screenshot from 2017-06-03 12-24-22](https://cloud.githubusercontent.com/assets/22585732/26752291/30aca8de-486a-11e7-9c02-355ef4e57acf.png)

**Comment by uncertainquark** [comment] 2019-04-17 11:48
The same applies to 3rd party apps. 

![Screenshot from 2019-04-17 17-17-36](https://user-images.githubusercontent.com/22585732/56285414-cc94ac80-6134-11e9-97ed-b2d1eb3e6ff2.png)

Seeing that the notification says "Application is ready to be used", it is confusing that upon clicking the notification, nothing happens.

**Comment by danirabbit** [comment] 2023-01-28 17:48
Closing as a duplicate of #1546

**Closed by danirabbit** 2023-01-28 17:48 UTC
Labels: Priority: Wishlist, Status: Confirmed
