### ISSUE TITLE
Uninstalled up is shown as installed

### ISSUE THREAD

**Issue by prthkms** [elementary/appcenter#436] opened 2017-08-04 06:48 UTC
I had previously installed and then removed one of the curated apps. Now I want to use the same app again but I'm stuck with this.

![screenshot from 2017-08-04 12 16 34](https://user-images.githubusercontent.com/2942624/28957256-b7d3c684-78e0-11e7-8e92-8ba464977ee2.png)

There is no response when I click `uninstall` or `open`

**Comment by davidmhewitt** [comment] 2020-04-14 16:40
I can't reproduce this, so I'll close the issue due to age.  Please re-open if anyone is still experiencing this.

**Closed by davidmhewitt** 2020-04-14 16:40 UTC
