### ISSUE TITLE
Able to select the text in creator of app

### ISSUE THREAD

**Issue by D0J0P** [elementary/appcenter#1049] opened 2019-07-26 21:52 UTC
It looks like I'm able to edit the creator of an app in AppCenter. Well, it won't actually let me edit the text, just focuses the edit cursor as if I could edit it. 
![Screenshot from 2019-07-18 18 37 53](https://user-images.githubusercontent.com/19495660/61983351-072ca180-afce-11e9-8f1a-9a1781b244fe.png)

**Comment by danrabbit** [comment] 2019-07-26 22:29
The text is intentional selectable so that it can be copied and pasted if you wish :)

Mentioning @elementary/ux but I think this can be closed as “Design Conflict” since it’s intentional behavior

**Comment by D0J0P** [comment] 2019-07-27 00:07
When you double-click it, it highlights so you can copy it. Do you think that could be the default behavior for single-click? I can definitely understand wanting to copy it, but looking like you can edit it is probably not the intended behavior.

**Comment by peteruithoven** [comment] 2019-07-27 07:55
Let's be a bit more specific. I think this editable effect is caused by the persistence of the cursor? That's the only think that's different compared to selection that we're used to in browsers?

Seeing this is apparently default behaivior for the `Gtk.Label` this is actually a GTK "issue"?

**Comment by cassidyjames** [comment] 2019-07-27 15:59
I agree it can be weird at times, but it is definitely an intended behavior, and a GTK specific implementation when making labels selectable.

**Comment by davidmhewitt** [comment] 2020-04-07 07:51
I'm going to close this since it's consistent throughout the OS and not an issue specific to AppCenter. This can be re-opened for discussion elsewhere if we feel it's an issue.

**Closed by davidmhewitt** 2020-04-07 07:51 UTC
