### ISSUE TITLE
Return button vertically misaligned?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#1035] opened 2019-07-13 21:08 UTC
Is it just me or the the return button vertically misaligned? 

<img src="https://user-images.githubusercontent.com/523210/61176508-57653600-a5c2-11e9-94ee-da9504957455.png" alt="Screenshot from 2019-07-13 22-47-19@2x" width="238" />

<img src="https://user-images.githubusercontent.com/523210/61176511-621fcb00-a5c2-11e9-87de-92ceef97aa66.png" alt="Screenshot from 2019-07-13 22-47-29@2x" width="227" />

When I give the button a 2 pixels top margin (which isn't a good fix) it looks like this:
<img src="https://user-images.githubusercontent.com/523210/61176527-8a0f2e80-a5c2-11e9-8e36-9385db5b112d.png" alt="Screenshot from 2019-07-13 23-02-23@2x" width="230" />

**Comment by lainsce** [comment] 2019-07-13 23:10
Seems that the issue is with the vertical alignment of the close button icon.

**Comment by danrabbit** [comment] 2022-05-22 00:16
Closing since this seems to be fixed in the current master

**Closed by danrabbit** 2022-05-22 00:16 UTC
