### ISSUE TITLE
Support more software

### ISSUE THREAD

**Issue by zuohuadong** [elementary/appcenter#869] opened 2018-10-22 06:05 UTC
I believe in the power of open source, but what users really want is the software itself, whether it is windows mac or chromeos: software is ecological. Although android is open source, there are a lot of non-open source software, for the user, as long as it is easy to use.
For app center, I hope to support closed source software, and have the corresponding logo, after all, for software, easy to use is enough.

Deepin has a lot of useful software.

We pay too much attention to open source and ignore the ease of use of the software itself.

**Comment by Conan-Kudo** [comment] 2018-10-22 11:51
That goes against the whole point of AppCenter and elementary OS. This project aims to find a way to help sustain open source software development.

**Comment by peteruithoven** [comment] 2018-10-22 12:03
One idea is implementing something like Snap or Flatpak support:
- https://github.com/elementary/appcenter/issues/712
- https://github.com/elementary/appcenter/issues/27

This would enable more and possibly non opensource software, so I'm closing this one as a duplicate.

**Closed by peteruithoven** 2018-10-22 12:03 UTC

**Comment by cassidyjames** [comment] 2018-10-22 16:04
As a further note, elementary does not package software for elementary OS; app developers submit their own apps. There is nothing technically preventing proprietary software from being released on AppCenter. Right now repos must be openly-readable but we make no requirements around licensing, and I am sure if a proprietary app wanted to target elementary OS, we could sort out private repo support.

**Comment by dumblob** [comment] 2018-11-21 15:52
Offtopic: What I always asked myself was how to install and run *elementary OS* applications on systems having users who are used to financially support the application providers - e.g. macOS or Windows. It might be worth consideration providing majority of *elementary OS* applications also for macOS just to raise more money (the issue is, that Apple might not allow *AppCenter* in their store thus we would be condemned to a separate ecosystem like [Homebrew](https://brew.sh/ )).

**Comment by dumblob** [comment] 2018-11-21 20:04
@cassidyjames sure, it wouldn't be for all apps, but still I would guess for the majority it would do a good job (the ones which do not need so much integration). SQL app, calculator, code editor, ... all these won't need basically any integration.

From my point of view the first question is whether it would really help funding the project or rather not. First after we answer this question, we can ask a second question - namely "how do we achieve that goal with our scarce resources?". I'm still asking just the first question :wink: (btw there might be some non-obvious surprising answers to the second question...).
