### ISSUE TITLE
Nvidia fails to install driver support (Odin)

### ISSUE THREAD

**Issue by brodock** [elementary/appcenter#1601] opened 2021-08-15 23:12 UTC
## What Happened
This is similar to https://github.com/elementary/appcenter/issues/1548. Clicking to install the driver doesnt work as expected.

One thing I noticed is that it was lacking the header (it seems we are not automatically installing `linux-headers-generic-hwe-20.04`.

When restarting it would not always boot with nvidia driver (most of the times it would default to `nouveau` which I could only fix by blacklisting.

## Expected Behavior

Should install and work as intended

## Steps to Reproduce

Install nvidia driver from the updates page in App Center, Reboot and try configure Nvidia Settings (Should get a blank page) Monitor resolution should also be incorrect (defaulting to minimal resolution / failsafe approach)

## Platform Information

* elementary OS 6 Odin (Linux 5.11.0-25-generic)
* 8× AMD Ryzen 7 3700x 8-core processor 
* NVIDIA® GeForce® GTX® 1660 SUPER

**Comment by davidmhewitt** [comment] 2021-08-16 08:38
I'm pretty sure the `linux-headers-generic-hwe-20.04` package isn't necessary for the driver to work. This would only be necessary if it was compiling the kernel modules in place. But, the `linux-modules-nvidia-470-generic-hwe-20.04` package should get installed, which adds pre-compiled modules for the correct kernel version.

I did have some issues with installing an nvidia driver on my PC, but I don't think they were caused by AppCenter, as I had the same issues when doing `sudo ubuntu-drivers autoinstall`.

My issues seemed to be solved by doing a `sudo nvidia-xconfig` and ensuring the right prime profile was selected.

I'll leave this open for now as there may be something we can do in AppCenter, but I'll continue investigating the issue.

**Comment by asonix** [comment] 2021-08-17 01:32
I got into a weird situation where nvidia drivers were installing properly for the 5.11.0-27 linux packages but grub wasn't updating to show that I could boot 5.11.0-27, it would only show 5.11.0-25. I did a `sudo grub-install` and rebooted, and my UEFI froze trying to load grub, but going into UEFI settings and manually booting "ubuntu" got me into grub where I could boot 5.11.0-27 with the nvidia driver properly loaded

I will note that part of this debugging process initially involved me running `sudo prime-select nvidia` and `sudo nvidia-xconfig` to no avail before I realized the kernel version issue, so it's possible that those commands also led me to this current working state.

**Comment by Cikappa2904** [comment] 2021-08-17 06:03
I also have this problem, installing the Nvidia drivers from the App Center (both 460 and 470) and then rebooting leads to only one monitor working at 640x480 resolution

**Comment by asonix** [comment] 2021-08-18 01:50
As an update, my computer still can't automatically load grub, but if I choose it from the boot menu it loads fine. no idea why this would be. That said, things are working fine once I boot into the OS

**Comment by asonix** [comment] 2021-08-19 15:54
As another update: it was because the default boot order preferred "UEFI OS" to "ubuntu", switching that around fixed my boot issues

**Comment by davidmhewitt** [comment] 2021-09-01 10:09
I'm going to close this issue as there were a bunch of issues in various repositories that could have caused issues with nvidia drivers, the related fixes were:

https://github.com/elementary/greeter/pull/558
https://github.com/elementary/os-patches/pull/196
https://github.com/elementary/appcenter/pull/1581

AppCenter now installs the same packages as `ubuntu-drivers` would, so any outstanding issues with nvidia drivers are unlikely to be caused by AppCenter. If you're still experiencing an issue, please open a new issue at https://github.com/elementary/triage with as many details as possible.

**Closed by davidmhewitt** 2021-09-01 10:09 UTC
