### ISSUE TITLE
Suddenly, using the same card. "Card does not support this kind of transaction"

### ISSUE THREAD

**Issue by estradanic** [elementary/appcenter#391] opened 2017-07-10 17:10 UTC
I have purchased a few apps from App Center with my Mastercard Debit card and until yesterday, hadn't run into any issues. All of a sudden though, using the same card, when I tried to purchase Quilter, it said my card didn't support that kind of transaction and to try a different card. I don't have a different card, so I can't troubleshoot that way, but I did try a different app and got the same result and I also called my bank to see if they were blocking anything and they weren't. I don't know what to do. I want to support the dev but I can't.

**Comment by tintou** [comment] 2017-07-10 17:12
Try a second time, if the card is still declined, you'll have to call your bank to know the reason, sometimes banks decline payments done in some other currency to protect its customers.

**Comment by cassidyjames** [comment] 2017-07-10 17:18
@tintou, @estradanic mentioned:

>I also called my bank to see if they were blocking anything and they weren't. 

I had the same experience with Quilter (including contacting my bank and having them tell me nothing came up on their end) and haven't tried again, but will momentarily. @btkostner are we using the "On behalf" key in Stripe yet, and if not, would doing that possibly fix this?

I'll also debug when I try again and drop the results here if it fails with the same error.

**Comment by danrabbit** [comment] 2017-07-11 04:40
This seems to actually be an issue in Houston. Closing this issue as a duplicate of https://github.com/elementary/houston/issues/483

**Closed by danrabbit** 2017-07-11 04:40 UTC
Labels: Priority: High, Status: Confirmed
