### ISSUE TITLE
AppCenter crashes with empty package cache

### ISSUE THREAD

**Issue by odin3** [elementary/appcenter#318] opened 2017-05-23 21:41 UTC
## Environment
**OS** Elementary OS 0.4.1 (Fresh)
**Environment:**
```
VMWare Workstation 12 Pro
```

## Description
Can't start AppCenter. When I'm trying to start it from terminal, I have error output:
```
** (process:8739): ERROR **: Client.vala:85: Metadata files have errors: /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-backports_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-backports_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-backports_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial_multiverse_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/security.ubuntu.com_ubuntu_dists_xenial-security_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial_universe_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial_restricted_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/ua.archive.ubuntu.com_ubuntu_dists_xenial_main_dep11_Components-amd64.yml.gz, /var/lib/app-info/yaml/packages.elementary.io_appcenter_dists_xenial_main_dep11_Components-amd64.yml.gz
Trace/breakpoint trap (core dumped)
```

**Comment by odin3** [comment] 2017-05-23 21:57
Fixed by re-installing AppCenter:
```
sudo apt-get purge appstream
sudo apt install appcenter
```

**Comment by danrabbit** [comment] 2017-05-23 22:06
Closing since OP fixed the issue by re-installing

**Comment by odin3** [comment] 2017-05-23 22:10
@danrabbit, imho stock base apps like that must work out-of-box without shell workarounds.

**Comment by purejava** [comment] 2017-05-25 16:51
This happens, when the package cache was never initiated / updated.
The issue can be reproduced on deleting the cache files with ```sudo rm -rf /var/cache/apt && sudo rm -rf /var/lib/apt``` (```sudo apt-get update``` rewrites the cache files again if needed later on).

**Comment by purejava** [comment] 2017-05-25 16:52
Here is the backtrace:
```
Thread 1 "appcenter" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff5825a5b in _g_log_abort (breakpoint=1) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gmessages.c:325
325 /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gmessages.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007ffff5825a5b in g_logv (breakpoint=1) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gmessages.c:325
#1  0x00007ffff5825a5b in g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=args@entry=0x7fffffffd490)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gmessages.c:1080
#2  0x00007ffff5825bcf in g_log (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x439256 "Client.vala:85: %s") at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gmessages.c:1119
#3  0x00000000004199cf in app_center_core_client_constructor (type=<optimized out>, n_construct_properties=<optimized out>, construct_properties=<optimized out>) at /build/appcenter-wnUWqE/appcenter-0.2.2+r644+pkg54~ubuntu0.4.1.1/src/Core/Client.vala:85
#4  0x00007ffff5afb149 in g_object_new_internal (n_params=0, params=0x0, class=0x682f20) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1699
#5  0x00007ffff5afb149 in g_object_new_internal (class=class@entry=0x682f20, params=params@entry=0x0, n_params=n_params@entry=0)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1779
#6  0x00007ffff5afcc01 in g_object_newv (object_type=object_type@entry=6827520, n_parameters=n_parameters@entry=0, parameters=parameters@entry=0x0)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1928
#7  0x00007ffff5afd534 in g_object_new (object_type=6827520, first_property_name=0x0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1621
#8  0x00007ffff5845c78 in g_once_impl (once=once@entry=0x65e250 <app_center_core_client_instance>, func=func@entry=0x419330 <___lambda4__gthread_func>, arg=arg@entry=0x0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./glib/gthread.c:604
#9  0x00000000004191ac in app_center_core_client_get_default () at /build/appcenter-wnUWqE/appcenter-0.2.2+r644+pkg54~ubuntu0.4.1.1/src/Core/Client.vala:658
#10 0x000000000041f40a in app_center_app_constructor (type=<optimized out>, n_construct_properties=<optimized out>, construct_properties=<optimized out>)
    at /build/appcenter-wnUWqE/appcenter-0.2.2+r644+pkg54~ubuntu0.4.1.1/src/Application.vala:77
#11 0x00007ffff5afb149 in g_object_new_internal (n_params=0, params=0x0, class=0x6876f0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1699
#12 0x00007ffff5afb149 in g_object_new_internal (class=class@entry=0x6876f0, params=params@entry=0x0, n_params=n_params@entry=0)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1779
#13 0x00007ffff5afcc01 in g_object_newv (object_type=object_type@entry=6827008, n_parameters=n_parameters@entry=0, parameters=parameters@entry=0x0)
    at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1928
#14 0x00007ffff5afd534 in g_object_new (object_type=6827008, first_property_name=0x0) at /build/glib2.0-ixQ1YB/glib2.0-2.48.2/./gobject/gobject.c:1621
#15 0x00007ffff7b6f10e in granite_application_construct () at /usr/lib/x86_64-linux-gnu/libgranite.so.3
#16 0x000000000041f607 in _vala_main (object_type=<optimized out>) at /build/appcenter-wnUWqE/appcenter-0.2.2+r644+pkg54~ubuntu0.4.1.1/src/Application.vala:17
#17 0x000000000041f607 in _vala_main () at /build/appcenter-wnUWqE/appcenter-0.2.2+r644+pkg54~ubuntu0.4.1.1/src/Application.vala:17
#18 0x000000000041f607 in _vala_main (args=0x7fffffffdec8, args_length1=1)
    at /build/appcenter-wnUWqE/appcenter-0.2.2+r644+pkg54~ubuntu0.4.1.1/src/Application.vala:251
#19 0x00007ffff518a830 in __libc_start_main (main=
    0x412560 <main>, argc=1, argv=0x7fffffffdec8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdeb8)
    at ../csu/libc-start.c:291
#20 0x00000000004125a9 in _start ()
(gdb) 
```

**Comment by purejava** [comment] 2017-05-25 16:53
Suprisingly this [command](https://github.com/elementary/appcenter/blob/master/src/Core/Client.vala#L85) crashes appcenter.
Replacing ```error``` with ```critical``` stops appcenter from crashing.

Does this make any sense to anybody?

**Comment by purejava** [comment] 2017-05-26 11:17
Well, after reading the docs it's not that surprising.
GLib.error terminates as described [in Valadoc](https://valadoc.org/glib-2.0/GLib.error.html) and even the short example code there writes a core dump.

To fix this appcenter issue GLib.critical can be used instead.

**Closed** 2017-05-27 16:12 UTC
