### ISSUE TITLE
immediate freeze after launch

### ISSUE THREAD

**Issue by TitanNano** [elementary/appcenter#323] opened 2017-05-27 15:21 UTC
I updated all applications to the latest version yesterday. 
After a reboot, I could launch the AppCenter, but the window freezes right away. I can move the window across the desktop but the window UI doesn't respond at all. 
Also resizing the window results in the new area of the window showing the wallpaper. If I move the resized window, the window still displays the previous area of the wallpaper.

**Comment by TitanNano** [comment] 2017-05-28 10:16
This seems to be caused due to a missing ubuntu-drivers binary. After installing ubuntu-drivers-common the appcenter started working. Please make sure you install this automatically.

**Comment by purejava** [comment] 2017-05-28 11:36
Thanks for reporting the issue.
This is a duplicate of #310 and has been fixed recently.

**Closed by purejava** 2017-05-28 11:36 UTC
Labels: Status: Duplicate
