### ISSUE TITLE
App center is showing update button without updates  available

### ISSUE THREAD

**Issue by FernandoGarcia** [elementary/appcenter#1064] opened 2019-08-21 13:34 UTC
Hi!

Using latest version available via daily ppa I have noticed right now that App center is showing update buttons even after install all packages.

The problem remains even after close the App.

![appcenter bug2](https://user-images.githubusercontent.com/2778501/63436362-edc91a80-c3fe-11e9-998f-9b8a31ae30e1.png)

![appcenter bug](https://user-images.githubusercontent.com/2778501/63436393-fd486380-c3fe-11e9-8261-3f091b0caf4f.png)

Best regards.

**Comment by davidmhewitt** [comment] 2019-11-08 00:58
A fix for this issue has been merged in #1129. When the new version of AppCenter comes out (3.2.1), we should see this issue resolved.

I'll close this issue but if you are still experiencing this issue *after* the new version of AppCenter comes out, please leave another comment.

This also appears to be a duplicate of #1001 and #1119.

**Closed by davidmhewitt** 2019-11-08 00:58 UTC
Labels: Status: Confirmed
