### ISSUE TITLE
problems with upgrade (incorrect name)

### ISSUE THREAD

**Issue by Philosoft** [elementary/appcenter#565] opened 2018-01-11 13:26 UTC
I will post it here, since I cannot find chat to ask a question or any specific place to post bugs. Sorry, if it's wrong place to post such bug, redirect me in right direction please.

### My setup

Freshly (10.01.2018) downloaded and installed elementary os. No additional PPAs. After installation my work've been:

`apt update; apt upgrade; apt install chromium-browser firefox mc pydf grc zsh git transmission; dpkg -i ~/Downloads/slack.deb ; apt install -f; apt autoremove`

So, I have pretty standard system.

### Problem

`apt update` leads to

```
--- ~ » sudo apt update                                                                                                               100 ↵
Hit:1 http://ru.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ru.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                         
Hit:3 http://ru.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                       
Ign:4 http://ppa.launchpad.net/elementary-os/stable/ubuntu loki InRelease                                                                  
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease                             
Ign:6 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu loki InRelease                      
Ign:7 http://packages.elementary.io/appcenter loki InRelease                                       
Err:8 http://ppa.launchpad.net/elementary-os/stable/ubuntu loki Release                            
  404  Not Found
Err:9 http://packages.elementary.io/appcenter loki Release
  404  Not Found [IP: 104.28.5.44 80]
Err:10 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu loki Release
  404  Not Found
Hit:11 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Reading package lists... Done 
E: The repository 'http://ppa.launchpad.net/elementary-os/stable/ubuntu loki Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://packages.elementary.io/appcenter loki Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/elementary-os/os-patches/ubuntu loki Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### My hypotesis

`cat /etc/apt/sources.list.d/elementary.list`

```
deb http://ppa.launchpad.net/elementary-os/stable/ubuntu loki main
deb-src http://ppa.launchpad.net/elementary-os/stable/ubuntu loki main
````

There should be `xenial` instead of `loki`. Same goes for
* `/etc/apt/sources.list.d/appcenter.list`
* `/etc/apt/sources.list.d/patches.list`

### Taken actions

I've done this `find /etc/apt/sources.list.d/ -type f -exec sed -i.bak -e 's/loki/xenial/' '{}' \;`
Then `apt upgrade`. Below lies output of `apt upgrade`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  indicator-bluetooth indicator-datetime indicator-keyboard indicator-power indicator-sound liburl-dispatcher1 libvala-0.34-0
  ubuntu-touch-sounds
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libvala-0.36-0
The following packages have been kept back:
  appcenter audience capnet-assist gala libgala0 libmaya-calendar0 libnoise-core0 libpantheon-files-core0 libpantheon-files-widgets0
  maya-calendar maya-calendar-daemon maya-calendar-plugin-caldav maya-calendar-plugin-google noise pantheon-calculator pantheon-files
  pantheon-greeter pantheon-mail pantheon-photos pantheon-photos-common pantheon-terminal screenshot-tool slingshot-launcher
  snap-photobooth user-specific-alternatives
The following packages will be upgraded:
  base-files bash cerbere contractor dkms elementary-icon-theme elementary-theme evince evince-common hicolor-icon-theme libevdocument3-4
  libevview3-3 libgranite-common libnm-gtk-common libnm-gtk0 libnma-common libnma0 libpantheon-online-accounts0 libscratchcore0
  libunity-control-center1 libwingpanel-2.0-0 network-manager-gnome pantheon-agent-polkit pantheon-online-accounts-plugin-fastmail
  pantheon-online-accounts-plugin-password pantheon-print scratch-text-editor switchboard-plug-about switchboard-plug-networking
  switchboard-plug-notifications switchboard-plug-online-accounts switchboard-plug-useraccounts switchboard-plug-users
  unity-control-center unity-control-center-faces wingpanel wingpanel-indicator-bluetooth wingpanel-indicator-network
38 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 13,4 MB of archives.
After this operation, 20,9 MB of additional disk space will be used.
```

Many packages with names `pantheon-*`, `switchboard-*`, `*gala*`, `*vala*` etc, lead me to think, that this is correct decision.

### Question

Is my actions from [previous section](#taken-actions) is the right ones? Am I safe to upgrade? (I think so). If that's the case - should I report it somewhere else? Make a simple PR? (cannot find related repo though)

**Comment by peteruithoven** [comment] 2018-01-11 13:36
I think the [stack exchange](https://elementaryos.stackexchange.com/) is a more appropriate place? Mostly since this is not really a bug with the appcenter and Elementary OS, it's a bug in Slack's deb. 
You'll probably get the same issue when running simply `dpkg -i ~/Downloads/slack.deb` ? 
(you could also use [Eddy](https://appcenter.elementary.io/com.github.donadigo.eddy.desktop) to more easily install debs.)

Similar issue: https://github.com/brave/browser-laptop/issues/6649

**Comment by peteruithoven** [comment] 2018-01-11 14:21
Disclaimer: I'm no expert on this. What's confusing here is that Loki is the Elementary OS version, which is build on the Xenial Ubuntu version. During the installation some thirt party packages will assume you're on a Ubuntu system, check the version, they get "loki" which they don't support. Usually you can replace that "loki" into "xenial"  during the installation of third party packages and it all works. 

I'll let other chime in on whether that issue is related or not.

**Comment by Philosoft** [comment] 2018-01-11 14:26
Point of this issue is to report that this occurs somewhere in the system with system packages, may be during installation process (since `dpkg` doesn't have record of any of affected files).

**Comment by davidmhewitt** [comment] 2018-01-11 14:27
@peteruithoven It does sound unrelated, I doubt Slack would be modifying a sources file that doesn't belong to it.

@Philosoft I notice your computer hitting some russian mirrors there. What language did you select when installing the system? And have you changed language settings at any point?

**Comment by Philosoft** [comment] 2018-01-11 14:33
@davidmhewitt 
During installation I choose english as primary language (default), russian (default again, when step with choosing layout began) as additional layout and Europe/Moscow as timezone (was default, autodetect, I guess). Region and language settings screenshot below

![screenshot from 2018-01-11 17-29-37](https://user-images.githubusercontent.com/296326/34830506-20cc4e08-f6f5-11e7-81a8-a22c715c71d2.png)

I did not choose, click or do anything here

it doesn't matter, as I see it) problem lies with elementary-ppa, which doesn't have any mirrors

**Comment by davidmhewitt** [comment] 2018-01-11 14:42
@Philosoft It may not matter but I'm just asking to see what may be different about your setup.

I have installed elementary multiple times, upgraded, installed packages (including) Slack and not seen this problem. We have occasionally seen strange unconfirmed issues with the package manager in the past when elementary has been installed in a different language.

I will try later to install elementary in a virtual machine following your steps and see if I can reproduce this.

A couple more questions:
1) Did you have an internet connection while installing?
2) Did you check the install updates/3rd party software checkboxes in the installer?
3) How soon after installing did this issue occur? Were you able to perform any updates from the elementary PPAs after installation, or were they always broken as soon as the system was installed?

**Comment by Philosoft** [comment] 2018-01-11 14:48
> Did you have an internet connection while installing?

yes

> Did you check the install updates/3rd party software checkboxes in the installer?

yes. both of them (autoupdate and install 3rd party)

> How soon after installing did this issue occur?

may be from the start. But for sure, I've noticed it today (less then 20h after installation)

> Were you able to perform any updates from the elementary PPAs after installation, or were they always broken as soon as the system was installed?

Sadly, I cannot tell this for sure. `apt update ; apt upgrade` did worked, some packages was downloaded, upgraded etc, but I did not paid enough attention to see - whether they come from PPA or not.

I was about to try and reproduce it in virtualbox, but strangely, after I launch vbox with elementary.iso attached to it all system hangs and not responding to anything (including any magic with <kbd>alt</kbd>+<kbd>sysrq</kbd>)

**Comment by davidmhewitt** [comment] 2018-01-11 14:51
Thank you for the information, I will look into this and see if I can reproduce the issue.

If possible, could you look to see if your installation log files are available in `/var/log/installer` and provide those too if they exist?

**Comment by Philosoft** [comment] 2018-01-11 14:57
[`/var/log/installer` directory](https://www.dropbox.com/s/hsgcoou7s72cup6/installer-log.tar.gz?dl=0)

**Comment by davidmhewitt** [comment] 2018-01-18 11:31
Unfortunately, I have been unable to reproduce this issue.

I will close this issue as it is not likely to be a problem with appcenter.

If you find you are able to reproduce this issue consistently, then please feel free to provide any more information that may be relevant.

Thank you again for reporting the issue, I hope any future installations of elementary go smoothly for you.

**Closed by davidmhewitt** 2018-01-18 11:31 UTC

**Comment by peteruithoven** [comment] 2018-02-04 20:11
@Philosoft sorry, I have to admit I didn't read your comments properly and thought this was another common issue. 

Why I'm commenting is that I noticed that there seem to be at least 3 questions with similar looking issues on Stack Exchange, all having the following error:
```
The repository 'http://ppa.launchpad.net/elementary-os/stable/ubuntu loki Release' does not have a Release file.
```
1. https://elementaryos.stackexchange.com/questions/14387/missing-release-files-during-apt-update
2. https://elementaryos.stackexchange.com/questions/7763/getting-errors-when-trying-to-run-sudo-apt-get-update
3. https://elementaryos.stackexchange.com/questions/13060/error-while-doing-sudo-apt-update

**Comment by Philosoft** [comment] 2018-02-05 07:21
@peteruithoven erm. first link is mine)) also none of the topics has complete answer (rather then update sources, which I did), none of them resolved, that bug you mentioned still in state `new`. So I just have opened this bug to let you know, that problem obviously exists, though not that easy to reproduce. I have no intention on forcing this issue further, now there are more annoying issues with appcenter (for sure this time, see issue 499 (not linking it here, because it's unrelated to this)), videos (issue 56) etc).

Thank you for your feedback anyway)

**Comment by 4sStylZ** [comment] 2018-03-20 13:24
I have the same issue here. 

I doesn’t have file referring to loki in my `source.list.d`
The issue is now closed, I reopen it because I don’t find the solution and can easily reproduce it : 

```
4sStylZ@bluebook:/etc/apt/sources.list.d$ sudo apt-get update
Hit:1 http://fr.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                                                                 
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                                                                                                                  
Hit:4 http://ppa.launchpad.net/benoit.pierre/plover/ubuntu xenial InRelease                                                                                                                                        
Hit:5 http://fr.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                                                                                               
Hit:6 http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial InRelease                                                                                                                                        
Ign:7 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                       
Hit:8 http://ppa.launchpad.net/fingerprint/fingerprint-gui/ubuntu xenial InRelease                                                                                                                                 
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                                                                                               
Hit:10 http://ppa.launchpad.net/gezakovacs/ppa/ubuntu xenial InRelease                                                                                   
Ign:11 http://archive.canonical.com/ubuntu loki InRelease                                                                                                            
Hit:12 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu xenial InRelease                                                                                     
Hit:13 http://linux.teamviewer.com/deb stable InRelease                                                                                                              
Ign:14 http://repo.vivaldi.com/snapshot/deb stable InRelease                                                                                                         
Hit:15 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu xenial InRelease                                                                               
Hit:16 http://linux.teamviewer.com/deb preview InRelease                                                                                  
Ign:17 http://archive.canonical.com/ubuntu loki Release                                                                                   
Hit:18 http://packages.elementary.io/appcenter xenial InRelease                               
Hit:19 https://repo.skype.com/deb stable InRelease                      
Ign:20 http://repo.vivaldi.com/stable/deb stable InRelease              
Hit:21 http://repo.vivaldi.com/snapshot/deb stable Release              
Hit:22 http://repo.vivaldi.com/stable/deb stable Release
Ign:23 http://archive.canonical.com/ubuntu loki/partner amd64 Packages
Ign:24 http://archive.canonical.com/ubuntu loki/partner i386 Packages
Ign:25 http://archive.canonical.com/ubuntu loki/partner all Packages
Hit:26 https://download.sublimetext.com apt/stable/ InRelease
Ign:27 http://archive.canonical.com/ubuntu loki/partner Translation-fr_FR
Ign:28 http://archive.canonical.com/ubuntu loki/partner Translation-fr
Ign:30 http://archive.canonical.com/ubuntu loki/partner Translation-en_US.UTF-8 git
Ign:31 http://archive.canonical.com/ubuntu loki/partner Translation-en
Ign:32 http://archive.canonical.com/ubuntu loki/partner amd64 DEP-11 Metadata
Ign:33 http://archive.canonical.com/ubuntu loki/partner DEP-11 64x64 Icons
Ign:23 http://archive.canonical.com/ubuntu loki/partner amd64 Packages
Ign:24 http://archive.canonical.com/ubuntu loki/partner i386 Packages
Ign:25 http://archive.canonical.com/ubuntu loki/partner all Packages
Ign:27 http://archive.canonical.com/ubuntu loki/partner Translation-fr_FR
Ign:28 http://archive.canonical.com/ubuntu loki/partner Translation-fr
Ign:30 http://archive.canonical.com/ubuntu loki/partner Translation-en_US.UTF-8 git
Ign:31 http://archive.canonical.com/ubuntu loki/partner Translation-en
Ign:32 http://archive.canonical.com/ubuntu loki/partner amd64 DEP-11 Metadata
Ign:33 http://archive.canonical.com/ubuntu loki/partner DEP-11 64x64 Icons
Ign:23 http://archive.canonical.com/ubuntu loki/partner amd64 Packages
Ign:24 http://archive.canonical.com/ubuntu loki/partner i386 Packages
Ign:25 http://archive.canonical.com/ubuntu loki/partner all Packages
Ign:27 http://archive.canonical.com/ubuntu loki/partner Translation-fr_FR
Ign:28 http://archive.canonical.com/ubuntu loki/partner Translation-fr
Ign:30 http://archive.canonical.com/ubuntu loki/partner Translation-en_US.UTF-8 git
Ign:31 http://archive.canonical.com/ubuntu loki/partner Translation-en
Ign:32 http://archive.canonical.com/ubuntu loki/partner amd64 DEP-11 Metadata
Ign:33 http://archive.canonical.com/ubuntu loki/partner DEP-11 64x64 Icons
Ign:23 http://archive.canonical.com/ubuntu loki/partner amd64 Packages
Ign:24 http://archive.canonical.com/ubuntu loki/partner i386 Packages
Ign:25 http://archive.canonical.com/ubuntu loki/partner all Packages
Ign:27 http://archive.canonical.com/ubuntu loki/partner Translation-fr_FR
Ign:28 http://archive.canonical.com/ubuntu loki/partner Translation-fr
Ign:30 http://archive.canonical.com/ubuntu loki/partner Translation-en_US.UTF-8 git
Ign:31 http://archive.canonical.com/ubuntu loki/partner Translation-en
Ign:32 http://archive.canonical.com/ubuntu loki/partner amd64 DEP-11 Metadata
Ign:33 http://archive.canonical.com/ubuntu loki/partner DEP-11 64x64 Icons
Ign:23 http://archive.canonical.com/ubuntu loki/partner amd64 Packages
Ign:24 http://archive.canonical.com/ubuntu loki/partner i386 Packages
Ign:25 http://archive.canonical.com/ubuntu loki/partner all Packages
Ign:27 http://archive.canonical.com/ubuntu loki/partner Translation-fr_FR
Ign:28 http://archive.canonical.com/ubuntu loki/partner Translation-fr
Ign:30 http://archive.canonical.com/ubuntu loki/partner Translation-en_US.UTF-8 git
Ign:31 http://archive.canonical.com/ubuntu loki/partner Translation-en
Ign:32 http://archive.canonical.com/ubuntu loki/partner amd64 DEP-11 Metadata
Ign:33 http://archive.canonical.com/ubuntu loki/partner DEP-11 64x64 Icons
Err:23 http://archive.canonical.com/ubuntu loki/partner amd64 Packages
  404  Not Found [IP: 91.189.91.15 80]
Ign:24 http://archive.canonical.com/ubuntu loki/partner i386 Packages
Ign:25 http://archive.canonical.com/ubuntu loki/partner all Packages
Ign:27 http://archive.canonical.com/ubuntu loki/partner Translation-fr_FR
Ign:28 http://archive.canonical.com/ubuntu loki/partner Translation-fr
Ign:30 http://archive.canonical.com/ubuntu loki/partner Translation-en_US.UTF-8 git
Ign:31 http://archive.canonical.com/ubuntu loki/partner Translation-en
Ign:32 http://archive.canonical.com/ubuntu loki/partner amd64 DEP-11 Metadata
Ign:33 http://archive.canonical.com/ubuntu loki/partner DEP-11 64x64 Icons
Reading package lists... Done
W: The repository 'http://archive.canonical.com/ubuntu loki Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://archive.canonical.com/ubuntu/dists/loki/partner/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

And my sources are : 

```
4sStylZ@bluebook:/etc/apt/sources.list.d$ grep -r loki
#nothing appear
```

```
4sStylZ@bluebook:/etc/apt/sources.list.d$ grep -r xenial
philip_scott-ubuntu-elementary-tweaks-xenial.list:deb http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu xenial main
philip_scott-ubuntu-elementary-tweaks-xenial.list:# deb-src http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu xenial main
appcenter.list:deb http://packages.elementary.io/appcenter xenial main
appcenter.list.save:deb http://packages.elementary.io/appcenter xenial main
philip_scott-ubuntu-elementary-tweaks-xenial.list.save:deb http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu xenial main
philip_scott-ubuntu-elementary-tweaks-xenial.list.save:# deb-src http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu xenial main
elementary.list.save:deb http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial main
elementary.list.save:deb-src http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial main
gezakovacs-ubuntu-ppa-xenial.list:deb http://ppa.launchpad.net/gezakovacs/ppa/ubuntu xenial main
gezakovacs-ubuntu-ppa-xenial.list:# deb-src http://ppa.launchpad.net/gezakovacs/ppa/ubuntu xenial main
benoit_pierre-ubuntu-plover-xenial.list.save:deb http://ppa.launchpad.net/benoit.pierre/plover/ubuntu xenial main
benoit_pierre-ubuntu-plover-xenial.list.save:# deb-src http://ppa.launchpad.net/benoit.pierre/plover/ubuntu xenial main
fingerprint-ubuntu-fingerprint-gui-xenial.list:deb http://ppa.launchpad.net/fingerprint/fingerprint-gui/ubuntu xenial main
fingerprint-ubuntu-fingerprint-gui-xenial.list:# deb-src http://ppa.launchpad.net/fingerprint/fingerprint-gui/ubuntu xenial main
fingerprint-ubuntu-fingerprint-gui-xenial.list:# deb-src http://ppa.launchpad.net/fingerprint/fingerprint-gui/ubuntu xenial main
elementary.list:deb http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial main
elementary.list:deb-src http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial main
benoit_pierre-ubuntu-plover-xenial.list:deb http://ppa.launchpad.net/benoit.pierre/plover/ubuntu xenial main
benoit_pierre-ubuntu-plover-xenial.list:# deb-src http://ppa.launchpad.net/benoit.pierre/plover/ubuntu xenial main
patches.list.save:deb http://ppa.launchpad.net/elementary-os/os-patches/ubuntu xenial main
patches.list.save:deb-src http://ppa.launchpad.net/elementary-os/os-patches/ubuntu xenial main
fingerprint-ubuntu-fingerprint-gui-xenial.list.save:deb http://ppa.launchpad.net/fingerprint/fingerprint-gui/ubuntu xenial main
fingerprint-ubuntu-fingerprint-gui-xenial.list.save:# deb-src http://ppa.launchpad.net/fingerprint/fingerprint-gui/ubuntu xenial main
fingerprint-ubuntu-fingerprint-gui-xenial.list.save:# deb-src http://ppa.launchpad.net/fingerprint/fingerprint-gui/ubuntu xenial main
patches.list:deb http://ppa.launchpad.net/elementary-os/os-patches/ubuntu xenial main
patches.list:deb-src http://ppa.launchpad.net/elementary-os/os-patches/ubuntu xenial main
```

**Comment by Philosoft** [comment] 2018-03-20 14:34
@4sStylZ paste your `/etc/apt/sources.list`, please

**Comment by 4sStylZ** [comment] 2018-04-10 11:55
Sorry I can’t. I have resolved my issue but I cannot remember how. I think a ppa was not reffering precisely at loki but I have deleted one row and I can now upgrade my elementary.

**Comment by chinarut** [comment] 2020-03-10 20:58
I realize this issue is already closed and because it is the same issue (just different release), I wanted to acknowledge this is still an issue with 5.1 (hera) and needed to substitute "bionic" for hera in all my source lists in /etc/apt and /etc/apt/sources.list.d

I'm not sure where to report this as this is a fresh install as of March 7, 2020.

my goal was to install the Elementary SDK (which now works)
`sudo apt install elementary-sdk
`
