### ISSUE TITLE
AppCenter and apt not finding any elementary apps.

### ISSUE THREAD

**Issue by MattDiamondd** [elementary/appcenter#988] opened 2019-04-13 09:54 UTC
When I open the elementary appcenter, no elementary specific apps appear. When I try installing elementary-sdk, it says it's unable to locate package elementary-sdk.
![Screenshot from 2019-04-13 12-47-47](https://user-images.githubusercontent.com/26790610/56077988-49e5b780-5deb-11e9-83fc-1cfe65d1ddb2.png)

**Comment by IamLizu** [comment] 2019-04-13 11:08
It is basically not showing any curated apps without the installed ones.

**Comment by peteruithoven** [comment] 2019-04-13 11:11
Did you alter the ppa's on your system?

The following will pretty print your sources:
```
grep -r --include '*.list' '^deb ' /etc/apt/ | sed -re 's/^\/etc\/apt\/sources\.list((\.d\/)?|(:)?)//' -e 's/(.*\.list):/\[\1\] /' -e 's/deb http:\/\/ppa.launchpad.net\/(.*?)\/ubuntu .*/ppa:\1/'
```

You should see something like:
```
[patches.list] ppa:elementary-os/os-patches
[elementary.list] ppa:elementary-os/stable
[appcenter.list] deb http://packages.elementary.io/appcenter bionic main
deb http://nl.archive.ubuntu.com/ubuntu/ bionic main restricted
deb http://nl.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
deb http://nl.archive.ubuntu.com/ubuntu/ bionic universe
deb http://nl.archive.ubuntu.com/ubuntu/ bionic-updates universe
deb http://nl.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://nl.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb http://nl.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
```

**Comment by IamLizu** [comment] 2019-04-13 11:16
This was altered i guess, in the process to fix this error this was messed up i guess.

**Comment by MattDiamondd** [comment] 2019-04-13 11:16
I don't have the first 3 repos/ppas

**Comment by IamLizu** [comment] 2019-04-13 11:17
You do have them, you ones comes from ro server

**Comment by IamLizu** [comment] 2019-04-13 11:17
Please execute the command that @peteruithoven said and paste the output here

**Comment by MattDiamondd** [comment] 2019-04-13 11:18
I did and this was the output https://paste.ubuntu.com/p/MFpVNYbpxJ/

**Comment by IamLizu** [comment] 2019-04-13 11:19
So, now are there those curated apps in appcenter?

**Comment by MattDiamondd** [comment] 2019-04-13 11:20
nope

**Comment by MattDiamondd** [comment] 2019-04-13 11:21
shouldn't I have those 3 lines as well: 
`[patches.list] ppa:elementary-os/os-patches
[elementary.list] ppa:elementary-os/stable
[appcenter.list] deb http://packages.elementary.io/appcenter bionic main`

**Comment by IamLizu** [comment] 2019-04-13 11:21
Yes, those are the reason. You need to add those to the sources.list

**Comment by MattDiamondd** [comment] 2019-04-13 11:22
at the beginning or at the end of the file?

**Comment by IamLizu** [comment] 2019-04-13 11:22
sudo add-apt-repository ppa:elementary-os/os-patches
sudo add-apt-repository ppa:elementary-os/stable

**Comment by MattDiamondd** [comment] 2019-04-13 11:23
okay?

**Comment by IamLizu** [comment] 2019-04-13 11:24
And execute `sudo nano /etc/apt/sources.list` to open the file and add this line `deb http://packages.elementary.io/appcenter bionic main` at the end

**Comment by MattDiamondd** [comment] 2019-04-13 11:25
finally

**Comment by IamLizu** [comment] 2019-04-13 11:26
Please, confirm, appcenter is okay? and can you install elementary-sdk ?

**Comment by MattDiamondd** [comment] 2019-04-13 11:27
yes I'm installing elementary-sdk right now and appcenter loads the curated apps. Thank you

**Comment by peteruithoven** [comment] 2019-04-13 11:27
I'm closing the issue. This isn't an issue for the AppCente, this was probably caused by user error.

Please be carefull when touching things like ppa's.

**Closed by peteruithoven** 2019-04-13 11:27 UTC
