### ISSUE TITLE
After installing a snap, when hovering over links in the installed snap-app, the default cursor icon changes into an ugly hand

### ISSUE THREAD

**Issue by Hacime** [elementary/appcenter#1425] opened 2020-10-04 19:23 UTC
Normally, when hovering over a link, the cursor changes into a black hand, which is normal.
However, when the app was installed from a snap, when hovering a link the cursor changes into an ugly hand only in that app.
I have installed the same app from snap and flathub to see that it only happens with snaps. Tried with different apps.
Also, to make sure it is an eOS problem, I have tested it in Ubuntu and after installing a snap, the hover behaviour of the cursor remains default.
See screenshot.
1st screenshot shows chromium installed from flathub.
2nd screenshot shows chromium installed from snap.
OS version: 5.1.7

![Chromium-Flatpak](https://user-images.githubusercontent.com/72276348/95025218-ab50b480-0677-11eb-807a-6c4dcd18b50b.jpg)

![Chromium-Snap](https://user-images.githubusercontent.com/72276348/95025224-b7d50d00-0677-11eb-8bb6-4afcd2326275.jpg)

**Comment by danrabbit** [comment] 2020-10-04 22:11
Since AppCenter doesn't support snaps this isn't an issue an AppCenter.

Likely the cause is an out of date version of icons in the Snap sandbox. You'll have to pursue this with the maintainers of the snap you're using

Closing as "out of scope" since this isn't an AppCenter issue

**Closed by danrabbit** 2020-10-04 22:11 UTC

**Comment by janxkoci** [comment] 2020-10-08 13:01
Also this is a limitation of Snap technology and how it handles themes. It has nothing to do with anything elementary and happens on other distros too, even vanilla Ubuntu.

**Comment by Hacime** [comment] 2020-10-08 17:22
I had tried it with ubuntu 20.04 (booted from an USB flash drive) because I wanted to see if it works normal there
before reporting it here. The cursor behavior was normal. That's why I thought that it seems to come from eOS.
I don't know why my test with ubuntu didn't show this behavior but it has shown up on your test with ubuntu.
So, I thought it's a bug.

**Comment by janxkoci** [comment] 2020-10-09 09:37
Interesting, I used 18.04 in the past and I remember having this issue e.g. in WPS office (also other theming issues). I left Ubuntu since and run only elementary OS now, so I didn't actually check, I just recalled my past experience. Sorry for that.

**Comment by Hacime** [comment] 2020-10-09 12:37
No problem, I was curious and bootet ubuntu 18.04 from an usb flash drive because I thought maybe they have fixed it in 20.04 and that's why it maybe didn't show on my test. Tested with chromium snap again.
The cursor behavior was normal on hover with 18.04 but it's okay.
I will go with flathub instead. It's also better integrated with AppCenter as well.
