### ISSUE TITLE
Flatpak components don't update through web proxy

### ISSUE THREAD

**Issue by regiqb** [elementary/appcenter#1571] opened 2021-08-05 18:10 UTC
I'm testing the elementary OS 6 beta 2 in a locked down network environment, where the connection to the internet can only be made through squid web proxy on the router. The http and https proxy are configured in the network settings panel of elementary os settings. The web browser works properly, the appcenter checks for updates properly, the apt based components update fine, but the flatpak based components fail to update.

When tested in terminal both apt and flatpak fail:
'sudo apt update' results in 'Downloading mirror file failed'
'sudo flatpak update' results in 'No such ref in remote appcenter'

**Comment by davidmhewitt** [comment] 2021-08-07 20:35
This isn't actually an issue with AppCenter, it's an issue with the settings panel itself not applying the settings into the necessary config files for flatpak and apt CLI to pick them up. There's an issue about that reported here: https://github.com/elementary/switchboard-plug-network/issues/37

I'll close this issue as a duplicate of that, but in the mean time, you should be able to configure the proxies manually if you're comfortable editing some config files, info here: https://askubuntu.com/questions/175172/how-do-i-configure-proxies-without-gui

**Closed by davidmhewitt** 2021-08-07 20:35 UTC
