### ISSUE TITLE
Supply IDs for notification categories

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1242] opened 2020-04-01 00:30 UTC
For example:

`io.elementary.appcenter.updates` for new updates
`("io.elementary.appcenter.%s").printf (app_id)` for when a specific app is installed

The goal being that when notifications are saved in the notifications indicator, they get replaced properly. We shouldn't have a bunch of "Updates available" notifications, just the latest one.

**Comment by davidmhewitt** [comment] 2020-04-07 09:49
Related: #1148

**Comment by cassidyjames** [comment] 2020-04-09 17:04
Ah, yeah gonna mark it as a duplicate of #1148 since that's effectively the same and predates it. :smile:

**Closed by cassidyjames** 2020-04-09 17:04 UTC
Labels: Status: Confirmed
