### ISSUE TITLE
Failed to fetch updates

### ISSUE THREAD

**Issue by icxz1** [elementary/appcenter#1164] opened 2019-12-28 17:06 UTC
This may have been caused by external, manually added software repositories or a corrupted sources file.
![Screenshot from 2019-12-29 00 05 51](https://user-images.githubusercontent.com/58741880/71547170-0eb60380-29cf-11ea-9f36-6b15392864eb.png)

**Comment by vikasnataraja** [comment] 2019-12-30 03:37
Had a similar issue where I couldn't uninstall an application through the AppCenter and said `"Failed to authenticate"` with that same error you're seeing. The only fix seems to be shutting it down/restarting your computer.

**Comment by cassidyjames** [comment] 2020-01-10 18:18
As an update to anyone following this issue: we're investigating this. It seems that cerbere (our daemon to start and restart shell components) is not closing cleanly, which causes issues in the session once you log out and back in.

**Comment by cassidyjames** [comment] 2020-01-10 18:19
Gonna mark this as a duplicate of #1168 since it has more details.

**Closed by cassidyjames** 2020-01-10 18:19 UTC
