### ISSUE TITLE
Crash crash from corrupt size?

### ISSUE THREAD

**Issue by kbknapp** [elementary/appcenter#947] opened 2019-01-28 21:13 UTC
I noticed AppCenter appears to crash after being open for ~45 seconds. I opened it in the terminal to see if any output could be observed and this is what I see:

```
$ io.elementary.appcenter
corrupted size vs. prev_size
[1]    27128 abort      io.elementary.appcenter
```

If there is some additional specs or logs I could provide just let me know what you need.

**Comment by jeremypw** [comment] 2019-01-29 12:07
I had sometimes noticed something similar when running appcenter from the cli (after terminating the resident process) but I have not seen any evidence of the resident process crashing.  I think it has been written with the expectation that the process does not end.

**Comment by kbknapp** [comment] 2019-01-29 14:25
To be clear, it crashes when I run it normally (from the GUI Icon). This led to *try* it from the CLI, which exhibited the same behavior and upon crashing produced that output.

**Comment by jeremypw** [comment] 2019-01-29 14:49
I do not get a crash running in cli (after terminating resident process) when carrying out no operations but I get the message 
```
:~$ io.elementary.appcenter 
malloc_consolidate(): invalid chunk size
Aborted

```
on closing the window.

I also get this message after navigating around for a bit.

Running io.elementary.appcenter -s in the cli seems stable though.

**Comment by davidmhewitt** [comment] 2019-01-29 16:38
I've been trying to trace this issue and was speaking to @tintou about it yesterday. I had tracked it to a memory management issue either in AppStream or in the way we interact with AppStream.

But weirdly, I can no longer reproduce this now.

**Comment by ron-casey** [comment] 2019-01-31 18:21
Can still reproduce, this always occurs in `syslog` at the time of the crash:
`Jan 31 13:17:25 ron-eos wingpanel[1318]: AppEntry.vala:299: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'io.elementary.appcenter' on object at path /io/elementary/appcenter
Jan 31 13:17:25 ron-eos wingpanel[1318]: message repeated 23 times: [ AppEntry.vala:299: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'io.elementary.appcenter' on object at path /io/elementary/appcenter]`

**Comment by davidmhewitt** [comment] 2020-04-09 07:55
I'm cleaning up the issue tracker and I feel it's best to close this issue as we never got the root cause and it's been a long time since we had any reports like this. Please feel free to re-open or open a new issue if it's something you're still experiencing.

**Closed by davidmhewitt** 2020-04-09 07:55 UTC
