### ISSUE TITLE
Phantom update notification.

### ISSUE THREAD

**Issue by Riverwolf0222** [elementary/appcenter#1236] opened 2020-03-26 17:41 UTC
The App Center has been sending a notification that there is an update available.
There is an indicator that there is an update on the icon in task bar.
But when I open the App Center there is no update available.
I am not sure if this is a software issue, or if the App Center is picking up that a non-curated application has an updated version and just not able to complete the update itself? If that is the case it would be nice if there was some way to note this so the user could manually do the update themselves.
Thank You.

**Comment by davidmhewitt** [comment] 2020-04-06 13:53
Thanks for the report, however, this seems to be a duplicate of #1193 , I'll close this issue.

**Closed by davidmhewitt** 2020-04-06 13:53 UTC
