### ISSUE TITLE
can not change period for update

### ISSUE THREAD

**Issue by axel-n** [elementary/appcenter#1297] opened 2020-05-03 13:01 UTC
how to change the period check for updates? 
i received notification for updates every day and want to change it

for example, I can change it in ubuntu (automatic check updates)
![image](https://user-images.githubusercontent.com/6695246/80914881-30e1d880-8d57-11ea-8885-5bbf54f32bdd.png)

**Comment by cassidyjames** [comment] 2020-05-03 17:30
Duplicate of #1237

**Closed** 2020-05-03 17:30 UTC
Labels: Status: Duplicate
