### ISSUE TITLE
Cache Screenshots, Highlights, Trending, Recently Updated

### ISSUE THREAD

**Issue by eljefuri** [elementary/appcenter#911] opened 2018-11-08 12:51 UTC
Not sure what happened to #627 but I would include a lot more cached data to make AppCenter feel a bit nicer and faster. Why not update and re-display that data only if it has been updated? Does it really change so often that it needs to be loaded again every time? In the absence of update-only-when-updated, perhaps this could also have some kind of reasonable if-opened-again-within-x-minutes cache.

**Comment by peteruithoven** [comment] 2018-11-08 12:55
Screenshots should already be cached: https://github.com/elementary/appcenter/pull/812 since AppCenter 3.0: 
https://github.com/elementary/appcenter/issues?q=is%3Aclosed+milestone%3A3.0

**Comment by eljefuri** [comment] 2018-11-08 13:04
I have 3.01+r1443+pkg75~ubuntu5.0.1 and they do not appear to be caching.

**Comment by davidmhewitt** [comment] 2018-11-20 10:54
I can confirm that screenshots are caching in my install of AppCenter. If you wish to confirm this with your install, you can kill the running instance of AppCenter and then run with debug messages with:

```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

When visiting an apps page for the first time, you will see messages stating that screenshots are being downloaded. When visiting the same page again, even after restarting AppCenter, screenshots are loaded from disk and these messages do not appear. If caching is not working on your computer, please re-open this issue.

The other part of your issue report, referring to caching banners and trending etc is a duplicate report of #210 so I'll close this issue so there's not too much crossover.

**Closed by davidmhewitt** 2018-11-20 10:54 UTC
