### ISSUE TITLE
'packages.elementary.io/appcenter xenial Release' does not have a Release file

### ISSUE THREAD

**Issue by LievenHanssen** [elementary/appcenter#393] opened 2017-07-10 19:53 UTC
When I was updating App Center I got the following error:

    E: De pakketbron 'http://packages.elementary.io/appcenter xenial Release' heeft geen Release-bestand.
    N: Bijwerken van de pakketlijst uit een dergelijke pakketbron kan niet veilig gebeuren en is daarom standaard uitgezet.
    N: Zie de man-pagina apt-secure(8) voor details over het aanmaken van een pakketbron en over de configuratie langs gebruikerskant.
Roughly translated it says that: 

 - E: the named package-source has no Release-file
 - N: updating from such a package list can't be done safely and therefore is turned off by default. 
 - N: See the man-page apt-secure(8) for details on making and configuring the package source as a user.

**Comment by btkostner** [comment] 2017-07-10 20:17
Can you check again please

**Comment by KudosAbhay** [comment] 2017-07-18 04:18
Hi. This issue is still not fixed if I am not wrong, as I am getting the same since last 4 months on my laptop. Along with this error, I face the following errors past 4 months as well:

N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://archive.getdeb.net/ubuntu xenial-getdeb Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://packages.elementary.io/appcenter/dists/xenial/main/binary-i386/Packages  403  Forbidden [IP: 104.28.4.44 80]
E: Failed to fetch http://screenshots.getdeb.net/dists/xenial-getdeb/apps/binary-amd64/Packages  403  Forbidden [IP: 104.28.25.125 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

Can you help me fix this too?


Thanks.

**Comment by btkostner** [comment] 2017-07-18 04:50
Looks like the error you are having relates to the `http://archive.getdeb.net/ubuntu` repo. We do not maintain that repository so we can not do anything about that error. You should try contacting the maintainer of that repository and report the issue to them.

**Comment by btkostner** [comment] 2017-07-18 04:52
Closing this issue. Feel free to re-open LievenHanssen if they issue still exists. I have a feeling it was caused by trying to update when the repo was updating.

**Closed by btkostner** 2017-07-18 04:52 UTC
Labels: Status: Incomplete
