### ISSUE TITLE
AppCenter app caching?

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/appcenter#920] opened 2018-11-20 01:06 UTC
I noticed the AppCenter refresh application list everytime it was relaunched so I came up with this idea: why dont we cache the app info and schedule the update? This way the AppCenter doesnt have to update app list on every launch.

**Comment by davidmhewitt** [comment] 2018-11-20 11:01
Hi,

Thank you for opening an issue about this.

I think this is a duplicate of either #210 or #16 ? I'll close this issue so we don't have too many overlapping issues, but if you have a different feature request to what those issues describe, please re-open this issue and add more detail that describes exactly which part of the AppCenter application lists need caching.

**Closed by davidmhewitt** 2018-11-20 11:01 UTC
