### ISSUE TITLE
[ Home | Updates ] tabs can be unselected

### ISSUE THREAD

**Issue by shroudedcode** [elementary/appcenter#496] opened 2017-10-07 09:19 UTC
![image](https://user-images.githubusercontent.com/29176678/31306460-d61483b6-ab50-11e7-8cd7-d8bb7658021b.png)

This can be easily reproduced by clicking on the currently active tab. It will then be unselected and longer shows the current state.

**Comment by lainsce** [comment] 2017-10-07 15:36
Isn't this a duplicate of #491?

**Closed** 2017-10-07 15:50 UTC
Labels: Status: Duplicate
