### ISSUE TITLE
[$50] Blurry icons in banners/headings

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#161] opened 2017-03-24 17:03 UTC
It looks like any time an app icon is in a banner or heading, it's blurry. This is not an issue with the fallback AppCenter banner for the home view.

![screenshot of home](https://cloud.githubusercontent.com/assets/611168/24305086/6215915e-1081-11e7-9ea2-ed58377bd08d.png)

![screenshot of app info view](https://cloud.githubusercontent.com/assets/611168/24305111/7060e09c-1081-11e7-83b7-9f386eeb7715.png)

**Comment by Philip-Scott** [comment] 2017-03-24 17:26
I don't have a bigger icon on spice-up though, so it might be my fault...

**Comment by danrabbit** [comment] 2017-03-24 19:30
It still shouldn't be pixelated. This means that somewhere along the line the icon is getting rendered prematurely.

**Comment by danrabbit** [comment] 2017-03-24 19:30
It still shouldn't be pixelated. This means that somewhere along the line the icon is getting rendered prematurely.

**Comment by cassidyjames** [comment] 2017-03-24 19:31
Yup, sorry, I could have been more specific. It looks like it's rendering the smaller icon at the smaller size, _then_ scaling up instead of rendering the smaller icon crisply at the larger size. @danrabbit knows what's up.

**Comment by codygarver** [comment] 2017-03-25 01:01
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/43406937-blurry-icons-in-banners-headings).

**Comment by donadigo** [comment] 2017-03-25 14:12
Both of the Vocal and Spice-Up icons are PNGs in the appstream data (at least on my system) so there is no way they can be scaled up and look as a 128px icons. Also, currently appstream sees only one 64px icon for both of these apps.

**Comment by danrabbit** [comment] 2017-03-25 15:14
Hm yeah that would indeed be rendering the icon pretty early 😝

**Comment by danrabbit** [comment] 2017-03-26 17:15
It looks like all of the icons in `/usr/share/app-info/icons/elementary-xenial-main/` are 64px PNGs, even for apps I know don't supply a PNG icon. This might be a problem in the appstream generator itself.

**Comment by danrabbit** [comment] 2017-03-26 18:16
Confirmed with Matthias that this is an issue in appstream generator itself.

We have another issue though which is that we're currently commented the "hidpi" (actually 128px) icons in apt.conf. This was due to an Ubuntu server error that AFAIK is resolved. I've pinged @codygarver in Slack about uncommenting this in our apt.conf which would at least resolve the issue for LoDPI

**Comment by danrabbit** [comment] 2017-03-27 18:50
I'm going to close this issue for AppCenter since it is out of our control here

**Closed by danrabbit** 2017-03-27 18:50 UTC
Labels: Bounty, Priority: Medium, Status: Confirmed

**Comment by cassidyjames** [comment] 2017-05-04 14:44
@danrabbit do you know where to track this upstream?

**Comment by danrabbit** [comment] 2017-05-04 15:03
@cassidyjames I'm not sure, you'd have to ask @ximion

**Comment by tintou** [comment] 2017-05-04 16:34
It's now fixed upstream with latest AppStream
