### ISSUE TITLE
AppCenter dock icon on updates shows 0

### ISSUE THREAD

**Issue by ghabit** [elementary/appcenter#1175] opened 2020-01-11 09:52 UTC
AppCenter icon on dock always shows "0" updates independ of quantity of updates
![Снимок экрана от 2020-01-11 12 51 32](https://user-images.githubusercontent.com/70936/72202497-401fdc00-3471-11ea-9535-f7417dfd0ccc.png)

**Comment by ryonakano** [comment] 2020-01-15 10:33
Thanks for reporting, but I'll close this as a duplicate of #1136 because that one was filed earlier than this one.

**Closed by ryonakano** 2020-01-15 10:33 UTC
