### ISSUE TITLE
Broadcom drivers not beeing installed

### ISSUE THREAD

**Issue by marcelovbcfilho** [elementary/appcenter#1588] opened 2021-08-11 23:07 UTC
## What Happened

I own a macbook pro 2011 with a Broadcom wifi card, so I need a third party driver to it, at the AppCenter the drivers is being displayed, so I clicked to install and after the install process restarted the computer, but the driver wasn’n being loaded, so I can’t connect my notebook to the internet.
Image 1: Showing that the driver is installed and the system hardware info
![Screenshot from 2021-08-11 23 01 57](https://user-images.githubusercontent.com/51462138/129114925-a3f7947a-bc35-42fa-8ae6-a36f3093b5cf.png)

Image 2: Showing that the wifi isn't available
![Screenshot from 2021-08-11 23 02 34](https://user-images.githubusercontent.com/51462138/129114953-328a2453-f5df-476f-a248-0f2cb50092d2.png)

## Expected Behavior

After the driver is installed and the computer restarted the wifi should be available to be used.

## Steps to Reproduce

1. Install Elementary OS 6 on a macbook pro 2011
2. After boot try to install the AppCenter listed third party driver
3. Restart the computer

### Logs

Don't know what kind of log is applicable in this case

## Platform Information

Elementary OS 6 stable release.

**Comment by davidmhewitt** [comment] 2021-08-18 10:06
Thanks for the report!

I'm going to close this as a duplicate of #1603 . There is a workaround in that post that should help.

**Closed by davidmhewitt** 2021-08-18 10:06 UTC
