### ISSUE TITLE
Appcenter just as a Flatpak- frontend?

### ISSUE THREAD

**Issue by slackernetuk** [elementary/appcenter#1799] opened 2021-12-29 20:55 UTC
### Problem

I've been establishing Pantheon desktop on Slackware 15, almost everything is working, but I am struggling with the Appcenter.

The Appcenter is working, but Packagekit- slack/katja- frontend just support single regex to blacklist 3rd party packages and it makes the update/upgrade- process difficult.

### Proposal

My idea is to build/install the Appcenter just as a Flatpak- frontend. 

Is that already possible? If yes, how do I have to proceed?

**Comment by cassidyjames** [comment] 2022-01-01 04:27
I think this is a duplicate of #1076. If not, we can reopen.

**Closed** 2022-01-01 04:27 UTC
