### ISSUE TITLE
Operating System update failed

### ISSUE THREAD

**Issue by dewongway** [elementary/appcenter#1549] opened 2021-06-21 14:39 UTC
## What Happened

When updating the operating system in appcenter, I'm getting this error:

io.elementary.a[496358]: Package.vala:549: Operation failed for package Operating System Updates - The following packages have unmet dependencies:#012  pantheon-online-accounts-plugin-lastfm: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r79+pkg65~daily~ubuntu6.1 is to be installed#012  pantheon-online-accounts-plugin-fastmail: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r79+pkg65~daily~ubuntu6.1 is to be installed#012  pantheon-online-accounts-plugin-mail: Depends: switchboard-plug-online-accounts (= 2.0.1+r925+pkg63~daily~ubuntu6.1) but 3.0.0+r79+pkg65~daily~ubuntu6.1 is to be installed

## Steps to Reproduce
1. Go to AppCenter
2. Go to Installed tab
3. Click Update on Operating System Updates

 ## Platform Information
Running in VM on Ovirt Version 4.4.2.6-1.el8
elementary OS 6 Early Access
Built on Ubuntu 20.04.1 LTS
Linux 5.8.0-53-generic

**Comment by cassidyjames** [comment] 2021-06-21 16:29
This is a duplicate of https://github.com/elementary/appcenter/issues/1540

**Closed by cassidyjames** 2021-06-21 16:29 UTC
