### ISSUE TITLE
Need an ability to control update checking schedule

### ISSUE THREAD

**Issue by uncertainquark** [elementary/appcenter#1258] opened 2020-04-09 16:25 UTC
## Feature
**Is your feature request related to a problem? Please describe.**
Every time I boot my computer, AppCenter shows a notification and stays in the Dock. Now I know this is completely intended behaviour. But the problem is it does this way too often and while I can turn off AppCenter notifications, I can't even remove the icon from the dock. It is irritating for various reasons:
1. I don't want to update right after I boot my computer, I want to work.
2. I don't want to keep updating every time there's like one or two updates or just a few MB worth of it. It's better to update more things once than many small things multiple times.

**Describe the solution you'd like**

An ability to set an update checking schedule. Say Daily/Weekly/Bi-weekly.

**Existing work**

Ubuntu's "Software & updates" package does that and it's great. It also handle installing security updates automatically in the background.

**Comment by cassidyjames** [comment] 2020-04-09 16:38
I think this is a duplicate of #1237 and I have the same concerns/solution as laid out there. We don't want to arbitrarily hold back fixes, features, etc. from users just… because. If there are concerns about bandwidth, we can tap into the new Metered Data connection type in Network Manager. If it's about AppCenter annoying you with updates, we should be able to turn off dock badges for apps.

**Closed by cassidyjames** 2020-04-09 16:38 UTC

**Comment by uncertainquark** [comment] 2020-04-10 04:31
Hey, that report #1237 is closed by the user. Keep one of the two open?

**Comment by cassidyjames** [comment] 2020-04-10 20:43
We opened more specific issues on the dock and notification settings. But I am still not convinced user-togglable settings for when to check for updates is the right option. This isn't something I see on other major OSes, and it sounds like working around the actual issue of not wanting to be bothered by the update notification (which notification settings would solve).
