### ISSUE TITLE
Problem with German translation of the app name of "AppCenter"

### ISSUE THREAD

**Issue by ralxxx** [elementary/appcenter#1413] opened 2020-09-24 12:33 UTC
For the moment AppCenter in German verison of eOS (5.1.7) is called  "AppCenter zum Übersetzungskatalog hinzufügen" (AppCenter - to be added to the translation catalogue). 

I suppose the name was introduced like this rather as some kind of accident. Would be good if it could be renamed once more in just "AppCenter".  

![AppCenter-screenshot-German](https://user-images.githubusercontent.com/36100882/94145201-74f28880-fe72-11ea-97f9-e93a1c499da5.png)

**Comment by davidmhewitt** [comment] 2020-09-24 12:35
Hi, thanks for the report!

This is a duplicate of #1395 

This has already been resolved and will be released in the next update of AppCenter.

Thanks,
David

**Closed by davidmhewitt** 2020-09-24 12:35 UTC
