### ISSUE TITLE
Polkit auth dialog never appears

### ISSUE THREAD

**Issue by matzipan** [elementary/appcenter#221] opened 2017-04-08 16:40 UTC
When I try to install Spice-Up, I get the following error:
```
[WARNING 17:39:38.282728] Package.vala:197: Operation failed for package Spice-Up - Failed to obtain authentication.
```

**Comment by danrabbit** [comment] 2017-04-08 18:07
I can't confirm this issue. Can you provide more information? Did you see a polkit auth dialog? Can you reproduce this with other apps from the AppCenter repo (like vocal)? Can you reproduce this with apps outside the AppCenter repo? Anything that might help reproduce this issue?

**Comment by matzipan** [comment] 2017-04-08 18:34
I did not see any polkit auth dialog. I can reproduce it with any app (including updates). I can reproduce it with VLC as well. 

The only thing that I did unusual lately was when I added the AppCenter repo, I first did add-apt-repository, and only after that did I add the key. But I don't see how that would affect anything.

**Comment by danrabbit** [comment] 2017-04-08 18:42
Can you get polkit dialogs from any other app? For example, user account settings? This might just be a problem with your installation

**Comment by matzipan** [comment] 2017-04-09 10:21
It appears not. Hm... this is odd.

**Comment by matzipan** [comment] 2017-04-09 10:22
```
matzipan@matzipan-thinkpad:~/Downloads$ sudo apt install pantheon-agent-polkit 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pantheon-agent-polkit is already the newest version (0.1.2+r75+pkg7~daily~ubuntu0.4.1).
```

**Comment by danrabbit** [comment] 2017-04-09 15:48
Alright. Closing this since it's a problem with your installation and not with AppCenter :p

**Closed by danrabbit** 2017-04-09 15:48 UTC
Labels: Status: Incomplete
