### ISSUE TITLE
Searching for "spice" or "spice-up" doesn't yield Spice-Up in the search results

### ISSUE THREAD

**Issue by matzipan** [elementary/appcenter#223] opened 2017-04-08 16:40 UTC
As described in title, unsure whether this is an issue with AppCenter or my setup because of #221

**Comment by cassidyjames** [comment] 2017-04-08 16:41
Whoops, looks like I was a bit faster on the draw there. :joy: Dupe of #222.

**Closed by cassidyjames** 2017-04-08 16:41 UTC
