### ISSUE TITLE
Duplicate App entry in appcenter.

### ISSUE THREAD

**Issue by harisvsulaiman** [elementary/appcenter#564] opened 2018-01-10 13:24 UTC
Hi,
I have a duplicate entry of an app in my appcenter, one free and the other with a suggested price.

I have attached Screenshots.
![image](https://user-images.githubusercontent.com/29329325/34774974-7e6d4cba-f637-11e7-8012-54725d3c07e9.png)

![image](https://user-images.githubusercontent.com/29329325/34774989-8d482098-f637-11e7-874e-c97d2d4ba00c.png)

![image](https://user-images.githubusercontent.com/29329325/34774999-9a399e3a-f637-11e7-97af-e7878cfd1e6f.png)

**Comment by fabianthoma** [comment] 2018-01-11 19:00
This is a duplicate of elementary/houston#576

**Closed by fabianthoma** 2018-01-11 19:00 UTC
