### ISSUE TITLE
No Thumbnails

### ISSUE THREAD

**Issue by hohmal** [elementary/appcenter#1211] opened 2020-02-16 12:16 UTC
The appcenter does not display thumbnails. Heavy load on the main memory.

**Comment by davidmhewitt** [comment] 2020-04-07 07:54
Can you please provide more information or a screenshot?

What do you mean by thumbnails? Screnshots? Icons? All applications or just flatpak applications?

**Comment by davidmhewitt** [comment] 2020-04-14 15:57
I'm going to close this issue as it's not clear what the issue is and we haven't yet received any further information.

OP, if you provide some more details, I'll be happy to re-open the issue and discuss.

**Closed by davidmhewitt** 2020-04-14 15:57 UTC
Labels: Status: Incomplete

**Comment by hohmal** [comment] 2020-04-15 10:42
The screenshots do not load. The appcenter needs 399MB of RAM. It doesn't matter if they are flatpak apps or other programs.

![grafik](https://user-images.githubusercontent.com/61112031/79328299-1534a080-7f16-11ea-8310-9ecefb0c684b.png)

**Comment by davidmhewitt** [comment] 2020-04-15 10:50
Can you check the permissions on `~/.cache/io.elementary.appcenter` by running the command:

`ls -la ~/.cache/io.elementary.appcenter`

This folder, the screenshots folder and its contents, and the `~/.cache` folder itself should be owned by your user and be writable by your user. Post the output of the command if you'd like me to check that's the case.

If the permissions look correct, please can you run AppCenter with some debug output turned on with the following commands in the terminal:
```
killall io.elementary.appcenter
G_MESSAGES_DEBUG=all io.elementary.appcenter
```

If you then go to an app page to reproduce the issue and paste the output from the terminal, we can see if there's anything in the logs.

**Comment by hohmal** [comment] 2020-04-15 11:09
> XXXXX@XXXXXXXX:~$ ls -la ~/.cache/io.elementary.appcenter
insgesamt 36
drwxr-xr-x  4 XXXXX XXXXX  4096 Nov  3 15:05 .
drwxrwxr-x 46 XXXXX XXXXX  4096 Apr 15 13:00 ..
drwxr-xr-x  3 XXXXX XXXXX  4096 Apr 15 12:58 flatpak-metadata
drwxr-xr-x  2 XXXXX XXXXX 20480 Apr 15 12:58 screenshots

XXXXX --> is my Username

**Comment by davidmhewitt** [comment] 2020-04-15 11:16
The permissions look OK, perhaps you could run the other commands above to get some debug logs and see if there are any messages there while it's trying to load screenshots?

**Comment by hohmal** [comment] 2020-04-15 11:28
After I run "killall io.elementary.appcenter" it works!

Thank you!!!

**Comment by hohmal** [comment] 2020-04-19 10:39
the problem has reappeared. I carried out the order you gave me. The following warning is displayed. 

> (io.elementary.appcenter:7184): Gtk-WARNING **: 12:33:45.185: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17
