### ISSUE TITLE
AppCenter is using a lot of memory

### ISSUE THREAD

**Issue by Nomadjackalope** [elementary/appcenter#494] opened 2017-10-03 17:51 UTC
AppCenter is using around 500mb of ram. It is not open, nor is it updating. Opening then closing it adds around 15mb each time.

**Comment by Extravert-ir** [comment] 2017-10-29 22:57
Same issue. When running machine for about a week without restart, appcenter uses 1.5 GiB of memory. Seems like there is a memory leak when checking for updates

**Comment by Philip-Scott** [comment] 2017-11-09 15:14
Can confirm that there's a memory leak somewhere. This is the usage after 4 days of uptime:

![image](https://user-images.githubusercontent.com/10786508/32612580-3f174956-c52e-11e7-9044-95c26a8c8d3e.png)

**Comment by v01d** [comment] 2018-02-24 01:16
I'm seeing this as well

**Comment by Episodio1** [comment] 2018-06-06 10:33
Here suffering the same with appcenter.
After 2 weeks usage: 40% used of 16 GB RAM.
Can I restart appcenter someway?

**Comment by mmstick** [comment] 2018-09-21 22:12
Just a question, but did any of you actively use the app center during that time? Or was this purely from running in the background, without ever opening it?

**Comment by bumbar1** [comment] 2018-10-01 16:37
Also experiencing this in 0.4.1. I use it to install updates and then close. I do however have (sound) system settings open/minimized (to switch between audio outputs); might that be part of the problem?

**Comment by janxkoci** [comment] 2020-11-02 09:43
I see this too, but it seems to be smart about the memory usage (so maybe it's not a "leak"?).

My typical usage of AppCenter is: computer uptime counts in days (a week or two at most); during this time the AppCenter is mostly in the background, opened only to install updates (after it notifies me) or install occasional app.

I have two machines with different specs:

- an **ultrabook** with **8 GB** of RAM
   - On the **ultrabook**, the AppCenter can consume up to **1.3 GB** of memory.
- a **netbook** with **2 GB** of RAM
   - On the **netbook**, the AppCenter only consumes up to **0.3 - 0.4 GB** of memory.

So the AppCenter seem to know how much memory it has available and limits it's memory usage accordingly.

Killing AppCenter and relaunching it shows significant decrease in RAM usage. I killed it now on the ultrabook and it went from 1.3 GB to 137 MB after relaunch, and then grew to 283 MB after a minute. From the timing it seems the small increase after relaunch was caused by checking for updates, and not by loading the trending apps (they loaded much faster and were done before the increase happened, but I was alt-tabbing, so I don't know for sure).

**Comment by cassidyjames** [comment] 2021-02-10 19:25
Yeah, and there have been several memory consumption related improvements to AppCenter since this issue was opened, including at least:

- https://github.com/elementary/appcenter/pull/846
- https://github.com/elementary/appcenter/pull/966

…plus likely many more as significant parts of AppCenter have been refactored and improved. I'm inclined to close this, but new issues can be opened for more specific issues in the future.

**Closed by cassidyjames** 2021-02-10 19:25 UTC
Labels: Priority: High, Status: Confirmed

**Comment by janxkoci** [comment] 2021-02-12 12:07
@cassidyjames just FYI my current uptime is 11 days and AppCenter consumes 1.3 GB on my system (it's yet another laptop, I bought Slimbook with elementaryOS preinstalled recently).

**Comment by bab5470** [comment] 2021-07-02 13:31
I run elementary OS in a VM with relatively little RAM (4GB) and for me io.elementary.appcenter has eaten through nearly half a gig of ram after the system has only been up for 22 hours. This app is actually consuming more memory than any other process on my system and I haven't even checked for updates. I don't know what other information would help to troubleshoot this.
