### ISSUE TITLE
Installation of Nvidia drivers fails silently

### ISSUE THREAD

**Issue by moonlitpath** [elementary/appcenter#2216] opened 2024-10-31 07:04 UTC
### What Happened?

When trying to install an Nvidia driver (nvidia-driver-550 in my case), installation fails with no error message. The "free" button disappears, so it looks like the driver was successfully installed, which is not true. After restarting AppCenter, the "free" button is back there again.

I don't know if it's relevant, but I chose to install proprietary drivers during installation of elementary. Nvidia driver wasn't installed after rebooting, however.

### Steps to Reproduce

1. Go to Updates section of AppCenter
2. Click "free" on nvidia-driver-550
3. Restart your PC, check that Nvidia driver wasn't installed

### Expected Behavior

Installation of Nvidia driver shouldn't fail. But if anything goes wrong, AppCenter should let the user know what happened.

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
https://gist.github.com/moonlitpath/fc2fc3f577e825861c8087649013506c
```

**Comment by danirabbit** [comment] 2024-11-04 20:04
Drivers are no longer handled in AppCenter in OS 8, so moving to System Settings but also closing as incomplete since there's a whole new drivers mechanism. If you can still reproduce this issue in OS 8 please feel free to reopen!

**Closed by danirabbit** 2024-11-04 20:04 UTC
