### ISSUE TITLE
Display (default) app permissions in appcenter for flatpaks

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/appcenter#2032] opened 2023-05-08 15:06 UTC
### Problem

When installing an app you really don't know what permissions the app requires until you install it and go to system settings

### Proposal

A UX mockup will be needed

**Comment by danirabbit** [comment] 2023-05-08 15:07
Thanks for your issue report! Closing this as a duplicate of https://github.com/elementary/appcenter/issues/1012

**Closed by danirabbit** 2023-05-08 15:07 UTC
