### ISSUE TITLE
Support donation URLs for non-curated apps

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1516] opened 2021-04-08 20:56 UTC
## Problem

Non-curated apps, e.g. those from Flathub, can use the [AppStream `donation` URL type](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#id-1.3.6.4.3.8.2.2.5) to link to a website that lets users contribute to the app financially. We don't currently support this URL type in AppCenter.

## Proposal

For curated apps, we of course prefer apps to use the built-in payment system for a much better user experience. However, for non-curated apps (or all apps when payments are turned off in build flags), we could support showing a "Fund" button in the footer if the relevant AppStream data exists. This would also be beneficial to downstreams like Pop!_OS or anyone else shipping the AppCenter client.

## Prior Art

GNOME Software and KDE Discover both display this link as a "donation" button.

**Comment by danirabbit** [comment] 2022-12-27 23:19
Duplicate of #1134

**Closed by danirabbit** 2022-12-27 23:19 UTC
Labels: Priority: Wishlist, Needs Design
