### ISSUE TITLE
Formatting broken on Update Screen

### ISSUE THREAD

**Issue by glennsheff** [elementary/appcenter#1196] opened 2020-02-05 12:40 UTC
During updates in appcenter it appears the & symbol is incorrectly formatted, thus showing &amp; instead of & symbol. Screenshot attached showing the error with Date & Time indicator and Mouse & Touchpad settings.

I did do a quick search and could not find an open issue towards this, but apologies if this is in the wrong place or replicated elsewhere. 

![Screenshot from 2020-02-05 12 23 33](https://user-images.githubusercontent.com/50517583/73842327-4311b080-4814-11ea-8210-809365387a6f.png)

**Comment by davidmhewitt** [comment] 2020-02-06 17:11
Thanks for the report!

However, this is a duplicate of https://github.com/elementary/appcenter/issues/1153.

You'll have had trouble finding it because it's closed due to the fact a fix has been applied. But the update hasn't been pushed out to users yet.

**Closed by davidmhewitt** 2020-02-06 17:11 UTC
