### ISSUE TITLE
app center error

### ISSUE THREAD

**Issue by angelilarde2** [elementary/appcenter#1171] opened 2020-01-06 01:28 UTC
i recently see this error when i open the app center this error it still showing after i update the app how to fix this this is the error

Failed to obtain authentication
![Screenshot from 2020-01-06 09-22-57](https://user-images.githubusercontent.com/59545597/71789563-b9c95b80-3066-11ea-8fcd-817a8c361eeb.png)

**Comment by angelilarde2** [comment] 2020-01-06 01:29
hope you see this

**Comment by tintou** [comment] 2020-01-06 08:46
You seem to have an highly customized elementary OS desktop, do you have added some PPA or non-default repository to your installation. Finally, you might have more hint of what's happening by running `sudo apt update` on a terminal.

**Comment by angelilarde2** [comment] 2020-01-06 12:27
> You seem to have an highly customized elementary OS desktop, do you have added some PPA or non-default repository to your installation. Finally, you might have more hint of what's happening by running `sudo apt update` on a terminal.

yes plank theme and also gtweaks

**Comment by cassidyjames** [comment] 2020-01-10 18:20
Duplicate of #1168

**Closed by cassidyjames** 2020-01-10 18:20 UTC
