### ISSUE TITLE
AppCenter shows old app version, screenshots and description

### ISSUE THREAD

**Issue by artemanufrij** [elementary/appcenter#525] opened 2017-11-04 20:04 UTC
Tested on 4 devices.

![bildschirmfoto von 2017-11-04 18 50 07](https://user-images.githubusercontent.com/16517095/32409024-d9337fc0-c1a3-11e7-95e4-c65dc92c003e.png)

**Comment by danrabbit** [comment] 2017-11-04 21:43
![screenshot from 2017-11-04 14 42 51](https://user-images.githubusercontent.com/7277719/32409733-767eca72-c16e-11e7-988b-fcf5a8ebdd6f.png)

Probably just hasn't fetched updates yet on those devices. If you force it to update manually (kill the client, apt update) then it shows

**Comment by artemanufrij** [comment] 2017-11-04 21:47
@danrabbit I restarted all devices...

**Comment by Philip-Scott** [comment] 2018-01-24 13:48
Re-opening the issue because it's been confirmed in Slack, and you shouldn't need to kill the app to see the newest updates

**Comment by J0Ar** [comment] 2018-12-28 21:51
Its still an issue...for example with Files. 
![bildschirmfoto von 2018-12-28 22-46-54](https://user-images.githubusercontent.com/23266409/50529136-1a889480-0af3-11e9-8add-1c78840fb265.png)

**Comment by danrabbit** [comment] 2021-08-31 02:53
This should be fixed now for all Flatpak apps. It's possible for deb packages to have outdated information just because of the way it's fetched with apt and there's not really much we can do there.

Closing since it's as reasonably fixed as it can be for AppCenter apps

**Closed by danrabbit** 2021-08-31 02:53 UTC
