### ISSUE TITLE
Proposal: Use GitHub API to fetch and display release notes for updates

### ISSUE THREAD

**Issue by mikeanthonywild** [elementary/appcenter#303] opened 2017-05-20 11:25 UTC
Not sure if this is on the radar after the transition from Launchpad or not, but it would make sense to utilise GitHub's release feature to tag releases and pull notes to be displayed in the AppCenter.

**Comment by peteruithoven** [comment] 2017-05-20 11:29
There are already ideas for changelog, but independent of github: https://github.com/elementary/appcenter/issues/24

**Comment by mikeanthonywild** [comment] 2017-05-20 11:45
Thanks for pointing me towards that. I'm not familiar with AppStream - it seems like it would be a better solution (ie. it would work for all projects, not just those hosted in AppCenter).

**Comment by danrabbit** [comment] 2017-05-20 14:49
Closing as a duplicate of #24

**Closed by danrabbit** 2017-05-20 14:49 UTC
