### ISSUE TITLE
Error When Processing Payment

### ISSUE THREAD

**Issue by dcharles525** [elementary/appcenter#289] opened 2017-05-18 15:02 UTC
When paying for any application, an error occurs (screenshot below). The payment is being withheld in my bank so I think it went through. 

![screenshot from 2017-05-17 11 04 28](https://cloud.githubusercontent.com/assets/4961680/26208912/53a7d13c-3bb9-11e7-8457-16fca69ad794.png)

Keep up the amazing work! I know personally that payment processing isn't the easiest thing in the world.

**Comment by danrabbit** [comment] 2017-05-18 18:33
Working on this now in #282. It should just be a hold and not an actual charge so it should fall off. Let me know if it sticks and I can get a refund issued :)

**Comment by franky303** [comment] 2017-05-18 18:45
I'm seeing the same message.  First payment worked.  Second payment (within a short period of time) - got that error message. After waiting for a couple of minutes (10 or so), i could do 1 purchase again. Quickly tried another purchase within short time -> error message again.  Seems to be locked down for a couple of minutes after a previous purchase.

**Comment by cassidyjames** [comment] 2017-05-19 14:23
@franky303 thanks so much for debugging. Let me know if there were any duplicate charges or anything weird showing up on your end and we can take care of it.

**Comment by franky303** [comment] 2017-05-19 14:43
Visa was upset today, they've sent me an SMS, called me twice AND sent me an email. :-)  I couldn't see any charges yet but i told them they can approve all of them.  You do NOT need to refund any duplicates, in case you see any.

**Comment by anarresti** [comment] 2017-05-21 15:00
This happened to me too, when trying to pay for Nimbus. And I can confirm I was not charged for Nimbus. But when I chose pay later, I got the same message I had when trying to install Vocal: "E: https://packages.elementary.io/appcenter xenial/mainamd64 com.github.danrabbit.nimbus am is no (yet) available (Protocol “http” not supported or disabled in libcurl)" For Vocal I was charged (and I'm glad I was was finally able to give back, congratz everyone for put the Appstore online!!). But I haven't been able to download apps that have the pay-what-you-want button. Do I need to do anything else at this point?

**Comment by danrabbit** [comment] 2017-05-21 15:48
@anarresti it seems like your issue is with your software sources list. You probably manually added the repository before it was released. You'll need to edit your sources.list (in `etc/apt/sources.list`) so that it reads `http` and not `https`

**Comment by danrabbit** [comment] 2017-05-21 15:50
Going to close this ticket since a new update was pushed with better error reporting and we recently resolved some payment issues with a couple apps on the store. Please re-open if you're still having issues :)

**Closed by danrabbit** 2017-05-21 15:50 UTC
Labels: Priority: Critical

**Comment by phocean** [comment] 2018-01-28 09:58
Hi,

I am having the same sort of issue.

I could make some payments at first, but since a few days ago, it has stopped working with the same cryptic, too generic error message.

Note that I have tried with 2 different banks and 3 credit cards, so an issue on this side is excluded.

**Comment by phocean** [comment] 2018-01-28 10:04
Well, I managed to pay once in something like 20 attempts, so there is definitely something wrong with the API of the service.

**Comment by peteruithoven** [comment] 2018-01-28 10:14
I had the same issue, but I opened an issue for the specific app I was trying to pay for: https://github.com/mdh34/quickDocs/issues/13 
It turned out to be, mostly, a configuration issue. Unless you have this issue with multiple apps I would suggest opening an issue for the specific app.

**Comment by phocean** [comment] 2018-01-28 10:15
I am, of course, having this issue with multiple apps.
