### ISSUE TITLE
AppCenter takes about 15 seconds to load completely

### ISSUE THREAD

**Issue by kdwk** [elementary/appcenter#1714] opened 2021-10-07 10:25 UTC
### What Happened?

https://user-images.githubusercontent.com/39268094/136366353-ecde393f-c80e-4f45-83bb-1f8866af9f3a.mp4

As shown in the video, AppCenter takes about 15 seconds to load completely. Not only does this keep the user waiting, but before loading is complete AppCenter does not know which app the user has installed, so installed apps show as uninstalled, causing great confusion

### Steps to Reproduce

1. Open AppCenter
2. Immediately after it loads the carousel, but before the activity spinner stops, click something on the carousel that you have installed.
3. The app does not show as installed. After the activity spinner stops, it shows correctly as installed again.

### Expected Behavior

AppCenter should finish loading quickly and immediately know which apps are installed.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by danrabbit** [comment] 2022-09-03 19:22
Closing as a duplicate of #1471

**Closed by danrabbit** 2022-09-03 19:22 UTC
