### ISSUE TITLE
Dark mode can't be turned on in non-curated apps - even in those that support it

### ISSUE THREAD

**Issue by JohnDumpling** [elementary/appcenter#1624] opened 2021-08-23 10:18 UTC
## What Happened
When I open a non-curated app from the AppCenter (PulseEffects for instance), dark mode is not turned on (app doesn't detect it). What is more, when I turn on dark mode from inside of the app, nothing happens, even after system restart:
![image](https://user-images.githubusercontent.com/89086803/130430719-5c8c03ac-24fe-4246-8e07-0bd1aef2303b.png)
Even popular apps like LibreOffice don't detect the dark mode:
![image](https://user-images.githubusercontent.com/89086803/130430982-263b2adf-83ed-4989-a91b-4e5db0324319.png)

## Expected Behavior
An app should automatically turn on dark mode (if it is supported), even non-curated apps if possible

## Steps to Reproduce
1. Open any non-curated app that should support dark mode and open it.
2. Dark mode shouldn't work or turn on automatically.

## Platform Information
Lenovo Legion 5 running elementary OS 6 (latest release)

**Comment by danrabbit** [comment] 2021-08-23 17:09
Closing as a duplicate of https://github.com/elementary/stylesheet/issues/1075

**Closed by danrabbit** 2021-08-23 17:09 UTC
